### ISSUE TITLE
asr出错

### ISSUE THREAD

**Issue by sshnuke3** [PaddlePaddle/PaddleSpeech#1276]
[2022-01-06 11:21:08,920] [    INFO] - audio feat shape: [1, 32104, 80]
ERROR: Exception on /asr [POST]
Traceback (most recent call last):
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 32, in asr_from_file
    device=paddle.get_device())
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/cli/asr/infer.py", line 446, in __call__
    self.infer(model)
  File "/root/tools/env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/tools/env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/cli/asr/infer.py", line 320, in infer
    simulate_streaming=cfg.simulate_streaming)
  File "/root/tools/env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/tools/env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 802, in decode
    simulate_streaming=simulate_streaming)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 579, in attention_rescoring
    num_decoding_left_chunks, simulate_streaming)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 465, in _ctc_prefix_beam_search
    simulate_streaming)  # (B, maxlen, encoder_dim)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 268, in _forward_encoder
    num_decoding_left_chunks=num_decoding_left_chunks
  File "/root/tools/env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/modules/encoder.py", line 167, in forward
    xs, pos_emb, masks = self.embed(xs, masks.astype(xs.dtype), offset=0)
  File "/root/tools/env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/modules/subsampling.py", line 141, in forward
    x, pos_emb = self.pos_enc(x, offset)
  File "/root/tools/env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/s2t/modules/embedding.py", line 161, in forward
    assert offset + x.shape[1] < self.max_len
AssertionError

相关代码
    19  @app.route('/asr', methods=['GET', 'POST'])
    20  def asr_from_file():
    21      if request.method == 'POST':
    22          file = request.files['the_file']
    23          file.save(f"/www/example/upload/{secure_filename(file.filename)}")
    24          result1 = asr_executor(
    25              model='conformer_wenetspeech',
    26              lang='zh',
    27              sample_rate=16000,
    28              config=None,  # Set `config` and `ckpt_path` to None to use pretrained model.
    29              ckpt_path=None,
    30              audio_file=f"/www/example/upload/{secure_filename(file.filename)}",
    31              force_yes=True,
    32              device=paddle.get_device())
    33          result2 = text_executor(
    34              text=format(result1),
    35              task='punc',
    36              model='ernie_linear_p7_wudao',
    37              lang='zh',
    38              config=None,
    39              ckpt_path=None,
    40              punc_vocab=None,
    41              device=paddle.get_device())
    42          return {
    43                  "asr_result":format(result1),
    44                  "punc_result":format(result2)
    45              },200

显卡驱动
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:07.0 Off |                    0 |
| N/A   45C    P0    28W /  70W |   6232MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      8487      C   python                                      6221MiB |
+-----------------------------------------------------------------------------+

**Comment by yt605155624** [comment]
输入音频太长，现在 asr 的音频要求 50s 以下，长音频需要自己剪裁一下

**Comment by sshnuke3** [comment]
了解
