### ISSUE TITLE
tts出错

### ISSUE THREAD

**Issue by sshnuke3** [PaddlePaddle/PaddleSpeech#1277]
[2022-01-06 13:39:46,020] [    INFO] [log.py] [L57] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz
ERROR: Exception on /tts [POST]
Traceback (most recent call last):
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/tools/env/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 66, in tts_to_file
    device=paddle.get_device())
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/cli/tts/infer.py", line 639, in __call__
    self.infer(text=text, lang=lang, am=am, spk_id=spk_id)
  File "/root/tools/env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/tools/env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/cli/tts/infer.py", line 511, in infer
    text, merge_sentences=True, get_tone_ids=get_tone_ids)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/t2s/frontend/zh_frontend.py", line 269, in get_input_ids
    robot=robot)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/t2s/frontend/zh_frontend.py", line 236, in get_phonemes
    sentences, merge_sentences=merge_sentences, with_erhua=with_erhua)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/t2s/frontend/zh_frontend.py", line 117, in _g2p
    sub_finals)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/t2s/frontend/tone_sandhi.py", line 342, in modified_tone
    finals = self._three_sandhi(word, finals)
  File "/root/tools/env/lib/python3.7/site-packages/paddlespeech/t2s/frontend/tone_sandhi.py", line 200, in _three_sandhi
    sub[0] = sub[0][:-1] + "2"
IndexError: list index out of range
self.phones_dict: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
self.phones_dict: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
vocab_size: 268
frontend done!
encoder_type is transformer
decoder_type is transformer
acoustic model done!
voc done!

**Comment by yt605155624** [comment]
这个是文本前端出错，和具体的输入有关，可以把输入发出来，或者把输入里面不规范的东西换成中文

**Comment by sshnuke3** [comment]
可能是从网页上复制文本时候带了不可见字符了
