### ISSUE TITLE
[tts] fastspeech2 aishell3 动转静报错

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1338]
https://github.com/PaddlePaddle/PaddleSpeech/blob/dae6bea546dc2123eb7c3f76661bb152efb96167/paddlespeech/t2s/exps/synthesize_e2e.py#L160-L164
我想要导出fastspeech2的多人静态模型，然后把下面的单人模型的动转静代码复制了过来，但是导出静态模型的时候报错：
```
Traceback (most recent call last):
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 350, in <module>
    main()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 346, in main
    evaluate(args)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 232, in evaluate
    mel = am_inference(part_phone_ids, spk_id)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/io.py", line 1274, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/io.py", line 766, in _run_dygraph
    var.name = program_holder.input_descs[i].name()
IndexError: list index out of range
```

**Comment by yt605155624** [comment]
单说话人输入只有 phone, 多说话人输入有 phone 和 spk 两个，不能直接复制过来吧

**Comment by jerryuhoo** [comment]
我还是不太懂这个应该怎么改，是input_spec的问题吗？InputSpec这个是指输入的text序列吗？为啥fastspeech只有一个，speedyspeech有两个？输入不是应该有很多吗，包括phone，text，stats等等

**Comment by yt605155624** [comment]
InputSpec 的输入的个数就是你调用模型时候的输入，目前 speedyspeech 有 phones 和 tones 2 个输入，fastspeech2 有 phones 一个输入，多 spk 的 fastspeech2 应该有 phones 和 spk 两个输入

**Comment by jerryuhoo** [comment]
如果改为这样又会报另外一个错
```python
if am_dataset in {"aishell3", "vctk"} and args.speaker_dict:
    am_inference_static = jit.to_static(
        am_inference,
        input_spec=[
            InputSpec([-1], dtype=paddle.int64),
            InputSpec([-1], dtype=paddle.int64)
        ])
    paddle.jit.save(am_inference_static,
                    os.path.join(args.inference_dir, args.am))
    am_inference_static = paddle.jit.load(
        os.path.join(args.inference_dir, args.am))
```
```
Traceback (most recent call last):
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 353, in <module>
    main()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 349, in main
    evaluate(args)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 235, in evaluate
    mel = am_inference(part_phone_ids, spk_id)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 376, in __call__
    error_data.raise_new_exception()
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 871, in forward
        normalized_mel, d_outs, p_outs, e_outs = self.acoustic_model.inference(
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 751, in inference
        _, outs, d_outs, p_outs, e_outs = self._forward(
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 614, in _forward
            d_outs = ds
        else:
            d_outs = self.duration_predictor.inference(hs, d_masks)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        if ps is not None:
            p_outs = ps

    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/modules/predictor/duration_predictor.py", line 138, in inference
        return self._forward(xs, x_masks, True)
    File "/tmp/tmp1gw8xk_c.py", line 40, in _forward
        xs = paddle.jit.dy2static.convert_ifelse(x_masks is not None,
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
        out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 271, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/modules/predictor/duration_predictor.py", line 102, in _forward
        xs = masked_fill(xs, x_masks, 0.0)
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/modules/masked_fill.py", line 44, in masked_fill
        mask = mask.broadcast_to(bshape)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 1835, in broadcast_to
        helper.append_op(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
        return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
        op = Operator(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
        for frame in traceback.extract_stack():

    InvalidArgumentError: The value (24) of the non-singleton dimension does not match the corresponding value (1) in shape for expand_v2 op.
      [Hint: Expected vec_in_dims[i] == expand_shape[i], but received vec_in_dims[i]:24 != expand_shape[i]:1.] (at /paddle/paddle/fluid/operators/expand_v2_op.h:172)
      [operator < expand_v2 > error]  [operator < run_program > error]
```

**Comment by yt605155624** [comment]
参考 动转静 文档 debug 吧
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/index_cn.html
我暂时没有时间做这方面的工作了

**Comment by jerryuhoo** [comment]
嗯好的，我看看

**Comment by jerryuhoo** [comment]
fastspeech2的多人动转静依旧没成功，多人speedyspeech倒是成功了，我觉得可能是没有传入所有inference的参数？于是我尝试了下styleInference的动转静，发现如下报错
```
TypeError: In transformed code:

    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 996, in forward
        normalized_mel, d_outs, p_outs, e_outs = self.acoustic_model.inference(
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 738, in inference
        _, outs, d_outs, p_outs, e_outs = self._forward(
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 601, in _forward
        p_outs = self.pitch_predictor(hs.detach(), d_masks.unsqueeze(-1))
    File "/tmp/tmpwm5y187g.py", line 33, in forward
        [__for_loop_var_index_5, xs] = paddle.jit.dy2static.convert_while_loop(
    File "/tmp/tmpwm5y187g.py", line 30, in for_loop_body_3
        xs = paddle.jit.dy2static.convert_call(__for_loop_iter_var_3)(xs)
    File "/tmp/tmpq86c5uj6.py", line 7, in forward
        input = paddle.jit.dy2static.convert_call(layer)(input)
    File "/tmp/tmpj024ozjm.py", line 52, in forward
        __return_value_0 = paddle.jit.dy2static.convert_ifelse(self.dim == -1,
    File "/tmp/tmpj024ozjm.py", line 41, in false_fn_42
            false_fn_41, (len_dim, self), (), ())
        paddle.jit.dy2static.convert_assert(self.dim >= 0)
        orig_perm = list(range(len_dim))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        new_perm = orig_perm[:]
        temp = new_perm[self.dim]


    TypeError: 'Variable' object cannot be interpreted as an integer
```
定位到了这里，看到了这个注释“Python style item change is not able when converting dygraph to static graph. ”，这个意思是没有办法把style inference转成静态图吗？原因是什么呢？
https://github.com/PaddlePaddle/PaddleSpeech/blob/d368d57d67ec8239c42a25a95e56d534cf23b005/paddlespeech/t2s/modules/layer_norm.py#L57-L61

**Comment by yt605155624** [comment]
就是如果想把数组中的两个值交换，用 python 的常规方式，是没有办法动转静的
```python
new_perm[self.dim], new_perm[len_dim -1] = new_perm[len_dim -1], new_perm[self.dim] 
```
因为 paddle 底层是依赖 c++ 的，所以此处要换成 c++ 的交换值的方式，即 先把值赋值给一个中间值 temp 之后再交换数值

fastspeech2 的多说话人动转静尚且不成功， styleInference 肯定更难呀，因为输入更多了。。fastspeech2 的多说话人动转静不成功应该和此处的报错无关

**Comment by yt605155624** [comment]
我看了下 aishell3 的 fastspeech2 的动转静模型是成功保存下来的
![image](https://user-images.githubusercontent.com/24568452/149861432-07e9fd92-cc07-4deb-b142-0ddcb14ed3f9.png)

但是在调用的时候报错了
```text
ValueError: (InvalidArgument) The value (24) of the non-singleton dimension does not match the corresponding value (1) in shape for expand_v2 op.
  [Hint: Expected vec_in_dims[i] == expand_shape[i], but received vec_in_dims[i]:24 != expand_shape[i]:1.] (at /paddle/paddle/fluid/operators/expand_v2_op.h:172)
  [operator < expand_v2 > error]  [operator < run_program > error]
```
看了下 `24` 是 `len(part_phone_ids)`, `1` 是 `len(spk_id)`, 为什么报错暂时未知

**Comment by yt605155624** [comment]
debug 了一下 https://github.com/PaddlePaddle/PaddleSpeech/blob/4a133619a14146f5da5398ea6315a93a7ea06bb0/paddlespeech/t2s/models/fastspeech2/fastspeech2.py#L784 此处的 hs.shape[1] 换成 paddle.shape(hs)[1] 即可，shape 是动转静里面的大坑，因为 tensor.shape 是 list ，但是 paddle.shape 是 Tensor, 动转静仅仅能识别 Tensor，当时走通动转静就要把很多 .shape 换成 paddle.shape, 参考 https://github.com/PaddlePaddle/PaddleSpeech/pull/948
pr 今天提交

**Comment by jerryuhoo** [comment]
感谢感谢！我不太懂动转静卡了好久~
