### ISSUE TITLE
[tts] StyleFastSpeech2Inference 改进/动转静问题

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1384]
之前StyleFastSpeech2Inference遇到动转静报错 #1338
我发现好像原因是在StyleFastSpeech2Inference里调用了两次模型，可能是报错的原因？然后我觉得可以改进一下，直接在_forward里面完成对duration，energy，pitch的变化，尝试改进如下：
https://github.com/jerryuhoo/PaddleSpeech/commit/c3336e6e06b69de554ae3387092cd83a0cfe4990
但是有两个问题，一个是robot好像效果不是很明显？还有一个问题是动转静依然会报错，
动转静的代码为：
```python
am_inference = jit.to_static(
    am_inference,
    input_spec=[
        InputSpec([-1], dtype=paddle.int64), # text
        None,
        InputSpec([1], dtype=paddle.float32),
        InputSpec([1], dtype=paddle.float32),
        None,
        InputSpec([1], dtype=paddle.float32),
        InputSpec([1], dtype=paddle.float32),
        None,
        InputSpec([1], dtype=paddle.float32),
        InputSpec([1], dtype=paddle.float32),
        InputSpec([1], dtype=paddle.bool),
        None,
        None,
    ]
)
```
报错信息为：
```
Traceback (most recent call last):
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 415, in <module>
    main()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 411, in main
    evaluate(args)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 281, in evaluate
    mel = am_inference(part_phone_ids, None, 1.0, None , None, 1.3, None, None, 1, None, True, None, None)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 376, in __call__
    error_data.raise_new_exception()
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
RuntimeError: In transformed code:

    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 1020, in forward
        normalized_mel, d_outs, p_outs, e_outs = self.acoustic_model.inference(
    File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 823, in inference
        else:
            # (1, L, odim)
            _, outs, d_outs, p_outs, e_outs = self._forward(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                xs,
                ilens,

    File "/tmp/tmpbj7svjlf.py", line 243, in _forward
        d_outs, e_embs, e_outs, hs, p_embs, p_outs = (paddle.jit.dy2static.
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
        out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 271, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpbj7svjlf.py", line 204, in true_fn_23
        p_outs = paddle.jit.dy2static.convert_ifelse(robot, true_fn_22,
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 208, in convert_ifelse
        out = _run_paddle_cond(pred, true_fn, false_fn, true_args, false_args,
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 266, in _run_paddle_cond
        return control_flow.cond(pred, lambda: true_fn(*true_args),
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/control_flow.py", line 2468, in cond
        mask = cast(pred, dtype='int32')
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 264, in cast
        helper.append_op(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
        return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
        op = Operator(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
        for frame in traceback.extract_stack():

    PreconditionNotMetError: The tensor of Input(X) is not initialized.
      [Hint: Expected tensor->IsInitialized() == true, but received tensor->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/operators/cast_op.cc:78)
      [operator < cast > error]  [operator < run_program > error]

    Revise suggestion: 
        1. Please ensure all your sublayers are inheritted from nn.Layer.
        2. Please ensure there is no tensor created explicitly depended on external data, we suggest to register it as buffer tensor. See https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/export_model/principle_cn.html#parameters-buffers for details
```

**Comment by yt605155624** [comment]
StyleFastSpeech2Inference 输入很多，用户会根据需要决定输入某些值，所以动转静的输入也很复杂，有的输入你在 input_spec 里面定义了，调用的时候就是一定要输入的吧，但是用户未必想输入。。。 而且感觉本身的部署需求也不高，这边没有计划改了，你的复杂代码我也不计划合入了，如果你自己想走通动转静，可以
```
import pdb
pdb.set_trace()
```
单步调试

可以参考这里的调试方法：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/04_dygraph_to_static/debugging_cn.html#duandiantiaoshi

**Comment by jerryuhoo** [comment]
嗯好的，经过调试改好了。发现了两个主要报错的原因，一个是因为有些参数没转换成paddle tensor，还有一个是synthesize_e2e.py中在读取静态模型之后，`mel = am_inference(...)` 这里传入的参数不能为None，这个有个小问题如果老师您不嫌麻烦的话可以解答一下吗，就是这里传入的参数不能为None，比如说durations这种，那解决办法只有在inference类中的forward把这个给删了吗？我是这样做的，直接把stylefastspeech2inference里的use_teacher_forcing一整块删掉了，就不用两次预测了。现在已经改好代码了，我感觉在style inference上避免了两次使用模型还是有所改进的，但是如果不计划合入的话我就自己用用吧。

**Comment by yt605155624** [comment]
当时之所以加了 StyleFastSpeech2Inference 这个类，就是不想在 FastSpeech2 本身的类里改太多的东西，我看了你的代码是直接改了 FastSpeech2 里面的代码了
关于静态模型的机制我也不是很懂，静态模型的输入好像一旦设定了就必须传入的样子。。。

**Comment by jerryuhoo** [comment]
哈哈哈好吧确实，那我close这个issue吧
