### ISSUE TITLE
[tts] hifigan vocoder 修改超参数训练报错

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1388]
https://github.com/PaddlePaddle/PaddleSpeech/blob/446e83ad2534bc4e0643edba0b2c730c27d1a205/examples/csmsc/voc5/conf/default.yaml#L31-L32
根据原论文的超参数，我想试试把这两行修改为
```yaml
upsample_scales: [8, 8, 2, 2]         # Upsampling scales. 
upsample_kernel_sizes: [16, 16, 4, 4] # Kernel size for upsampling layers. 
```
但是报错
```
Exception in main training loop: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [8, 80, 24] and the shape of Y = [8, 80, 29]. Received [24] in X is not equal to [29] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_sub > error]
Traceback (most recent call last):
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 109, in update
    self.update_core(batch)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan_updater.py", line 100, in update_core
    mel_loss = self.criterion_mel(wav_, wav)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/modules/losses.py", line 923, in forward
    mel_loss = F.l1_loss(mel_hat, mel)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 690, in l1_loss
    unreduced = _elementwise_op_in_dygraph(
  File "/root/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 206, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
Trainer extensions will try to handle the extension. Then all extensions will finalize.Traceback (most recent call last):
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 275, in <module>
    main()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 271, in main
    train_sp(args, config)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 239, in train_sp
    trainer.run()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 198, in run
    six.reraise(*exc_info)
  File "/root/miniconda3/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 109, in update
    self.update_core(batch)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan_updater.py", line 100, in update_core
    mel_loss = self.criterion_mel(wav_, wav)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/workspace/code/PaddleSpeech/paddlespeech/t2s/modules/losses.py", line 923, in forward
    mel_loss = F.l1_loss(mel_hat, mel)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 690, in l1_loss
    unreduced = _elementwise_op_in_dygraph(
  File "/root/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 206, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [8, 80, 24] and the shape of Y = [8, 80, 29]. Received [24] in X is not equal to [29] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_sub > error]
```

**Comment by jerryuhoo** [comment]
问题解决了，n_shift需要等于upsample_scales里的参数相乘
