### ISSUE TITLE
ERROR: ImportError: cannot import name '__version__' from 'paddlespeech' 

### ISSUE THREAD

**Issue by iamfoolberg** [PaddlePaddle/PaddleSpeech#1395]
Hi there, when i managed to execute the demo command:
`(/home/berg/PaddleSpeech/tools/venvs) root@bergtts:~/PaddleSpeech# paddlespeech tts --input "你好，欢迎使用飞桨深度学习框架！" --output output.wav`

it complains the following error.

```
Traceback (most recent call last):
  File "/home/berg/PaddleSpeech/tools/venvs/bin/paddlespeech", line 33, in <module>
    sys.exit(load_entry_point('paddlespeech', 'console_scripts', 'paddlespeech')())
  File "/home/berg/PaddleSpeech/tools/venvs/bin/paddlespeech", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/berg/PaddleSpeech/tools/venvs/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/home/berg/PaddleSpeech/tools/venvs/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/berg/PaddleSpeech/paddlespeech/cli/__init__.py", line 16, in <module>
    from .asr import ASRExecutor
  File "/home/berg/PaddleSpeech/paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "/home/berg/PaddleSpeech/paddlespeech/cli/asr/infer.py", line 30, in <module>
    from ..utils import cli_register
  File "/home/berg/PaddleSpeech/paddlespeech/cli/utils.py", line 33, in <module>
    from .. import __version__
ImportError: cannot import name '__version__' from 'paddlespeech' (/home/berg/PaddleSpeech/paddlespeech/__init__.py)

```
After installing miniconda in ubuntu 18.04.3, i changed to root, and go on creating the venvs and executing pip installs...
`#conda create -y -p tools/venvs python=3.7 `

**Comment by iamfoolberg** [comment]
#comment the last line in setup.py
`#remove_version_py()`

#add the line in paddlespeech/__init__.py
`__version__ = '0.1.1'`

Finally, i heard the voice:)

NICE WORK, but make the docs more comfortable plz.
