### ISSUE TITLE
any idea about the error when run "bash run.sh"? 

### ISSUE THREAD

**Issue by everschen** [PaddlePaddle/PaddleSpeech#1468]
Generate durations.txt from MFA results ...
Traceback (most recent call last):
  File "/PaddleSpeech/utils/gen_duration_from_textgrid.py", line 113, in <module>
    main()
  File "/PaddleSpeech/utils/gen_duration_from_textgrid.py", line 109, in main
    gen_duration_from_textgrid(inputdir, output, config.fs, config.n_shift)
  File "/PaddleSpeech/utils/gen_duration_from_textgrid.py", line 68, in gen_duration_from_textgrid
    list_dir = os.listdir(inputdir)
FileNotFoundError: [Errno 2] No such file or directory: 'baker_alignment_tone'
Extract features ...
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../preprocess.py", line 292, in <module>
    main()
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../preprocess.py", line 183, in main
    assert rootdir.is_dir()
AssertionError
Get features' stats ...
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/PaddleSpeech/utils/compute_statistics.py", line 109, in <module>
    main()
  File "/PaddleSpeech/utils/compute_statistics.py", line 84, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'
Normalize ...
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../normalize.py", line 133, in <module>
    main()
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../normalize.py", line 81, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../normalize.py", line 133, in <module>
    main()
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../normalize.py", line 81, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/dev/raw/metadata.jsonl'
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../normalize.py", line 133, in <module>
    main()
  File "/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/parallelwave_gan/../normalize.py", line 81, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/test/raw/metadata.jsonl'

**Comment by everschen** [comment]
FYI, I use "Hard: Get the Full Function (Support Ubuntu), Choice 1: Running in Docker Container (Recommend)", all the steps of choice 1 has been finished successfully.

**Comment by yt605155624** [comment]
You should follow the readme download the dataset and baker_alignment_tone.tar.gz and unzip to the right dir

**Comment by everschen** [comment]
thanks, I didn't see any guide of downloading dataset for choice 1, maybe it handle by script? however it seems inside the docker there's some problem to download dataset.( I have downloaded ntlk by manual for this reason) I saw "Now you can execute training, inference, and hyper-parameters tuning in Docker container." at the end of choice 1, I suppose it's ready to continue.

**Comment by yt605155624** [comment]
We have provided README.md for every example， please see https://github.com/PaddlePaddle/PaddleSpeech/tree/19f67e1f564f1dcd49b89159b39bb4a34b7b6cdd/examples/csmsc/tts3

**Comment by everschen** [comment]
aha, got it, thank you so much and have a nice night!
