### ISSUE TITLE
官方示例：automatic_video_subtitiles  换了一个大视频就出错了 错误信息如下 

### ISSUE THREAD

**Issue by xueyangkk** [PaddlePaddle/PaddleSpeech#1529]
华为云AI服务器 2核心8G 无GPU

官方的视频使用起来没有任何问题 

自己视频网上随便下的，转换后可以播放，只是想比较官方提供的示例大了很多

`
(/opt/ai/PaddleSpeech/tools/venv) root@ecs-58b4:/opt/workSpace/automatic_video_subtitiles# ./run.sh 
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[2022-03-03 17:31:49,028] [    INFO] - checking the audio file format......
[2022-03-03 17:31:49,033] [    INFO] - The sample rate is 16000
[2022-03-03 17:31:49,033] [    INFO] - The audio file format is right
[2022-03-03 17:31:49,033] [    INFO] - File /root/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-03-03 17:31:53,137] [    INFO] - Use pretrained model stored in: /root/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar
[2022-03-03 17:31:53,138] [    INFO] - /root/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar
[2022-03-03 17:31:53,138] [    INFO] - /root/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/model.yaml
[2022-03-03 17:31:53,138] [    INFO] - /root/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/exp/conformer/checkpoints/wenetspeech.pdparams
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: paddlespeech_ctcdecoders in /opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages (0.1.1)
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2022-03-03 17:31:58,449] [    INFO] - Preprocess audio_file:/opt/workSpace/automatic_video_subtitiles/subtitle_demo1.wav
[2022-03-03 17:31:58,449] [    INFO] - get the preprocess conf
[2022-03-03 17:31:58,478] [    INFO] - read the audio file
[2022-03-03 17:31:58,480] [    INFO] - audio shape: (4789627,)
[2022-03-03 17:32:01,084] [    INFO] - audio feat shape: [1, 29933, 80]
Traceback (most recent call last):
  File "recognize.py", line 35, in <module>
    device=args.device)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/utils.py", line 338, in _warpper
    return executor_func(self, *args, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/asr/infer.py", line 536, in __call__
    self.infer(model)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/asr/infer.py", line 381, in infer
    simulate_streaming=cfg.simulate_streaming)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 751, in decode
    simulate_streaming=simulate_streaming)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 528, in attention_rescoring
    num_decoding_left_chunks, simulate_streaming)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 414, in _ctc_prefix_beam_search
    simulate_streaming)  # (B, maxlen, encoder_dim)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/models/u2/u2.py", line 217, in _forward_encoder
    num_decoding_left_chunks=num_decoding_left_chunks
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/modules/encoder.py", line 167, in forward
    xs, pos_emb, masks = self.embed(xs, masks.astype(xs.dtype), offset=0)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/modules/subsampling.py", line 141, in forward
    x, pos_emb = self.pos_enc(x, offset)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech/s2t/modules/embedding.py", line 161, in forward
    assert offset + x.shape[1] < self.max_len
AssertionError
(/opt/ai/PaddleSpeech/tools/venv) root@ecs-58b4:/opt/workSpace/automatic_video_subtitiles# 
`

**Comment by yt605155624** [comment]
same as https://github.com/PaddlePaddle/PaddleSpeech/issues/1527
