### ISSUE TITLE
按照官方的安装方法，提示找不到 paddleaudio 这个包。

### ISSUE THREAD

**Issue by allenxln** [PaddlePaddle/PaddleSpeech#1573]
安装完成以后，运行 paddlespeech命令，提示：
Traceback (most recent call last):
  File "/home/allen/.aliot/miniconda3/envs/paddle_env/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/home/allen/.aliot/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .asr import ASRExecutor
  File "/home/allen/.aliot/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "/home/allen/.aliot/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddlespeech/cli/asr/infer.py", line 31, in <module>
    from ..utils import cli_register
  File "/home/allen/.aliot/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddlespeech/cli/utils.py", line 31, in <module>
    import paddleaudio
ModuleNotFoundError: No module named 'paddleaudio'

试了一下 pip install paddleaudio 也没问题。请问如何解？谢谢

**Comment by zh794390558** [comment]
可能没有安装到 /home/allen/.aliot/miniconda3/envs/ 里

**Comment by thomascatlee** [comment]
版本要一致，0.1.0对应0.1.0，0.2.0对应0.2.0
