### ISSUE TITLE
numpy.ndarray has the wrong size, try recompiling

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleSpeech#1584]
最新的develop版本，测试demo的时候报错

Traceback (most recent call last):
  File "demos/automatic_video_subtitiles/recognize.py", line 22, in <module>
    from paddlespeech.cli import ASRExecutor
  File "./paddlespeech/cli/__init__.py", line 16, in <module>
    from .asr import ASRExecutor
  File "./paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "./paddlespeech/cli/asr/infer.py", line 31, in <module>
    from ..utils import cli_register
  File "./paddlespeech/cli/utils.py", line 31, in <module>
    import paddleaudio
  File "./paddleaudio/__init__.py", line 19, in <module>
    from . import metric
  File "./paddleaudio/metric/__init__.py", line 15, in <module>
    from .mcd import mcd_distance
  File "./paddleaudio/metric/mcd.py", line 14, in <module>
    import mcd.metrics_fast as mt
  File "__init__.pxd", line 178, in init mcd.metrics_fast (mcd/metrics_fast.c:4107)
ValueError: numpy.ndarray has the wrong size, try recompiling

**Comment by zh794390558** [comment]
`sudo apt-get install python-numpy`后再运行试试。

**Comment by yangy996** [comment]
> `sudo apt-get install python-numpy`后再运行试试。

不行 还是报错

**Comment by yangy996** [comment]
我是单个安装的，然后报这个错误，按文档脚本批量安装代码是正常的，不知道是什么原因照成的

**Comment by w5688414** [comment]
I solve this problem by running:

```
pip install numpy --upgrade
```
