### ISSUE TITLE
aishell asr0 如何使用现有模型推理？

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1671]
目前ASR的README里的模型好像不是最新的？根据这里下载好的模型之后，运行run.sh，stage设为6，但是会报config的错，看了下README里下载的和conf里的不同。
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/aishell/asr0/README.md#pretrained-model
然后我又找到了https://github.com/PaddlePaddle/PaddleSpeech/blob/82cd7015d749eccc14e170b63e03ff36e125c6f2/docs/source/released_model.md
这里的ds offline模型，然后报错
```FileNotFoundError: [Errno 2] No such file or directory: 'data/manifest.test'```
这个文件是preprocess生成的，但是为什么不一起放在能下载的模型里呢？
如果要调用已有的ds2 online/offline模型，应该下载哪个模型，如何操作呢？
我看到脚本也会自动下载模型，是存放在这个位置吗```~/.paddlespeech/models/``` ？
感谢解答！

**Comment by zh794390558** [comment]
模型推理可以参看CLI的代码。example主要用于从数据集训练。pretrianed的model发布的配置文件只包含推理需要的信息，训练相关的manifeset.test这些不会打包的，需要参看examples/asr0/conf中的配置文件修改。

**Comment by zh794390558** [comment]
可以参考下 https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-Saved-Model-Config

**Comment by jerryuhoo** [comment]
好的，再请教个问题，在demos/automatic_video_subtitiles中运行run.sh，我把model改为deepspeech2online_aishell。但是好像无法成功下载模型？conformer_wenetspeech和deepspeech2offline_aishell都没问题。
报错如下：
```
[2022-04-08 06:25:11,467] [    INFO] - checking the audio file format......
[2022-04-08 06:25:11,467] [    INFO] - The sample rate is 16000
[2022-04-08 06:25:11,467] [    INFO] - The audio file format is right
[2022-04-08 06:25:11,469] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-04-08 06:25:12,240] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 check failed, 48bdf4bece60024a8cbd602f550bf69e(calc) != d5e076217cf60486519f72c217d21b9b(base)
[2022-04-08 06:25:12,241] [    INFO] - unique_endpoints {''}
[2022-04-08 06:25:12,243] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-04-08 06:25:12,919] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 check failed, 48bdf4bece60024a8cbd602f550bf69e(calc) != d5e076217cf60486519f72c217d21b9b(base)
[2022-04-08 06:25:12,920] [    INFO] - Downloading asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz from https://paddlespeech.bj.bcebos.com/s2t/aishell/asr0/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz
[2022-04-08 06:25:12,920] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-04-08 06:25:13,590] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 check failed, 48bdf4bece60024a8cbd602f550bf69e(calc) != d5e076217cf60486519f72c217d21b9b(base)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 499004/499004 [01:15<00:00, 6573.26it/s][2022-04-08 06:26:29,969] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-04-08 06:26:30,612] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 check failed, 48bdf4bece60024a8cbd602f550bf69e(calc) != d5e076217cf60486519f72c217d21b9b(base)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 499004/499004 [00:40<00:00, 12348.63it/s][2022-04-08 06:27:11,415] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-04-08 06:27:12,052] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 check failed, 48bdf4bece60024a8cbd602f550bf69e(calc) != d5e076217cf60486519f72c217d21b9b(base)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 499004/499004 [01:26<00:00, 5774.96it/s][2022-04-08 06:28:38,803] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-04-08 06:28:39,439] [    INFO] - File /root/.paddlespeech/models/deepspeech2online_aishell-zh-16k/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz md5 check failed, 48bdf4bece60024a8cbd602f550bf69e(calc) != d5e076217cf60486519f72c217d21b9b(base)
Traceback (most recent call last):
  File "recognize.py", line 33, in <module>
    text = asr_executor(
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 338, in _warpper
    return executor_func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 533, in __call__
    self._init_from_path(model, lang, sample_rate, config, decode_method,
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 229, in _init_from_path
    res_path = self._get_pretrained_path(tag)  # wenetspeech_zh
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 204, in _get_pretrained_path
    decompressed_path = download_and_decompress(pretrained_models[tag],
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 128, in download_and_decompress
    uncompress_path = download.get_path_from_url(archive['url'], path,
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/download.py", line 102, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum, method=method)
  File "/root/miniconda3/lib/python3.8/site-packages/paddlespeech/cli/download.py", line 198, in _download
    raise RuntimeError("Download from {} failed. "
RuntimeError: Download from https://paddlespeech.bj.bcebos.com/s2t/aishell/asr0/asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz failed. Retry limit reached
```

**Comment by zh794390558** [comment]
用develop的代码吧，asr0_deepspeech2_online_aishell_ckpt_0.1.1.model.tar.gz  这个资源修改过所以md5不对。后面修复下。

**Comment by Jackwaterveg** [comment]
资源问题已经修复

**Comment by zyb8543d** [comment]
> 资源问题已经修复

@Jackwaterveg 依然遇到了同样的问题：
```
constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
RuntimeError: Download from https://paddlespeech.bj.bcebos.com/s2t/wenetspeech/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz failed.
```
