### ISSUE TITLE
csmsc/voc5 onnx模型加载有误

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/PaddleSpeech#1684]
- 测试[hifigan_csmsc_onnx_0.2.0](https://paddlespeech.bj.bcebos.com/Parakeet/released_models/hifigan/hifigan_csmsc_onnx_0.2.0.zip)时，报错：
```python
>>> import onnx
>>> model = onnx.load('pretrained_model/fastspeech2_csmsc_onnx_0.2.0/hifigan_csmsc.onnx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/onnx/__init__.py", line 121, in load_model
    model = load_model_from_string(s, format=format)
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/onnx/__init__.py", line 158, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/onnx/__init__.py", line 99, in _deserialize
    decoded = cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message
```
- 测试环境：
```text
OS: CentOS
Python: 3.7
onnx: 1.10.1
```

**Comment by yt605155624** [comment]
用 onnxruntime 试试，用原生 onnx 可能需要先对模型进行 simplify

**Comment by jiangjiajun** [comment]
onnx需升级至最新
```
pip install onnx --upgrade
```

**Comment by SWHL** [comment]
感谢，问题解决了， 原因是我这边下载这个模型没有下载完全
