### ISSUE TITLE
csmsc/tts3 推理报错:Tensor holds the wrong type, it holds int64_t, but desires to be int

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/PaddleSpeech#1685]
### 测试环境:
  ```text
  OS: CentOS
  python: 3.7
  paddlepaddle-gpu: 2.2.2.post101
  ```

### 运行代码
- 提前下载好`pretrained_model`到`${MAIN_ROOT}`下
  ```text
  pretrained_model/
  ├── fastspeech2_nosil_baker_ckpt_0.4
  │   ├── default.yaml
  │   ├── energy_stats.npy
  │   ├── phone_id_map.txt
  │   ├── pitch_stats.npy
  │   ├── snapshot_iter_76000.pdz
  │   └── speech_stats.npy
  └── pwg_baker_ckpt_0.4
      ├── pwg_default.yaml
      ├── pwg_snapshot_iter_400000.pdz
      └── pwg_stats.npy
  ```
- 在`examples/csmsc/tts3`创建`main.sh`脚本，输入以下代码：
    ```bash
    source path.sh
    
    FLAGS_allocator_strategy=naive_best_fit \
    FLAGS_fraction_of_gpu_memory_to_use=0.01 \
    
    model_dir="${MAIN_ROOT}/pretrained_model"
    
    python ${BIN_DIR}/../synthesize_e2e.py \
      --am=fastspeech2_csmsc \
      --am_config"=${model_dir}/fastspeech2_nosil_baker_ckpt_0.4/default.yaml" \
      --am_ckpt="${model_dir}/fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz" \
      --am_stat="${model_dir}/fastspeech2_nosil_baker_ckpt_0.4/speech_stats.npy"  \
      --voc=pwgan_csmsc \
      --voc_config="${model_dir}/pwg_baker_ckpt_0.4/pwg_default.yaml" \
      --voc_ckpt="${model_dir}/pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz" \
      --voc_stat="${model_dir}/pwg_baker_ckpt_0.4/pwg_stats.npy" \
      --lang=zh \
      --text=${BIN_DIR}/../sentences.txt \
      --output_dir=exp/default/test_e2e \
      --inference_dir=exp/default/inference \
      --phones_dict="${model_dir}/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt"
    ```
#### 报错信息
```python
========Args========
am: fastspeech2_csmsc
am_ckpt: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz
am_config: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/fastspeech2_nosil_baker_ckpt_0.4/default.yaml
am_stat: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/fastspeech2_nosil_baker_ckpt_0.4/speech_stats.npy
inference_dir: exp/default/inference
lang: zh
ngpu: 1
output_dir: exp/default/test_e2e
phones_dict: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
speaker_dict: null
spk_id: 0
text: /da2/SWHL/_exp/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../sentences.txt
tones_dict: null
voc: pwgan_csmsc
voc_ckpt: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz
voc_config: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/pwg_baker_ckpt_0.4/pwg_default.yaml
voc_stat: /da2/SWHL/_exp/PaddleSpeech-develop/pretrained_model/pwg_baker_ckpt_0.4/pwg_stats.npy

========Config========
batch_size: 64
f0max: 400
f0min: 80
fmax: 7600
fmin: 80
fs: 24000
max_epoch: 1000
model:
  adim: 384
  aheads: 2
  decoder_normalize_before: True
  dlayers: 4
  dunits: 1536
  duration_predictor_chans: 256
  duration_predictor_kernel_size: 3
  duration_predictor_layers: 2
  elayers: 4
  encoder_normalize_before: True
  energy_embed_dropout: 0.0
  energy_embed_kernel_size: 1
  energy_predictor_chans: 256
  energy_predictor_dropout: 0.5
  energy_predictor_kernel_size: 3
  energy_predictor_layers: 2
  eunits: 1536
  init_dec_alpha: 1.0
  init_enc_alpha: 1.0
  init_type: xavier_uniform
  pitch_embed_dropout: 0.0
  pitch_embed_kernel_size: 1
  pitch_predictor_chans: 256
  pitch_predictor_dropout: 0.5
  pitch_predictor_kernel_size: 5
  pitch_predictor_layers: 5
  positionwise_conv_kernel_size: 3
  positionwise_layer_type: conv1d
  postnet_chans: 256
  postnet_filts: 5
  postnet_layers: 5
  reduction_factor: 1
  stop_gradient_from_energy_predictor: False
  stop_gradient_from_pitch_predictor: True
  transformer_dec_attn_dropout_rate: 0.2
  transformer_dec_dropout_rate: 0.2
  transformer_dec_positional_dropout_rate: 0.2
  transformer_enc_attn_dropout_rate: 0.2
  transformer_enc_dropout_rate: 0.2
  transformer_enc_positional_dropout_rate: 0.2
  use_scaled_pos_enc: True
n_fft: 2048
n_mels: 80
n_shift: 300
num_snapshots: 5
num_workers: 4
optimizer:
  learning_rate: 0.001
  optim: adam
seed: 10086
updater:
  use_masking: True
win_length: 1200
window: hann
allow_cache: True
batch_max_steps: 25500
batch_size: 6
discriminator_grad_norm: 1
discriminator_optimizer_params:
  epsilon: 1e-06
  weight_decay: 0.0
discriminator_params:
  bias: True
  conv_channels: 64
  in_channels: 1
  kernel_size: 3
  layers: 10
  nonlinear_activation: LeakyReLU
  nonlinear_activation_params:
    negative_slope: 0.2
  out_channels: 1
  use_weight_norm: True
discriminator_scheduler_params:
  gamma: 0.5
  learning_rate: 5e-05
  step_size: 200000
discriminator_train_start_steps: 100000
eval_interval_steps: 1000
fmax: 7600
fmin: 80
fs: 24000
generator_grad_norm: 10
generator_optimizer_params:
  epsilon: 1e-06
  weight_decay: 0.0
generator_params:
  aux_channels: 80
  aux_context_window: 2
  bias: True
  dropout: 0.0
  freq_axis_kernel_size: 1
  gate_channels: 128
  in_channels: 1
  interpolate_mode: nearest
  kernel_size: 3
  layers: 30
  nonlinear_activation: None
  nonlinear_activation_params:
    
  out_channels: 1
  residual_channels: 64
  skip_channels: 64
  stacks: 3
  upsample_scales: [4, 5, 3, 5]
  use_causal_conv: False
  use_weight_norm: True
generator_scheduler_params:
  gamma: 0.5
  learning_rate: 0.0001
  step_size: 200000
lambda_adv: 4.0
n_fft: 2048
n_mels: 80
n_shift: 300
num_save_intermediate_results: 4
num_snapshots: 10
num_workers: 4
pin_memory: True
remove_short_samples: True
save_interval_steps: 5000
seed: 42
stft_loss_params:
  fft_sizes: [1024, 2048, 512]
  hop_sizes: [120, 240, 50]
  win_lengths: [600, 1200, 240]
  window: hann
top_db: 60
train_max_steps: 400000
trim_frame_length: 2048
trim_hop_length: 512
trim_silence: False
win_length: 1200
window: hann
frontend done!
vocab_size: 268
W0409 16:39:01.139977 31890 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0409 16:39:01.145202 31890 device_context.cc:465] device: 0, cuDNN Version: 7.6.
encoder_type is transformer
decoder_type is transformer
/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/framework/io.py:415: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(obj, collections.Iterable) and not isinstance(obj, (
acoustic model done!
voc done!
/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/framework.py:2253: UserWarning: The Attr(force_cpu) of Op(fill_constant) will be deprecated in the future, please use 'device_guard' instead. 'device_guard' has higher priority when they are used at the same time.
  "used at the same time." % type)
/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
Building prefix dict from the default dictionary ...
[2022-04-09 16:39:17] [DEBUG] [__init__.py:113] Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
[2022-04-09 16:39:17] [DEBUG] [__init__.py:133] Loading model from cache /tmp/jieba.cache
Loading model cost 0.653 seconds.
[2022-04-09 16:39:18] [DEBUG] [__init__.py:165] Loading model cost 0.653 seconds.
Prefix dict has been built successfully.
[2022-04-09 16:39:18] [DEBUG] [__init__.py:166] Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/da2/SWHL/_exp/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 250, in <module>
    main()
  File "/da2/SWHL/_exp/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 246, in main
    evaluate(args)
  File "/da2/SWHL/_exp/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 106, in evaluate
    mel = am_inference(part_phone_ids)
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 1279, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 829, in _run_dygraph
    'program_id': _hash_with_id(trace_program)
  File "/da2/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_impl.h:51)
  [operator < reshape2 > error]  [operator < run_program > error]
```

**Comment by yt605155624** [comment]
请安装最新的 develop 版本的 paddle 再试试

**Comment by jerryuhoo** [comment]
我也遇到了同样的问题，动转静的时候会报这个错。安装最新版paddle现在可以了
```
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://[www.paddlepaddle.org.cn/whl/linux/gpu/develop.html](http://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html)
```
