### ISSUE TITLE
尝试voice clone 示例时失败PaddleSpeech/examples/aishell3/vc1/

### ISSUE THREAD

**Issue by QiFuChina** [PaddlePaddle/PaddleSpeech#1708]
如标题，设备环境
操作系统Ubuntu20.04
显卡3070ti，nvidia-smi显示cuda version
nvcc -V 显示
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
首先是第一个**_怀疑_**的点，在termianl下进入`/usr/local `文件夹，发现存在两个cuda文件夹
`cuda   cuda-11.1`
仅安装过一次cuda-11.1并复制cudnn文件进相应的文件夹。但是在bashrc添加cuda-11.1的路径之后输入官方文档的import paddle等语句测试，发现无法检测到paddlepaddle。把路径改为cuda并复制相应的cudnn文件后，再次检测成功，paddlespeech可正常执行命令行语句
按照文档下载aishell-3并保存于`datasets/data_aishell3` ，`vc1/aishell3_alignment_tone` ，`vc1/ge2e_ckpt_0.3` 后，执行`./run.sh --stage 0 --stop-stage 0`，首先出现下列信息_**多次提示nltk_data无法下载**_(已经按照文档下载解压保存在`/home`文件夹下)
Loaded encoder ge2e_ckpt_0.3/step-3000000
0 utterances in total
0utterance [00:00, ?utterance/s]
Generate durations.txt from MFA results ...
Extract features ...
·················································
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/preprocess.py", line 370, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/preprocess.py", line 235, in main
    assert rootdir.is_dir()
AssertionError

以及`dump` 文件夹下没有完整生成子文件夹

Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/utils/compute_statistics.py", line 109, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/utils/compute_statistics.py", line 84, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'

/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/utils/compute_statistics.py", line 109, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/utils/compute_statistics.py", line 84, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'
/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,

/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/utils/compute_statistics.py", line 109, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/utils/compute_statistics.py", line 84, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'
Normalize ...

Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/normalize.py", line 184, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/normalize.py", line 92, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'

Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/normalize.py", line 184, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/normalize.py", line 92, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/dev/raw/metadata.jsonl

接着执行`CUDA_VISIBLE_DEVICES=0 ./local/preprocess.sh 、./conf ./ge2e_ckpt_0.3`时，出现如下信息
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/normalize.py", line 184, in <module>
    main()
  File "/home/xht/SourceCode/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/normalize.py", line 92, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/xht/.conda/envs/paddlespeech/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 623, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/test/raw/metadata.jsonl'

**Comment by yt605155624** [comment]
主要的问题是这里
```
assert rootdir.is_dir()
```
也就是此处传入的 rootdir 不对 https://github.com/PaddlePaddle/PaddleSpeech/blob/cf1a395e150b970c6ea2b60bd4162a68911adbee/examples/aishell3/vc1/local/preprocess.sh#L32

data_aishell3 应该保存在 ```~/datasets/data_aishell3```
