### ISSUE TITLE
engine pool cannot initialize

### ISSUE THREAD

**Issue by vpegasus** [PaddlePaddle/PaddleSpeech#1847]
env: ubuntu20.04, python3.8

command:
```
paddlespeech_server start --config_file ./conf/tts_online_application.yaml
```

```
/home/xxx/xxx/lib/python3.8/site-packages/sklearn/utils/multiclass.py:14: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
/home/xxx/xxx/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/home/xxx/xxx/lib/python3.8/site-packages/sklearn/utils/optimize.py:18: DeprecationWarning: Please use `line_search_wolfe2` from the `scipy.optimize` namespace, the `scipy.optimize.linesearch` namespace is deprecated.
  from scipy.optimize.linesearch import line_search_wolfe2, line_search_wolfe1
/home/xxx/xxx/lib/python3.8/site-packages/sklearn/utils/optimize.py:18: DeprecationWarning: Please use `line_search_wolfe1` from the `scipy.optimize` namespace, the `scipy.optimize.linesearch` namespace is deprecated.
  from scipy.optimize.linesearch import line_search_wolfe2, line_search_wolfe1
Traceback (most recent call last):
  File "/home/xxx/xxx/bin/paddlespeech_server", line 8, in <module>
    sys.exit(server_execute())
  File "/home/xxx/xxx/lib/python3.8/site-packages/paddlespeech/server/entry.py", line 36, in server_execute
    status = 0 if com['_entry']().execute(sys.argv[idx:]) else 1
  File "/home/xxx/xxx/lib/python3.8/site-packages/paddlespeech/server/bin/paddlespeech_server.py", line 78, in execute
    if self.init(config):
  File "/home/xxx/xxx/lib/python3.8/site-packages/paddlespeech/server/bin/paddlespeech_server.py", line 69, in init
    if not init_engine_pool(config):
  File "/home/xxx/xxx/lib/python3.8/site-packages/paddlespeech/server/engine/engine_pool.py", line 37, in init_engine_pool
    if not ENGINE_POOL[engine].init(config=config[engine_and_type]):
AttributeError: 'NoneType' object has no attribute 'init'

```

who can help me about this error?

**Comment by lym0302** [comment]
Is it the latest code?

**Comment by vpegasus** [comment]
> Is it the latest code?

Yes, I just piped install this morning. and the source code I also downloaded this morning ( in terms of ./conf/tts_online_application.yaml ).

**Comment by yt605155624** [comment]
please 
1. pip install paddlespeech==1.0.0a
2. or git clone PaddleSpeech & pip install .

to install the latest version of paddlespeech
