### ISSUE TITLE
raise ValueError('all input arrays must have the same shape') ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by wuxiaolianggit** [PaddlePaddle/PaddleSpeech#2008]
大佬，您好，我按照语音分类的方法制作数据集，但是训练的时候一致报错，
raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
请问大佬，怎么解决呢？

**Comment by zh794390558** [comment]
确认习样本的shape是否相同。

可以给出报错的link便于定位问题，谢谢。

**Comment by wuxiaolianggit** [comment]
输入都是3s的音频啊，应该是相同的

**Comment by wuxiaolianggit** [comment]
Epoch=1/10, Step=1/224 loss=2.0149 acc=0.3750 lr=0.000001
Epoch=1/10, Step=2/224 loss=2.6289 acc=0.1250 lr=0.000001
Epoch=1/10, Step=3/224 loss=2.7558 acc=0.5000 lr=0.000001
Epoch=1/10, Step=4/224 loss=0.8492 acc=0.4375 lr=0.000001
Epoch=1/10, Step=5/224 loss=0.9390 acc=0.3125 lr=0.000001
Epoch=1/10, Step=6/224 loss=1.6636 acc=0.1875 lr=0.000001
Epoch=1/10, Step=7/224 loss=0.6243 acc=0.6875 lr=0.000001
Epoch=1/10, Step=8/224 loss=0.9829 acc=0.4375 lr=0.000001
Epoch=1/10, Step=9/224 loss=0.8008 acc=0.5000 lr=0.000001
Epoch=1/10, Step=10/224 loss=0.6795 acc=0.6250 lr=0.000001
Epoch=1/10, Step=11/224 loss=0.6959 acc=0.4375 lr=0.000001
Epoch=1/10, Step=12/224 loss=1.0572 acc=0.4375 lr=0.000001
Epoch=1/10, Step=13/224 loss=0.6562 acc=0.6875 lr=0.000001
Epoch=1/10, Step=14/224 loss=1.8922 acc=0.4375 lr=0.000001
Epoch=1/10, Step=15/224 loss=0.7169 acc=0.6250 lr=0.000001
Epoch=1/10, Step=16/224 loss=4.6308 acc=0.1875 lr=0.000001
Epoch=1/10, Step=17/224 loss=0.9289 acc=0.1875 lr=0.000001
Epoch=1/10, Step=18/224 loss=0.8225 acc=0.3125 lr=0.000001
Epoch=1/10, Step=19/224 loss=1.6492 acc=0.3125 lr=0.000001
Epoch=1/10, Step=20/224 loss=0.7137 acc=0.5625 lr=0.000001
Epoch=1/10, Step=21/224 loss=0.7275 acc=0.4375 lr=0.000001
Epoch=1/10, Step=22/224 loss=1.5566 acc=0.3750 lr=0.000001
Epoch=1/10, Step=23/224 loss=1.1431 acc=0.4375 lr=0.000001
Epoch=1/10, Step=24/224 loss=2.1380 acc=0.3125 lr=0.000001
Epoch=1/10, Step=25/224 loss=0.7066 acc=0.5000 lr=0.000001
Epoch=1/10, Step=26/224 loss=0.7562 acc=0.5625 lr=0.000001
Epoch=1/10, Step=27/224 loss=1.0719 acc=0.3750 lr=0.000001
Epoch=1/10, Step=28/224 loss=0.8189 acc=0.3750 lr=0.000001
Epoch=1/10, Step=29/224 loss=0.6922 acc=0.4375 lr=0.000001
Epoch=1/10, Step=30/224 loss=1.1085 acc=0.2500 lr=0.000001
Epoch=1/10, Step=31/224 loss=2.5135 acc=0.3125 lr=0.000001
Epoch=1/10, Step=32/224 loss=0.7399 acc=0.4375 lr=0.000001
Epoch=1/10, Step=33/224 loss=1.2367 acc=0.2500 lr=0.000001
Epoch=1/10, Step=34/224 loss=0.7742 acc=0.4375 lr=0.000001
Epoch=1/10, Step=35/224 loss=0.9008 acc=0.1875 lr=0.000001
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wxl/develop/python/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/wxl/develop/python/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 212, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 78, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 78, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "/home/wxl/develop/python/lib/python3.9/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
@zh794390558 大佬，您看一下，这是什么问题，怎么解决呢？

**Comment by zh794390558** [comment]
```
batch = np.stack(batch, axis=0)
```
应该是这里出错的，把 batch 都打出来看看。

**Comment by wuxiaolianggit** [comment]
Epoch=1/10, Step=34/224 loss=0.8708 acc=0.1875 lr=0.000001
batch[ 0 ] shape is  (48480,)
batch[ 1 ] shape is  (48480,)
batch[ 2 ] shape is  (48480,)
batch[ 3 ] shape is  (48480,)
batch[ 4 ] shape is  (48480,)
batch[ 5 ] shape is  (48480,)
batch[ 6 ] shape is  (48480,)
batch[ 7 ] shape is  (48480,)
batch[ 8 ] shape is  (48480,)
batch[ 9 ] shape is  (48480,)
batch[ 10 ] shape is  (48480,)
batch[ 11 ] shape is  (48480,)
batch[ 12 ] shape is  (48480,)
batch[ 13 ] shape is  (48480,)
batch[ 14 ] shape is  (48480,)
batch[ 15 ] shape is  (48480,)
batch[ 0 ] shape is  ()
batch[ 1 ] shape is  ()
batch[ 2 ] shape is  ()
batch[ 3 ] shape is  ()
batch[ 4 ] shape is  ()
batch[ 5 ] shape is  ()
batch[ 6 ] shape is  ()
batch[ 7 ] shape is  ()
batch[ 8 ] shape is  ()
batch[ 9 ] shape is  ()
batch[ 10 ] shape is  ()
batch[ 11 ] shape is  ()
batch[ 12 ] shape is  ()
batch[ 13 ] shape is  ()
batch[ 14 ] shape is  ()
batch[ 15 ] shape is  ()
Epoch=1/10, Step=35/224 loss=1.2811 acc=0.0625 lr=0.000001
batch[ 0 ] shape is  (48480,)
batch[ 1 ] shape is  (48480,)
batch[ 2 ] shape is  (48480,)
batch[ 3 ] shape is  (48480,)
batch[ 4 ] shape is  (48480,)
batch[ 5 ] shape is  (48480,)
batch[ 6 ] shape is  (48480,)
batch[ 7 ] shape is  (48480,)
batch[ 8 ] shape is  (48480,)
batch[ 9 ] shape is  (16800,)
batch[ 10 ] shape is  (48480,)
batch[ 11 ] shape is  (48480,)
batch[ 12 ] shape is  (48480,)
batch[ 13 ] shape is  (48480,)
batch[ 14 ] shape is  (48480,)
batch[ 15 ] shape is  (48480,)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wxl/develop/python/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/wxl/develop/python/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 212, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 80, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 80, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/home/wxl/develop/python/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 60, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "/home/wxl/develop/python/lib/python3.9/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

@zh794390558 大佬，确实在35个iter的时候shape有问题，该怎么解决呢？大概是哪方面的问题的呢？

**Comment by zh794390558** [comment]
用dataloader过数据，然后debug吧。可以用 pdb

**Comment by wuxiaolianggit** [comment]
多谢大佬的回复和解答，我尝试利用pdb调试一下，之前没怎么用过，我看一下是数据的原因，还是paddle框架的原因啊，等找到了，我反馈给大佬啊。 @zh794390558

**Comment by wuxiaolianggit** [comment]
@zh794390558 大佬，您好，我找出原因了，是由于我的数据集里面有部分数据不是3s，有的是3.03s，有的时3.02s，大佬，有办法做语音数据对齐吗？

**Comment by zh794390558** [comment]
load语音可以指定start, end吧

**Comment by wuxiaolianggit** [comment]
好的，大佬。我自己写了一个对齐，搞了半天，终于训练起来了。

**Comment by wuxiaolianggit** [comment]
@zh794390558  大佬，您好，panns 语音分类网络可以转成onnx模型吗，我转模型一直报错呢？

**Comment by zh794390558** [comment]
没有试过，有问题可以在Paddle2ONNX提issue问问。

**Comment by suzhou-Second** [comment]
> 好的，大佬。我自己写了一个对齐，搞了半天，终于训练起来了。

你好，麻烦问下你这个是在paddle.io.DataLoader 这个之前补的吗？
