### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by litterGuy** [PaddlePaddle/PaddleSpeech#2029]
使用 examples/aishell/asr0进行普通话训练的例子，出现了如标题的错误。
执行
```
bash run.sh
```
然后报了以下错误
```
2022-06-10 15:35:20.062 | INFO     | paddlespeech.s2t.utils.utility:all_version:45 - Deps Module Version:[('python', '3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]'),
 ('paddle', '2.3.0'),
 ('paddle_commit', '590b4dbcdd989324089ce43c22ef151c746c92a3'),
 ('soundfile', '0.10.3')]
2022-06-10 15:35:20.063 | INFO     | paddlespeech.s2t.training.trainer:__init__:112 - Rank: 0/4
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:35953', '127.0.0.1:51237', '127.0.0.1:58673']
INFO 2022-06-10 15:35:21,402 launch_utils.py:322] terminate process group gid:51514
INFO 2022-06-10 15:35:21,402 launch_utils.py:322] terminate process group gid:51514
INFO 2022-06-10 15:35:25,405 launch_utils.py:343] terminate all the procs
INFO 2022-06-10 15:35:25,405 launch_utils.py:343] terminate all the procs
ERROR 2022-06-10 15:35:25,405 launch_utils.py:642] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
ERROR 2022-06-10 15:35:25,405 launch_utils.py:642] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.
INFO 2022-06-10 15:35:29,409 launch_utils.py:343] terminate all the procs
INFO 2022-06-10 15:35:29,409 launch_utils.py:343] terminate all the procs
INFO 2022-06-10 15:35:29,409 launch.py:402] Local processes completed.
INFO 2022-06-10 15:35:29,409 launch.py:402] Local processes completed.
Namespace(ckpt_dir='exp/deepspeech2/checkpoints', dst_model='exp/deepspeech2/checkpoints/avg_1.pdparams', max_epoch=65536, min_epoch=0, num=1, val_best=True)
Traceback (most recent call last):
  File "/home/xsy/works/PaddleSpeech/utils/avg_model.py", line 116, in <module>
    main(args)
  File "/home/xsy/works/PaddleSpeech/utils/avg_model.py", line 43, in main
    sort_idx = np.argsort(val_scores[:, 1])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
Failed in avg ckpt!
```

这个问题是因为什么，该如何修复呢？希望大佬提供下帮助

**Comment by Jackwaterveg** [comment]
请问是否已经训好了模型，比如 exp/模型名/checkpoints 中是否有 数字.pdparams, 数字.pdoopt( 比如  1.pdparms 1.pdopt)

**Comment by litterGuy** [comment]
没有产生模型文件，exp下只有log文件夹

**Comment by litterGuy** [comment]
怪自己阅读文档不细了。。。。
/examples/aishell/asr0/run.sh文件的
```
gpus=0,1,2,3
```
参数一定要修改，根据自己机器的配置调整。
因自己机器只有gpu0，然后就报了以上错误、
