### ISSUE TITLE
Out of memory error on GPU 

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2033]
你好。我想问一个问题。我再训练fastspeech2的时候，config文件都没有变动，batch=64，但是会报错“Out of memory error on GPU 0”。
**GPU: v100，32G**
无论我的batch改成32还是16，同样会报“Out of memory ”这个错误，用多张卡训练也是一样的情况：
```
Exception in main training loop: (Fatal) Operator where raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 1.083714GB memory on GPU 0, 30.711914GB memory has been allocated and available memory is only 1.036621GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.60 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 (at /paddle/paddle/fluid/memory/detail/system_allocator.cc:155)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

Traceback (most recent call last):
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 109, in update
    self.update_core(batch)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/models/fastspeech2/fastspeech2_updater.py", line 83, in update_core
    spk_emb=spk_emb)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 557, in forward
    tone_id=tone_id)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 656, in _forward
    zs, _ = self.decoder(hs, h_masks)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/encoder.py", line 415, in forward
    xs, masks = self.encoders(xs, masks)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/repeat.py", line 25, in forward
    args = m(*args)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/encoder_layer.py", line 101, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/attention.py", line 155, in forward
    return self.forward_attention(v, scores, mask)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/attention.py", line 115, in forward_attention
    scores = masked_fill(scores, mask, min_value)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/masked_fill.py", line 48, in masked_fill
    xs = paddle.where(mask, trues, xs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/tensor/search.py", line 522, in where
    return _C_ops.where(condition, x, y)
Trainer extensions will try to handle the extension. Then all extensions will finalize.Traceback (most recent call last):
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/exps/fastspeech2/train.py", line 214, in <module>
    main()
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/exps/fastspeech2/train.py", line 210, in main
    train_sp(args, config)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/exps/fastspeech2/train.py", line 167, in train_sp
    trainer.run()
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/training/trainer.py", line 198, in run
    six.reraise(*exc_info)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 109, in update
    self.update_core(batch)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/models/fastspeech2/fastspeech2_updater.py", line 83, in update_core
    spk_emb=spk_emb)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 557, in forward
    tone_id=tone_id)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 656, in _forward
    zs, _ = self.decoder(hs, h_masks)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/encoder.py", line 415, in forward
    xs, masks = self.encoders(xs, masks)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/repeat.py", line 25, in forward
    args = m(*args)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/encoder_layer.py", line 101, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/attention.py", line 155, in forward
    return self.forward_attention(v, scores, mask)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/transformer/attention.py", line 115, in forward_attention
    scores = masked_fill(scores, mask, min_value)
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/0_Paddlespeech/paddlespeech/t2s/modules/masked_fill.py", line 48, in masked_fill
    xs = paddle.where(mask, trues, xs)
  File "/root/anaconda3/envs/paddlespeech/lib/python3.7/site-packages/paddle/tensor/search.py", line 522, in where
    return _C_ops.where(condition, x, y)
SystemError: (Fatal) Operator where raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 1.083714GB memory on GPU 0, 30.711914GB memory has been allocated and available memory is only 1.036621GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.60 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 (at /paddle/paddle/fluid/memory/detail/system_allocator.cc:155)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)
```

我更换成其他训练数据，batch=64都没有问题。请问这是什么原因。训练数据是magicdata，

**Comment by yt605155624** [comment]
请检查是否是第一个数据集的每条音频的长度过长，目前的配置是在 csmsc 数据集上的配置，可以参照 csmsc 每条音频的长度裁剪音频
