### ISSUE TITLE
数据类型有错误哦

### ISSUE THREAD

**Issue by Doubledongli** [PaddlePaddle/PaddleSpeech#2114]
2022-07-05 11:07:06.922 | INFO     | paddlespeech.s2t.training.trainer:do_train:271 - Train Total Examples: 6245
Traceback (most recent call last):
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\training\trainer.py", line 342, in run
    self.do_train()
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\training\trainer.py", line 307, in do_train
    raise e
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\training\trainer.py", line 286, in do_train
    self.train_batch(batch_index, batch, msg)
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\exps\deepspeech2\model.py", line 55, in train_batch
    loss = self.model(audio, audio_len, text, text_len)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\models\ds2\deepspeech2.py", line 292, in forward
    loss = self.decoder(eouts, eouts_len, text, text_len)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
2022-07-05 11:07:18.467 | ERROR    | paddlespeech.s2t.training.trainer:do_train:306 - (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container. (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:148)
  [operator < warpctc > error]
2022-07-05 11:07:18.468 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Epoch-Train Time Cost: 0:00:11.545535
2022-07-05 11:07:18.468 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Training Done: 0:00:12.690650
    outputs = self.forward(*inputs, **kwargs)
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\modules\ctc.py", line 95, in forward
    loss = self.criterion(logits, ys_pad, hlens, ys_lens)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\develop\workspace\PaddleSpeech\paddlespeech\s2t\modules\loss.py", line 93, in forward
    loss = self.loss(logits, ys_pad, hlens, ys_lens, **self._kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\nn\layer\loss.py", line 1130, in forward
    norm_by_times=norm_by_times)
  File "D:\conda\envs\asr\lib\site-packages\paddle\nn\functional\loss.py", line 1126, in ctc_loss
    input_lengths, label_lengths)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\layers\loss.py", line 613, in warpctc
    norm_by_times, )
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container. (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:148)
  [operator < warpctc > error]

![image](https://user-images.githubusercontent.com/20540661/177243521-a50b2802-b641-45a2-8399-1e9b5587c7c4.png)
![image](https://user-images.githubusercontent.com/20540661/177243544-586de79a-80ea-48b8-9299-2c6942da0430.png)
这个错误，起先是数据类型错误，后来我自己转了下类型还是错误，我的操作系统是下面的配置。
![image](https://user-images.githubusercontent.com/20540661/177243641-9fadf039-74e2-453a-978d-f6c9042e18e6.png)
![image](https://user-images.githubusercontent.com/20540661/177243788-deec1ee1-91e9-4507-886c-f4398f6d1fd1.png)

**Comment by zh794390558** [comment]
看log是数据类型错误，麻烦打印下输入的数据类型并查看paddle api 文档，看下是否一致。

**Comment by Doubledongli** [comment]
> 打印下输入的数据类型并查看paddle api 文档，看下是否一致

数据类型默认是int32，并且完全一样的代码，我在ubuntu上面运行是正常的，win10上就报错，并且我通过paddle.to_tensor转为int64以后，仍旧会报其他的错误，错误类型如下：
`  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\conda\envs\asr\lib\site-packages\paddle\nn\layer\loss.py", line 1130, in forward
    norm_by_times=norm_by_times)
  File "D:\conda\envs\asr\lib\site-packages\paddle\nn\functional\loss.py", line 1126, in ctc_loss
    input_lengths, label_lengths)
  File "D:\conda\envs\asr\lib\site-packages\paddle\fluid\layers\loss.py", line 613, in warpctc
    norm_by_times, )
RuntimeError: (NotFound) There are no kernels which are registered in the warpctc operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at C:\home\workspace\Paddle_release\paddle\fluid\imperative\prepared_operator.cc:327)
  [operator < warpctc > error]`

个人怀疑，这是一个系统底层数据转换的bug。
![1657069924294](https://user-images.githubusercontent.com/20540661/177442737-ff1ecb4f-dcf7-4295-af4c-b60bbaa04fef.jpg)

**Comment by zh794390558** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/3038472/178237461-45169fc8-bdf1-4cea-a8fe-ac307bc78144.png">

确定是和这个api类型一致？确定的话有可能是win上的bug了。可以在paddle那边儿问问看。

**Comment by Doubledongli** [comment]
> 话有可能是win上的bug了。可以在paddle那边儿问问看。

已经找到原因了，windows无法安装pip的ppspeech的ctc_decoders，这个只有mac和linux版本，所以导致底层调用失败，啥时候paddle那边能出windows版本啊，自己想编译一直出问题

**Comment by yt605155624** [comment]
[自行编译paddlespeech-ctcdecoders的windows版本](https://github.com/PaddlePaddle/PaddleSpeech/discussions)
