### ISSUE TITLE
wenetspeech streaming ASR failed

### ISSUE THREAD

**Issue by JaheimLee** [PaddlePaddle/PaddleSpeech#2218]
When upgrade paddlespeech to the latest develop version, there are shape mismatch errors in logs. But the older version works well.
```
[2022-08-02 20:46:34,856] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2022-08-02 20:46:34,856] [    INFO] - start to do model forward
[2022-08-02 20:46:34,860] [   ERROR] - (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 16, 512, 19], X's size = 155648, 'shape' is [1, 16, 0], the capacity of 'shape' is 8192.
  [Hint: Expected capacity == in_size, but received capacity:8192 != in_size:155648.] (at /paddle/paddle/fluid/operators/reshape_op.cc:204)
  [operator < reshape2 > error]
Traceback (most recent call last):
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 477, in advance_decoding
    (y, self.att_cache, self.cnn_cache) = self.model.encoder.forward_chunk(
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddlespeech/s2t/modules/encoder.py", line 230, in forward_chunk
    xs, pos_emb, _ = self.embed(xs, tmp_masks, offset=offset)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddlespeech/s2t/modules/subsampling.py", line 143, in forward
    x = self.out(x.transpose([0, 2, 1, 3]).reshape([b, t, c * f]))
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddle/tensor/manipulation.py", line 2139, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddle/fluid/layers/nn.py", line 6373, in reshape
    out, _ = _C_ops.reshape2(x, None, 'shape', shape)
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 16, 512, 19], X's size = 155648, 'shape' is [1, 16, 0], the capacity of 'shape' is 8192.
  [Hint: Expected capacity == in_size, but received capacity:8192 != in_size:155648.] (at /paddle/paddle/fluid/operators/reshape_op.cc:204)
  [operator < reshape2 > error]
```

**Comment by zh794390558** [comment]
> The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 16, 512, 19], X's size = 155648, 'shape' is [1, 16, 0],

> File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddlespeech/s2t/modules/subsampling.py", line 143, in forward
> x = self.out(x.transpose([0, 2, 1, 3]).reshape([b, t, c * f]))

I think maybe the model input data is not good, please check whether it is. Some hints  as above.

**Comment by JaheimLee** [comment]
> > The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 16, 512, 19], X's size = 155648, 'shape' is [1, 16, 0],
> 
> > File "/data/miniconda3/envs/ljh_paddle/lib/python3.9/site-packages/paddlespeech/s2t/modules/subsampling.py", line 143, in forward
> > x = self.out(x.transpose([0, 2, 1, 3]).reshape([b, t, c * f]))
> 
> I think maybe the model input data is not good, please check whether it is. Some hints as above.

I don't think so. Because it did work before. Here is my audio. Because github can't upload .wav file, here I change .wav to .mp4

https://user-images.githubusercontent.com/18062264/182752760-9fffe885-3a66-4d02-b192-68e22c740017.mp4

**Comment by yt605155624** [comment]
@JaheimLee hi, I pull the latest develop PaddleSpeech (commit id: 2f9bdf2306d15f32677dcbf87009c45750312373), wget your audio and rename it  to `test.wav`, 
run the following cmd:
```bash
paddlespeech_server start --config_file ./conf/ws_conformer_wenetspeech_application.yaml
paddlespeech_client asr_online --server_ip {your ip} --port 8090 --input ./test.wav
```
this is my client log

```text
[2022-08-05 07:32:17,744] [    INFO] - client receive msg={"status": "ok", "signal": "server_ready"}
[2022-08-05 07:32:17,860] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,871] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,881] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,891] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,900] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,909] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,918] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:17,926] [    INFO] - client receive msg={'result': ''}
[2022-08-05 07:32:18,364] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,374] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,381] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,389] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,396] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,404] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,412] [    INFO] - client receive msg={'result': '抖'}
[2022-08-05 07:32:18,811] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,820] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,827] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,835] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,842] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,850] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,858] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:18,865] [    INFO] - client receive msg={'result': '抖音走了一个老'}
[2022-08-05 07:32:19,315] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,324] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,331] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,339] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,346] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,354] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,362] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了'}
[2022-08-05 07:32:19,738] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,747] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,755] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,762] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,770] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,777] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,785] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:19,793] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗'}
[2022-08-05 07:32:20,167] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,175] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,183] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,190] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,198] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,205] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,213] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的'}
[2022-08-05 07:32:20,592] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,600] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,607] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,615] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,623] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,630] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,638] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:20,646] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板'}
[2022-08-05 07:32:21,031] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,039] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,047] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,054] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,062] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,069] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,077] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我'}
[2022-08-05 07:32:21,472] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,480] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,488] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,496] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,503] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,511] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,518] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,526] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼'}
[2022-08-05 07:32:21,926] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:21,934] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:21,942] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:21,950] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:21,958] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:21,965] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:21,973] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有'}
[2022-08-05 07:32:22,378] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,387] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,395] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,402] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,410] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,418] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,425] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,433] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色'}
[2022-08-05 07:32:22,843] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:22,852] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:22,859] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:22,867] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:22,874] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:22,882] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:22,889] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天'}
[2022-08-05 07:32:23,306] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,314] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,321] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,328] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,336] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,343] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,350] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,358] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同'}
[2022-08-05 07:32:23,782] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:23,790] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:23,797] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:23,803] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:23,810] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:23,817] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:23,824] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东'}
[2022-08-05 07:32:24,258] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,267] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,274] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,282] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,290] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,297] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,305] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,313] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直'}
[2022-08-05 07:32:24,752] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直播间累双将'}
[2022-08-05 07:32:24,761] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直播间累双将'}
[2022-08-05 07:32:24,769] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直播间累双将'}
[2022-08-05 07:32:24,776] [    INFO] - client receive msg={'result': '抖音走了一个老罗又来了一个老罗去电的罗老板前天在送我桑菜鱼搞得有酸有色昨天作为同行跑到东雨辉的直播间累双将'}

```
Maybe you can try again

python & paddle (I use an old develop version of paddle) 
```text
Python 3.7.0 (default, Nov 13 2020, 03:24:08)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.__version__
'0.0.0'
>>> print(paddle.version.commit)
99b3727d5bd37ae18ef63407dc4bd6ab75fb76fc
```
