### ISSUE TITLE
ValueError: `paddle.load` can not parse the file:/Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/exp/conformer/checkpoints/wenetspeech.pdparams.

### ISSUE THREAD

**Issue by gubaoya123456** [PaddlePaddle/PaddleSpeech#2231]
我执行程序 main.py 报错

**执行环境：**

> python 3.8.9
> paddlepaddle 2.3.1
> paddlespeech 1.0.1

**执行代码：**

```
from paddlespeech.cli.asr.infer import ASRExecutor
asr = ASRExecutor()
result = asr(audio_file="zh.wav")
print(result)
```
**报错：**

/Users/petergu/workspace/python/paddle/venv/bin/python /Users/petergu/workspace/python/paddle/main.py
[2022-08-08 15:04:14,091] [    INFO] - checking the audio file format......
[2022-08-08 15:04:14,104] [    INFO] - The sample rate is 16000
[2022-08-08 15:04:14,104] [    INFO] - The audio file format is right
[2022-08-08 15:04:14,104] [    INFO] - start to init the model
[2022-08-08 15:04:14,104] [    INFO] - File /Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz md5 checking...
[2022-08-08 15:04:18,679] [    INFO] - Use pretrained model stored in: /Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar
[2022-08-08 15:04:18,679] [    INFO] - /Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar
[2022-08-08 15:04:18,679] [    INFO] - /Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/model.yaml
[2022-08-08 15:04:18,679] [    INFO] - /Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/exp/conformer/checkpoints/wenetspeech.pdparams
Traceback (most recent call last):
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 952, in load
    load_result = _pickle_loads_mac(path, f)
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/fluid/io.py", line 1950, in _pickle_loads_mac
    load_result = pickle.loads(pickle_bytes, encoding='latin1')
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 980, in load
    tensor, _ = _load_selected_rows(path)
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 541, in _load_selected_rows
    _seek = core.load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:680854656 != 0U:0.] (at /home/Paddle/paddle/fluid/framework/selected_rows_utils.cc:68)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 984, in load
    tensor, _ = _load_lod_tensor(path)
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 502, in _load_lod_tensor
    _seek = paddle.fluid.core.load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 680854656 found).
  [Hint: Expected version == 0U, but received version:680854656 != 0U:0.] (at /home/Paddle/paddle/fluid/framework/lod_tensor.cc:276)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 995, in load
    program = Program.parse_from_string(
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/fluid/framework.py", line 5762, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /home/Paddle/paddle/fluid/framework/program_desc.cc:103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petergu/workspace/python/paddle/main.py", line 3, in <module>
    result = asr(audio_file="zh.wav")
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 338, in _warpper
    return executor_func(self, *args, **kwargs)
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 454, in __call__
    self._init_from_path(model, lang, sample_rate, config, decode_method,
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 192, in _init_from_path
    model_dict = paddle.load(self.ckpt_path)
  File "/Users/petergu/workspace/python/paddle/venv/lib/python3.8/site-packages/paddle/framework/io.py", line 999, in load
    raise ValueError(
ValueError: `paddle.load` can not parse the file:/Users/petergu/.paddlespeech/models/conformer_wenetspeech-zh-16k/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/exp/conformer/checkpoints/wenetspeech.pdparams.

Process finished with exit code 1

**Comment by zh794390558** [comment]
> _pickle.UnpicklingError: pickle data was truncated

确认下ckpt是否下载正确。可以删除后重新测试使用。

**Comment by feng-1985** [comment]
这种很有可能模型文件被破坏了

**Comment by qinhuangdaoStation** [comment]
netron可以正常可视化，这算是模型正常吗？而且我在自己的Linux上面可以正常执行，在其他的平台Linux就报这个错误

**Comment by qinhuangdaoStation** [comment]
可以使用下面的方法，验证模型是否正常。如果正常，则有可能是版本的问题，paddlepaddle与paddlenlp/xxx版本不兼容，paddlenlp/xxx版本过高

`
def func_method_01(model_dir):

    paddle.enable_static()

    model_filename = os.path.join(model_dir, "inference.pdmodel")
    params_filename = os.path.join(model_dir, "inference.pdiparams")

    # 使用推断配置和模型文件创建一个 inference.Predictor 对象
    config = paddle.inference.Config(model_filename, params_filename)
    predictor = paddle.inference.create_predictor(config)

    print("predictor: \n", predictor)
    pass
`
