### ISSUE TITLE
想转换PaddleSpeech到ONNX格式，但是报错

### ISSUE THREAD

**Issue by zhijianli** [PaddlePaddle/PaddleSpeech#2258]
**问题描述**
目前想转换PaddleSpeech到ONNX格式，代码如下：
```
# 从模型代码中导入模型
import paddle

# 实例化模型
model_for_onnx = asr_engine.executor.model.encoder
# 将模型设置为推理状态
model_for_onnx.eval()

input_spec = [
    paddle.static.InputSpec(
        shape=[1, 67, 80],
        dtype='float32',
        name='xs'),
    paddle.static.InputSpec(
        shape=[0],
        dtype='int64',
        name='offset'),
    paddle.static.InputSpec(
        shape=[-16],
        dtype='int64',
        name='required_cache_size'),
    paddle.static.InputSpec(
        shape=[1, 16, 512],
        dtype='float32',
        name='subsampling_cache'),
    paddle.static.InputSpec(
        shape=[1, 16, 512],
        dtype='float32',
        name='elayers_output_cache'),
    paddle.static.InputSpec(
        shape=[1, 512, 14],
        dtype='float32',
        name='conformer_cnn_cache'),
]

# ONNX模型导出
paddle.onnx.export(model_for_onnx, 'deep_111', input_spec=input_spec, opset_version=12, enable_onnx_checker=True)

```

但是报错

**报错截图**
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 6889, in _dygraph_guard
    yield
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 868, in save
    with_hook=with_hook)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/github/PaddleSpeech/paddlespeech/s2t/modules/encoder.py", line 349, in forward
            pos_emb,
            output_cache=attn_cache,
            cnn_cache=cnn_cache)
            ~~~~~~~~~~~~~~~~~~~~ <--- HERE
        r_elayers_output_cache.append(xs[:, next_cache_start:, :])
        r_conformer_cnn_cache.append(new_cnn_cache)

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpgf4ex6_9.py", line 88, in forward
	output_cache, residual, self, x), (mask, residual, x_q))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
	out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpgf4ex6_9.py", line 77, in false_fn_10
	paddle.jit.dy2static.convert_assert(output_cache.shape[0] == x.shape[0]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 478, in convert_assert
	assert cond, message

    AssertionError


Process finished with exit code 1

```

想请教一下是什么原因？

**Comment by zh794390558** [comment]
这个转onnx吗？可以先参考https://github.com/PaddlePaddle/PaddleSpeech/pull/2212/files 这个，我们做动转静用的。转onnx应该转静态图，然后paddle2onnx吧？

**Comment by lesliexufdu** [comment]
我也有这个问题。请问你这个用的什么Paddle版本啊，我照你的文件改了后，提示装饰器错误
![image](https://user-images.githubusercontent.com/96860383/186105670-75b4a9d5-ef2a-4dba-aa7e-35a72872e730.png)

**Comment by zh794390558** [comment]
用的是develop的版本。
