### ISSUE TITLE
Text-to-Speech 提示 cannot load library libsndfile.dylib

### ISSUE THREAD

**Issue by clstech** [PaddlePaddle/PaddleSpeech#2279]
** Environment (please complete the following information):**
 - OS: Mac M1
 - Python Version 3.8
 - PaddlePaddle Version 2.3.1

克隆之后，安装失败，修改onnxruntime==1.12.1 和 conda install libsndfile 后安装成功，在使用Text-to-Speech报如下错误

`paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
`

```
Traceback (most recent call last):
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/soundfile.py", line 143, in <module>
    _snd = _ffi.dlopen(_libname)
OSError: cannot load library '/Users/chenchun/miniforge3/envs/paddle_env/bin/../lib/libsndfile.dylib': dlopen(/Users/chenchun/miniforge3/envs/paddle_env/bin/../lib/libsndfile.dylib, 0x0002): Library not loaded: '@rpath/libvorbis.0.4.9.dylib'
  Referenced from: '/Users/chenchun/miniforge3/envs/paddle_env/lib/libsndfile.1.0.31.dylib'
  Reason: tried: '/Users/chenchun/miniforge3/envs/paddle_env/lib/libvorbis.0.4.9.dylib' (no such file), '/Users/chenchun/miniforge3/envs/paddle_env/lib/libvorbis.0.4.9.dylib' (no such file), '/Users/chenchun/miniforge3/envs/paddle_env/lib/libvorbis.0.4.9.dylib' (no such file), '/Users/chenchun/miniforge3/envs/paddle_env/bin/../lib/libvorbis.0.4.9.dylib' (no such file), '/usr/local/lib/libvorbis.0.4.9.dylib' (no such file), '/usr/lib/libvorbis.0.4.9.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenchun/miniforge3/envs/paddle_env/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddlespeech/cli/base_commands.py", line 19, in <module>
    from ..resource import CommonTaskResource
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 28, in <module>
    import soundfile as sf
  File "/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/chenchun/miniforge3/envs/paddle_env/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib' (no such file)
```

**Comment by yt605155624** [comment]
相关问题可以自行百度或谷歌搜索解决，paddlespeech 不保证在 mac m1 上安转成功
