### ISSUE TITLE
zh_en_tts 推理出错

### ISSUE THREAD

**Issue by sixyang** [PaddlePaddle/PaddleSpeech#2294]
报错如下所示：
```
acoustic model done!
voc done!
Traceback (most recent call last):
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 262, in <module>
    main()
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 258, in main
    evaluate(args)
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 106, in evaluate
    frontend_dict = run_frontend(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/syn_utils.py", line 193, in run_frontend
    input_ids = frontend.get_input_ids(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/frontend/mix_frontend.py", line 253, in get_input_ids
    phones_seg.append(input_ids["phone_ids"][0])
UnboundLocalError: local variable 'input_ids' referenced before assignment
```
定位到问题如下所示：
```
242                 if lang == "zh":
243                     input_ids = self.zh_frontend.get_input_ids(
244                         content,
245                         merge_sentences=True,
246                         get_tone_ids=get_tone_ids,
247                         to_tensor=to_tensor)
248 
249                 elif lang == "en":
250                     input_ids = self.en_frontend.get_input_ids(
251                         content, merge_sentences=True, to_tensor=to_tensor)
252 
253                 phones_seg.append(input_ids["phone_ids"][0])
254                 if add_sp:
255                     phones_seg.append(self.sp_id_tensor)
```
这里应该是没有更新 lang 的 mix 选项~

**Comment by sixyang** [comment]
把 zh 的处理方式写成 else，然后又遇到这个问题，
```
voc done!
Traceback (most recent call last):
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 262, in <module>
    main()
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 258, in main
    evaluate(args)
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 106, in evaluate
    frontend_dict = run_frontend(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/exps/syn_utils.py", line 193, in run_frontend
    input_ids = frontend.get_input_ids(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/frontend/mix_frontend.py", line 253, in get_input_ids
    input_ids = self.zh_frontend.get_input_ids(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/frontend/zh_frontend.py", line 408, in get_input_ids
    phonemes = self.get_phonemes(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/frontend/zh_frontend.py", line 375, in get_phonemes
    phonemes = self._g2p(
  File "/root/autodl-tmp/PaddleSpeech-r1.1.0/paddlespeech/t2s/frontend/zh_frontend.py", line 278, in _g2p
    if merge_list[-1] == 'sp':
IndexError: list index out of range
```

**Comment by yt605155624** [comment]
请把你的输入文本列出来一下吧, 是不是分句有**纯数字**的情况，比如 `你好，12234，hello world`
此处的 lang 无需有 mix 选项，是把输入分类成中文或者英文分别过对应的前端，我们自己的文本是没有问题的 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/sentences_mix.txt, 可能是你的输入撞了什么特殊的 case，可以自己打印一下中间结果看看 `input_ids` 为什么没有值，欢迎提交 pr 修复

**Comment by sixyang** [comment]
> 请把你的输入文本列出来一下吧, 是不是分句有**纯数字**的情况，比如 `你好，12234，hello world` 此处的 lang 无需有 mix 选项，是把输入分类成中文或者英文分别过对应的前端，我们自己的文本是没有问题的 [https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/sentences_mix.txt](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/sentences_mix.txt?rgh-link-date=2022-08-24T01%3A52%3A22Z), 可能是你的输入撞了什么特殊的 case，可以自己打印一下中间结果看看 `input_ids` 为什么没有值，欢迎提交 pr 修复

今天看了一下文本，发现 sentence.txt 里面是乱码，emmm，应该是系统编码的问题。抱歉

**Comment by yt605155624** [comment]
不过也算是帮我们发现了一个问题，目前对于分句是纯数字的确实表现不好，我们会修复一下

**Comment by sixyang** [comment]
为什么在 sentence_mix.txt 第一列在代码里要取名为 utt_id，我以为是 speaker_id，但是发现修改了这个值并没有什么用。还是在一开始 config 里面修改 speaker_id 才有用~只是好奇

**Comment by yt605155624** [comment]
第一列设置为 utt_id 方便保存音频
