### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'negative_slope'

### ISSUE THREAD

**Issue by YuBYan** [PaddlePaddle/PaddleSpeech#2401]
你好，
我使用docker镜像想要运行这个Paddle Speech Demo [speech_web，依照这个readme文档](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/speech_web)
 在执行 `python main.py --port 8010` 时报错
`grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2022-09-17 02:56:35,240] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'source/model'.
---    fused 0 elementwise_add with relu activation
---    fused 0 elementwise_add with tanh activation
---    fused 0 elementwise_add with leaky_relu activation
---    fused 0 elementwise_add with swish activation
---    fused 0 elementwise_add with hardswish activation
---    fused 0 elementwise_add with sqrt activation
---    fused 0 elementwise_add with abs activation
---    fused 0 elementwise_add with clip activation
---    fused 0 elementwise_add with gelu activation
---    fused 0 elementwise_add with relu6 activation
---    fused 0 elementwise_add with sigmoid activation
---    fused 0 elementwise_sub with relu activation
---    fused 0 elementwise_sub with tanh activation
---    fused 0 elementwise_sub with leaky_relu activation
---    fused 0 elementwise_sub with swish activation
---    fused 0 elementwise_sub with hardswish activation
---    fused 0 elementwise_sub with sqrt activation
---    fused 0 elementwise_sub with abs activation
---    fused 0 elementwise_sub with clip activation
---    fused 0 elementwise_sub with gelu activation
---    fused 0 elementwise_sub with relu6 activation
---    fused 0 elementwise_sub with sigmoid activation
---    fused 0 elementwise_mul with relu activation
---    fused 0 elementwise_mul with tanh activation
---    fused 0 elementwise_mul with leaky_relu activation
---    fused 0 elementwise_mul with swish activation
---    fused 0 elementwise_mul with hardswish activation
---    fused 0 elementwise_mul with sqrt activation
---    fused 0 elementwise_mul with abs activation
---    fused 0 elementwise_mul with clip activation
---    fused 0 elementwise_mul with gelu activation
---    fused 0 elementwise_mul with relu6 activation
---    fused 0 elementwise_mul with sigmoid activation
[2022-09-17 02:56:36,889] [    INFO] - Already cached /root/.paddlenlp/models/plato-mini/plato-mini-vocab.txt[2022-09-17 02:56:36,890] [    INFO] - Already cached /root/.paddlenlp/models/plato-mini/plato-mini-spm.model[2022-09-17 02:56:36,948] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/plato-mini/tokenizer_config.json
[2022-09-17 02:56:36,949] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/plato-mini/special_tokens_map.json
Traceback (most recent call last):
  File "main.py", line 73, in <module>
2022-09-17 02:56:48.298 | INFO     | paddlespeech.s2t.modules.embedding:__init__:153 - max len: 5000
    chatbot = Robot(asr_config, tts_config, asr_init_path, ie_model_path=ie_model_path)
  File "/home/PaddleSpeech/demos/speech_web/speech_server/src/robot.py", line 15, in __init__
    self.asr = ASR(config_path=asr_config)
  File "/home/PaddleSpeech/demos/speech_web/speech_server/src/SpeechBase/asr.py", line 37, in __init__
    self.engine.init(self.config)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 891, in init
    if not self.init_model():
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 862, in init_model
    am_predictor_conf=self.config.am_predictor_conf):
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 836, in _init_from_path
    self.init_model()
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 756, in init_model
    model = model_class.from_config(self.config)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 886, in from_config
    model = cls(configs)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 803, in __init__
    configs)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 849, in _init_from_config
    input_dim, global_cmvn=global_cmvn, **configs['encoder_conf'])
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/modules/encoder.py", line 472, in __init__
    use_dynamic_left_chunk, max_len)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/modules/encoder.py", line 130, in __init__
    max_len=max_len), )
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/modules/subsampling.py", line 114, in __init__
    Conv2D(1, odim, 3, 2),
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/modules/align.py", line 131, in __init__
    weight_attr = paddle.ParamAttr(initializer=nn.initializer.KaimingUniform(fan_in=None, negative_slope=math.sqrt(5), nonlinearity='leaky_relu'))
TypeError: __init__() got an unexpected keyword argument 'negative_slope'`
环境 ： ubuntu 20.04 
docker image TAG develop-cpu-5d5888

**Comment by yt605155624** [comment]
使用 paddle 版本 >= 2.3.1

**Comment by YuBYan** [comment]
谢谢，使用
`python -m pip install paddlepaddle==2.3.1 -i https://mirror.baidu.com/pypi/simple`  安装解决
