### ISSUE TITLE
关于用pyinstaller打包后找不到模型的问题

### ISSUE THREAD

**Issue by dsyrock** [PaddlePaddle/PaddleSpeech#2402]
我在尝试用pyinstaller打包后运行遇到一个问题

> Traceback (most recent call last):
  File "DSY_PaddleSpeech.py", line 12, in <module>
  File "paddlespeech\cli\utils.py", line 328, in _warpper
  File "paddlespeech\cli\asr\infer.py", line 473, in __call__
  File "paddlespeech\cli\asr\infer.py", line 146, in _init_from_path
  File "paddlespeech\resource\resource.py", line 72, in set_task_model
AssertionError: Can't find "conformer_wenetspeech-zh-16k" in resource. Model name must be one of []
[26888] Failed to execute script 'DSY_PaddleSpeech' due to unhandled exception!

首先确认在正常情况下，python里运行是成功的，只是打包后出错。从信息看是找不到上述的模型文件。我能找到这个文件位于c盘的路径下，但尝试过直接把他复制去打包的路径下，得到同样的出错信息。

假如我打包的路径是 K:\paddlespeech\
请问我要复制到哪个路径下，让程序能成功定位到模型文件？

**Comment by yt605155624** [comment]
问题应该不是模型文件路径的问题，请从这行为入口进行 debug, 从报错信息看, 你的 `self.pretrained_models.keys()` 都没有正常打印出来，请先确定下这里
https://github.com/PaddlePaddle/PaddleSpeech/blob/e6cbcca3e220b3b2ae869055f0771b48958b512b/paddlespeech/resource/resource.py#L73

**Comment by dsyrock** [comment]
> 问题应该不是模型文件路径的问题，请从这行为入口进行 debug, 从报错信息看, 你的 `self.pretrained_models.keys()` 都没有正常打印出来，请先确定下这里
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/e6cbcca3e220b3b2ae869055f0771b48958b512b/paddlespeech/resource/resource.py#L73

确实，打印出来是空的
odict_keys([])
这会是哪个地方出问题呢？原来的话可以打印出来
odict_keys(['conformer_wenetspeech-zh-16k', 'conformer_online_wenetspeech-zh-16k', 'conformer_online_multicn-zh-16k', 'conformer_aishell-zh-16k', 'conformer_online_aishell-zh-16k', 'transformer_librispeech-en-16k', 'deepspeech2online_wenetspeech-zh-16k', 'deepspeech2offline_aishell-zh-16k', 'deepspeech2online_aishell-zh-16k', 'deepspeech2offline_librispeech-en-16k'])

**Comment by dsyrock** [comment]
我又测试了一下，问题应该出在你说的resource.py这个文件的 def _get_pretrained_models(self) 这段
我在

> exec('from .pretrained_models import {}'.format(import_models))
models = OrderedDict(locals()[import_models])

下面加了一行
> print('models', models)

没有获得结果，那应该是exec那行没有执行了。我试试用明文的方式能不能执行

**Comment by dsyrock** [comment]
为了能顺利运行，我暂时把
exec('from .pretrained_models import {}'.format(import_models))
改为
from .pretrained_models import asr_dynamic_pretrained_models
然后出现了新的问题

> Traceback (most recent call last):
  File "DSY_PaddleSpeech.py", line 12, in <module>
  File "paddlespeech\cli\utils.py", line 328, in _warpper
  File "paddlespeech\cli\asr\infer.py", line 472, in __call__
  File "paddlespeech\cli\asr\infer.py", line 196, in _init_from_path
  File "paddlespeech\resource\resource.py", line 114, in get_model_class
  File "paddlespeech\utils\dynamic_import.py", line 37, in dynamic_import
  File "importlib\__init__.py", line 127, in import_module
  File "\<frozen importlib._bootstrap\>", line 1014, in _gcd_import
  File "\<frozen importlib._bootstrap\>", line 991, in _find_and_load
  File "\<frozen importlib._bootstrap\>", line 961, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap\>", line 219, in _call_with_frames_removed
  File "\<frozen importlib._bootstrap\>", line 1014, in _gcd_import
  File "\<frozen importlib._bootstrap\>", line 991, in _find_and_load
  File "\<frozen importlib._bootstrap\>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'paddlespeech.s2t.models'

实在没找到这个 frozen importlib._bootstrap 文件在哪里，只找到_bootstrap.py

**Comment by yt605155624** [comment]
我们的打包方式参考：https://github.com/PaddlePaddle/PaddleSpeech/wiki/Build-Pip-Package-and-Upload 没用过 pyinstaller，没有相关经验

**Comment by SmileGoat** [comment]
importlib._bootstrap 这类在打包文件的时候，会生成。模型文件，好像是打包不进去的，具体你可以check一下setup.py。你要是打包自己修改的python文件，使用 上述链接的setup.py 的命令就可以，要是定制化打包内容，可以修改 setup.py，目前的经验只有这些，

**Comment by dsyrock** [comment]
> importlib._bootstrap 这类在打包文件的时候，会生成。模型文件，好像是打包不进去的，具体你可以check一下setup.py。你要是打包自己修改的python文件，使用 上述链接的setup.py 的命令就可以，要是定制化打包内容，可以修改 setup.py，目前的经验只有这些，

感谢！我试试看。模型文件倒是没所谓，初次运行会自动下载

**Comment by dsyrock** [comment]
> 我们的打包方式参考：https://github.com/PaddlePaddle/PaddleSpeech/wiki/Build-Pip-Package-and-Upload 没用过 pyinstaller，没有相关经验

感谢！我试试看

**Comment by dsyrock** [comment]
搞了好几天终于成功用pyinstaller打包了paddspeech，分享一下经验

- 首先保证代码在python环境下能正常运行

- 修改部分代码
```
site-packages/paddle/dataset/image.py
找到这段代码
if six.PY3:
    import subprocess
    import sys
    import_cv2_proc = subprocess.Popen(
        [sys.executable, "-c", "import cv2"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)
    out, err = import_cv2_proc.communicate()
    retcode = import_cv2_proc.poll()
    if retcode != 0:
        cv2 = None
    else:
        import cv2
else:
    try:
        import cv2
    except ImportError:
        cv2 = None

改成
try:
    import cv2
except ImportError:
    cv2 = None
```

```
site-packages/paddlespeech/resource/resource.py
找到这段代码
exec('from .pretrained_models import {}'.format(import_models))
先在他上面或下面加一句
print(import_models)
然后运行一下原代码，打印出你具体需要的这个变量的名字，比如我这里是 asr_dynamic_pretrained_models
然后注释掉exec和删掉print行，加一行
from .pretrained_models import asr_dynamic_pretrained_models  # import后面的内容以你print的结果为准
```

- 用pyinstaller打包，打包方式必须用文件夹方式，后续还要往里面拷文件

- 从自己python安装路径下的 site-packages，找到以下文件夹复制去你打包好的路径下
> librosa
paddle
paddlespeech
textgrid
typeguard

至此应该能成功地独立运行

补充一下，打包后文件夹里有几个大家伙是可以删除的，节省点空间
> tensorflow
torch
PyQt5
