### ISSUE TITLE
windows10 Pycharm运行报错

### ISSUE THREAD

**Issue by starflag** [PaddlePaddle/PaddleSpeech#2431]
```
from paddlespeech.cli.asr.infer import ASRExecutor
asr = ASRExecutor()
path = 'sound/1.wav'
res = asr(audio_file=path, sample_rate=8000)
print(res)
```
这里audio_file=path高亮，查看代码发现没有此变量，要改成什么？

报错信息：
`C:\Users\usr\.conda\envs\py38\lib\site-packages\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "C:/Users/usr/PycharmProjects/SpeechRecog/SpeRecog.py", line 6, in <module>
    res = asr(audio_file=path, sample_rate=8000)
  File "C:\Users\usr\.conda\envs\py38\lib\site-packages\paddlespeech\cli\utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "C:\Users\usr\.conda\envs\py38\lib\site-packages\paddlespeech\cli\asr\infer.py", line 473, in __call__
    self._init_from_path(model, lang, sample_rate, config, decode_method,
  File "C:\Users\usr\.conda\envs\py38\lib\site-packages\paddlespeech\cli\asr\infer.py", line 146, in _init_from_path
    self.task_resource.set_task_model(tag, version=None)
  File "C:\Users\usr\.conda\envs\py38\lib\site-packages\paddlespeech\resource\resource.py", line 72, in set_task_model
    assert model_tag in self.pretrained_models, \
AssertionError: Can't find "conformer_wenetspeech-zh-8k" in resource. Model name must be one of ['conformer_wenetspeech-zh-16k', 'conformer_online_wenetspeech-zh-16k', 'conformer_online_multicn-zh-16k', 'conformer_aishell-zh-16k', 'conformer_online_aishell-zh-16k', 'transformer_librispeech-en-16k', 'deepspeech2online_wenetspeech-zh-16k', 'deepspeech2offline_aishell-zh-16k', 'deepspeech2online_aishell-zh-16k', 'deepspeech2offline_librispeech-en-16k']

查看生成的日志：
`2022-09-21 18:04:50.441 | DEBUG    | paddlespeech.s2t:<module>:42 - register user softmax to paddle, remove this when fixed!
2022-09-21 18:04:50.441 | DEBUG    | paddlespeech.s2t:<module>:46 - register user log_softmax to paddle, remove this when fixed!
2022-09-21 18:04:50.441 | DEBUG    | paddlespeech.s2t:<module>:50 - register user sigmoid to paddle, remove this when fixed!
2022-09-21 18:04:50.441 | DEBUG    | paddlespeech.s2t:<module>:54 - register user log_sigmoid to paddle, remove this when fixed!
2022-09-21 18:04:50.442 | DEBUG    | paddlespeech.s2t:<module>:58 - register user relu to paddle, remove this when fixed!
2022-09-21 18:04:50.442 | DEBUG    | paddlespeech.s2t:<module>:67 - override cat of paddle if exists or register, remove this when fixed!
2022-09-21 18:04:50.442 | DEBUG    | paddlespeech.s2t:<module>:89 - override long of paddle.Tensor if exists or register, remove this when fixed!
2022-09-21 18:04:50.442 | DEBUG    | paddlespeech.s2t:<module>:111 - override new_full of paddle.Tensor if exists or register, remove this when fixed!
2022-09-21 18:04:50.442 | DEBUG    | paddlespeech.s2t:<module>:122 - override contiguous of paddle.Tensor if exists or register, remove this when fixed!
2022-09-21 18:04:50.442 | DEBUG    | paddlespeech.s2t:<module>:134 - register user view to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.443 | DEBUG    | paddlespeech.s2t:<module>:144 - register user view_as to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.443 | DEBUG    | paddlespeech.s2t:<module>:181 - register user masked_fill to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.443 | DEBUG    | paddlespeech.s2t:<module>:200 - register user masked_fill_ to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.443 | DEBUG    | paddlespeech.s2t:<module>:224 - register user repeat to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.445 | DEBUG    | paddlespeech.s2t:<module>:230 - register user softmax to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.445 | DEBUG    | paddlespeech.s2t:<module>:235 - register user sigmoid to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.445 | DEBUG    | paddlespeech.s2t:<module>:240 - register user relu to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.445 | DEBUG    | paddlespeech.s2t:<module>:249 - register user type_as to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.446 | DEBUG    | paddlespeech.s2t:<module>:266 - register user to to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.446 | DEBUG    | paddlespeech.s2t:<module>:276 - register user float to paddle.Tensor, remove this when fixed!
2022-09-21 18:04:50.446 | DEBUG    | paddlespeech.s2t:<module>:287 - register user int to paddle.Tensor, remove this when fixed!`
`
是没有模型的问题吗？模型是要在哪里下，保存在哪里？

**Comment by yt605155624** [comment]
目前不支持 8k 的 sample_rate

**Comment by yaleimeng** [comment]
先把测试音频的采样率转换到16000，然后再调用函数进行识别。
