### ISSUE TITLE
rir_noise MD5 报错！！！

### ISSUE THREAD

**Issue by JJun-Guo** [PaddlePaddle/PaddleSpeech#2436]
MD5 Chesksum ./PaddleSpeech-develop/dataset/rir_noise/rirs_noises.zip ...
Traceback (most recent call last):
  File "./PaddleSpeech-develop/dataset/rir_noise/rir_noise.py", line 117, in <module>
    main()
  File "./PaddleSpeech-develop/dataset/rir_noise/rir_noise.py", line 113, in main
    manifest_path=args.manifest_prefix)
  File "./PaddleSpeech-develop/dataset/rir_noise/rir_noise.py", line 97, in prepare_dataset
    filepath = download(url, md5sum, target_dir)
  File "./PaddleSpeech-develop/utils/utility.py", line 146, in download
    raise RuntimeError("MD5 checksum failed.")
RuntimeError: MD5 checksum failed.
Prepare rir_noise failed. Terminated.

**Comment by yt605155624** [comment]
原始下载链接是这个，我怀疑是原本的 md5 值变了所以过不了我们的检查，可以自己先手动下载的指定位置 https://github.com/PaddlePaddle/PaddleSpeech/blob/1a1ce92cb4576e0e810857f06f01b26a686ee6f7/dataset/rir_noise/rir_noise.py#L37 我们看下是不是 md5 值有变化
