### ISSUE TITLE
[TTS]使用speech_web的小数据集微调报错

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2461]
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 69, in align_corpus
TypeError: 'NoneType' object is not subscriptable
[4100] Failed to execute script align
10 1
100%|████████████████████████████████████████| 10/10 [00:00<00:00, 16905.70it/s]
Done
Traceback (most recent call last):
  File "/home/fyy/ResourceCode/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 335, in <module>
    pretrained_model_dir=pretrained_model_dir)
  File "/home/fyy/ResourceCode/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 254, in extract_feature
    vocab_speaker, dump_dir, "train")
  File "/home/fyy/ResourceCode/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 148, in normalize
    "energy": np.load,
  File "/home/fyy/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddlespeech/t2s/datasets/data_table.py", line 45, in __init__
    assert len(data) > 0, "This dataset has no examples"
AssertionError: This dataset has no examples
rank: 0, pid: 4132, parent_pid: 4071
multiple speaker fastspeech2!
spk_num: 174
Traceback (most recent call last):
  File "/home/fyy/ResourceCode/PaddleSpeech/examples/other/tts_finetune/tts3/local/finetune.py", line 269, in <module>
    train_sp(train_args, config)
  File "/home/fyy/ResourceCode/PaddleSpeech/examples/other/tts_finetune/tts3/local/finetune.py", line 120, in train_sp
    with jsonlines.open(args.train_metadata, 'r') as reader:
  File "/home/fyy/miniconda3/envs/paddle_env/lib/python3.7/site-packages/jsonlines/jsonlines.py", line 627, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/fyy/ResourceCode/PaddleSpeech/demos/speech_web/speech_server/tmp_dir/finetune/default/dump/train/norm/metadata.jsonl'
上面是报错信息

**Comment by yt605155624** [comment]
应该是用 MFA 对齐有问题，可以直接用 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tts_finetune/tts3 看看具体报错信息，TTS finetune 问题汇总可以参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/2456

**Comment by oyb1125** [comment]
好的 解决了 参考https://github.com/PaddlePaddle/PaddleSpeech/issues/2319#issuecomment-1229405871
