### ISSUE TITLE
使用ecapa-tdnn进行语音克隆报错

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2471]
![2022-09-28 10-27-22 的屏幕截图](https://user-images.githubusercontent.com/62881198/192674046-4c64e0a4-fb26-4a9d-9382-be28115919f5.png)
如图 使用这个功能报下面的错是什么原因
Traceback (most recent call last):
  File "/home/fyy/ResourceCode/PaddleSpeech/paddlespeech/t2s/exps/voice_cloning.py", line 233, in <module>
    main()
  File "/home/fyy/ResourceCode/PaddleSpeech/paddlespeech/t2s/exps/voice_cloning.py", line 229, in main
    voice_cloning(args)
  File "/home/fyy/ResourceCode/PaddleSpeech/paddlespeech/t2s/exps/voice_cloning.py", line 69, in voice_cloning
    audio_file=input_dir / os.listdir(input_dir)[0], force_yes=True)
  File "/home/fyy/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddlespeech/cli/utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'force_yes'

**Comment by yt605155624** [comment]
请 git clone PaddleSpeech 之后，在 PaddleSpeech 目录执行 
`pip install .` (安装依赖和 paddlespeech) 或者 `python3 setup.py install` (仅安装 paddlespeech 不安装依赖)
安装 develop 版本的 paddlespeech, 目前发行版的 paddlespeech 中还没有这个功能

**Comment by oyb1125** [comment]
> 请 git clone PaddleSpeech 之后，在 PaddleSpeech 目录执行 `pip install .` (安装依赖和 paddlespeech) 或者 `python3 setup.py install` (仅安装 paddlespeech 不安装依赖) 安装 develop 版本的 paddlespeech, 目前发行版的 paddlespeech 中还没有这个功能

感谢 可以了
