### ISSUE TITLE
看不明白发生啥了

### ISSUE THREAD

**Issue by ydroxy** [PaddlePaddle/PaddleSpeech#2519]
D:\PaddleSpeech-develop\demos\speech_web\speech_server>python main.py --port 8010
2022-10-11 03:52:59.439 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 11004] getaddrinfo failed>
[nltk_data] Error loading cmudict: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
INFO 2022-10-11 03:53:02,951 loader.py:54] Loading faiss with AVX2 support.
INFO 2022-10-11 03:53:02,951 loader.py:58] Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
INFO 2022-10-11 03:53:02,951 loader.py:64] Loading faiss.
INFO 2022-10-11 03:53:03,085 loader.py:66] Successfully loaded faiss.
[2022-10-11 03:53:03,398] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'source/model'.
W1011 03:53:03.420004 13704 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W1011 03:53:03.421998 13704 dynamic_loader.cc:276] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "D:\PaddleSpeech-develop\demos\speech_web\speech_server\main.py", line 65, in <module>
    chatbot = Robot(
  File "D:\PaddleSpeech-develop\demos\speech_web\speech_server\src\robot.py", line 17, in __init__
    self.nlp = NLP(ie_model_path=ie_model_path)
  File "D:\PaddleSpeech-develop\demos\speech_web\speech_server\src\SpeechBase\nlp.py", line 8, in __init__
    self.ie_model = Taskflow(
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\taskflow\taskflow.py", line 513, in __init__
    self.task_instance = task_class(model=self.model,
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 361, in __init__
    self._get_inference_model()
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\taskflow\task.py", line 228, in _get_inference_model
    self._construct_model(self.model)
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\taskflow\information_extraction.py", line 419, in _construct_model
    model_instance = UIE.from_pretrained(self._task_path)
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\transformers\model_utils.py", line 348, in from_pretrained
    base_model = cls.base_model_class(*base_args, **base_kwargs)
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\transformers\utils.py", line 159, in __impl__
    init_func(self, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 841, in __init__
    self.embeddings = ErnieEmbeddings(vocab_size, hidden_size,
  File "C:\Program Files\Python39\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 59, in __init__
    self.word_embeddings = nn.Embedding(vocab_size,
  File "C:\Users\Ydroxy\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py", line 1453, in __init__
    self.weight = self.create_parameter(
  File "C:\Users\Ydroxy\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "C:\Users\Ydroxy\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "C:\Users\Ydroxy\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "C:\Users\Ydroxy\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\initializer.py", line 472, in __call__
    out_var = _C_ops.truncated_gaussian_random(
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:303)
  [operator < truncated_gaussian_random > error]

D:\PaddleSpeech-develop\demos\speech_web\speech_server>

**Comment by ydroxy** [comment]
python3 D:\PaddleSpeech-develop\paddlespeech/t2s/exps/voice_cloning.py                     --am=fastspeech2_aishell3                     --am_config=source/model/fastspeech2_aishell3_ckpt_vc2_1.2.0/default.yaml                     --am_ckpt=source/model/fastspeech2_aishell3_ckpt_vc2_1.2.0/snapshot_iter_96400.pdz                     --am_stat=source/model/fastspeech2_aishell3_ckpt_vc2_1.2.0/speech_stats.npy                     --voc=pwgan_aishell3                     --voc_config=source/model/pwg_aishell3_ckpt_0.5/default.yaml                     --voc_ckpt=source/model/pwg_aishell3_ckpt_0.5/snapshot_iter_1000000.pdz                     --voc_stat=source/model/pwg_aishell3_ckpt_0.5/feats_stats.npy                     --text="欢迎使用飞桨语音套件"                     --input-dir=D:\PaddleSpeech-develop\demos\speech_web\speech_server\tmp_dir\tdnn                     --output-dir=source/wav/vc/out                     --phones-dict=source/model/fastspeech2_aishell3_ckpt_vc2_1.2.0/phone_id_map.txt                     --use_ecapa=True                     --ngpu=1

运行结果： 0
INFO:     127.0.0.1:9302 - "POST /vc/clone_g2p HTTP/1.1" 200 OK

**Comment by yt605155624** [comment]
先在仓库里搜下  nltk_data 解决下 ：）
