### ISSUE TITLE
gpu内存不够报错【已解决】

### ISSUE THREAD

**Issue by yunqi777** [PaddlePaddle/PaddleSpeech#2599]
【已解决】
终端输入nvidia-smi查看cuda版本
参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
选择对应cuda版本的paddle
【原题】
数据集有四千多条数据，但是之前五千多条的时候没有报错，为什么会这样呢？该怎么办？
![Snipaste_2022-10-30_10-36-00](https://user-images.githubusercontent.com/110005064/198860038-980cf8ef-e9fe-4e43-b5f1-b37b892e18fd.png)

**Comment by yt605155624** [comment]
请检查 GPU 显存是否正确释放，和数据集总数无关，和 batch_size 有挂

**Comment by yunqi777** [comment]
> 请检查 GPU 显存是否正确释放，和数据集总数无关，和 batch_size 有挂

请问如何检查显存释放呢？调小了batch_size还是会显存突然增高

**Comment by yt605155624** [comment]
1. 请问如何检查显存释放呢？ -> 训练结束后 nvidia-smi 查看显存是否还被占用
2. 调小了batch_size还是会显存突然增高 -> 看看是不是个别数据长度明显比其他的长
3. 可以尝试加一些 FLAGS https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/memory_cn.html#flags-allocator-strategy

**Comment by idreamerhx** [comment]
我这边也有一个类似问题，借楼麻烦看下。  cpu运行正常，没有在其他gpu上测试过。显卡是rtx3090
I have a same problem。 cpu runs ok but not tested on other gpus. the graphic card is rtx3090/.

谢谢
thanks

(pyvenv-paddlespeech) (ubu20x86-cuda118-paddle) root@1:/opt/sound# paddlespeech asr --model conformer_wenetspeech --lang zh --input zh.wav
/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
W1101 13:55:41.336647  1891 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 10.2
W1101 13:55:41.346014  1891 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
[2022-11-01 13:55:52,641] [   ERROR] - (Fatal) Operator range raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 655.142555PB memory on GPU 0, 1.108154GB memory has been allocated and available memory is only 22.589050GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)
Traceback (most recent call last):
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 300, in infer
    result_transcripts = self.model.decode(
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 817, in decode
    hyp = self.attention_rescoring(
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 548, in attention_rescoring
    hyps, encoder_out = self._ctc_prefix_beam_search(
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 429, in _ctc_prefix_beam_search
    encoder_out, encoder_mask = self._forward_encoder(
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 231, in _forward_encoder
    encoder_out, encoder_mask = self.encoder(
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/modules/encoder.py", line 163, in forward
    masks = make_non_pad_mask(xs_lens).unsqueeze(1)  # (B, 1, L)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/modules/mask.py", line 90, in make_non_pad_mask
    return make_pad_mask(lengths).logical_not()
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/modules/mask.py", line 61, in make_pad_mask
    seq_range = paddle.arange(0, max_len, dtype=paddle.int64)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/tensor/creation.py", line 567, in arange
    return paddle.fluid.layers.range(start, end, step, dtype, name)
  File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 1505, in range
    out = _C_ops.range(start, end, step)
SystemError: (Fatal) Operator range raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 655.142555PB memory on GPU 0, 1.108154GB memory has been allocated and available memory is only 22.589050GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)

KeyError: 'result'(

**Comment by idreamerhx** [comment]
测试了同样环境的nlp  cv 等模型，gpu是可以正常运行的。看起来是语音相关的某些算子的问题

**Comment by idreamerhx** [comment]
/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py:1505

############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [5000.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [1.])
############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [512.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [2.])
############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [5000.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [1.])
############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [512.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [2.])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [80]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [256]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [4703889136186909696]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])


对应--device=cpu : 

############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [5000.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [1.])
############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [512.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [2.])
############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [5000.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [1.])
############### Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [512.]) Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [2.])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [80]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [256]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [498]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [21]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py:276: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.bool, the right dtype will convert to paddle.int64
  warnings.warn(
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [10]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
############### Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [0]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [22]) Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])

**Comment by yt605155624** [comment]
@idreamerhx 你这里报错需要这么多的显存肯定是不正常的
```text
0. Cannot allocate 655.142555PB memory on GPU 0
```
我注意到你的 paddle-gpu 版本和 CUDA 版本不匹配，你的 CUDA 很新但是你安装的是 10.2 版本 CUDA 的 paddle，请安装对应 CUDA 版本(11.6)的 paddle，参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
```text
W1101 13:55:41.336647 1891 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 10.2
```

**Comment by idreamerhx** [comment]
File "/opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/s2t/modules/mask.py", line 61, in make_pad_mask

max_len = int(lengths.max())

cpu:
############### 498
gpu:
############### 4703889136186910055

我换成了
max_len = lengths.item()
看起来后面的代码还有问题。

**Comment by idreamerhx** [comment]
感谢。 是版本问题 我更新了paddlepaddle-gpu   post11.6 已经可以用了.
感谢楼主

**Comment by yunqi777** [comment]
> @idreamerhx @yt605155624 你这里报错需要这么多的显存肯定是不正常的
> 
> ```
> 0. Cannot allocate 655.142555PB memory on GPU 0
> ```
> 
> 我注意到你的 paddle-gpu 版本和 CUDA 版本不匹配，你的 CUDA 很新但是你安装的是 10.2 版本 CUDA 的 paddle，请安装对应 CUDA 版本(11.6)的 paddle，参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
> 
> ```
> W1101 13:55:41.336647 1891 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 10.2
> ```

我是cuda11.2，原先是paddle2.2.2版本，现在换成了2.3.2，但是产生新的报错
![image](https://user-images.githubusercontent.com/110005064/199218542-7a2ec359-4da0-4620-b8a8-2425ebd6d54b.png)

**Comment by idreamerhx** [comment]
是的，我换成 post11.6就可以了。
如果能排除cuda环境问题，建议先定位到paddle代码吧

**Comment by yunqi777** [comment]
@yt605155624 多谢大佬，我修改了paddle的版本，现在已经能正常运行了
