### ISSUE TITLE
[TTS]wavernn合成报错

### ISSUE THREAD

**Issue by kslz** [PaddlePaddle/PaddleSpeech#2653]
使用fastspeech2和wavernn进行合成，命令如下
```
python3 /home/aistudio/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py \
--am=fastspeech2_mix \
--am_config=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/default.yaml \
--am_ckpt=/home/aistudio/work/exp_spkxtdt/output/checkpoints/snapshot_iter_113958.pdz \
--am_stat=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/speech_stats.npy \
--voc=wavernn_csmsc \
--voc_config=/home/aistudio/checkpoint/wavernn_csmsc_ckpt_0.2.0/default.yaml \
--voc_ckpt=/home/aistudio/checkpoint/wavernn_csmsc_ckpt_0.2.0/snapshot_iter_400000.pdz \
--voc_stat=/home/aistudio/checkpoint/wavernn_csmsc_ckpt_0.2.0/feats_stats.npy \
--lang=mix \
--text=/home/aistudio/work/exp_spkxtdt/sentence.txt \
--output_dir=/home/aistudio/work/exp_spkxtdt/wav_out_rnn \
--phones_dict=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/phone_id_map.txt \
--speaker_dict=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/speaker_id_map.txt \
--spk_id=0 \
--ngpu=1
```

经测试 fs2+pwg 运行正常，使用下面的方式调用 fs2+wavernn 合成成功，唯独使用synthesize_e2e.py合成失败
```
from paddlespeech.cli.tts.infer import TTSExecutor
tts = TTSExecutor()
tts(text="欢迎使用飞桨！",
    output="output.wav", 
    am="fastspeech2_mix",
    am_ckpt=am_ckpt,           # 微调后的模型地址
    am_config = os.path.join(out_am_path, "default.yaml"),
    am_stat = os.path.join(out_am_path, "speech_stats.npy"),
    
    phones_dict = os.path.join(out_am_path, "phone_id_map.txt"),
    speaker_dict = os.path.join(out_am_path, "speaker_id_map.txt"),
    spk_id = 0,
    
    voc = "wavernn_csmsc",
    voc_config = os.path.join(out_vocoder_path, "default.yaml"),
    voc_ckpt = os.path.join(out_vocoder_path, "snapshot_iter_400000.pdz"),
    voc_stat = os.path.join(out_vocoder_path, "feats_stats.npy"),
    lang="mix"
    )
```

**Comment by kslz** [comment]
报错截图
![image](https://user-images.githubusercontent.com/54951765/201888121-40a6c522-9b27-49a9-810a-8c25873dd0ca.png)

```
seed: 42
train_max_steps: 400000
valid_size: 50
win_length: 1200
window: hann
[2022-11-15 17:13:34,412] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/bert-base-chinese/bert-base-chinese-vocab.txt
[2022-11-15 17:13:34,425] [    INFO] - tokenizer config file saved in /home/aistudio/.paddlenlp/models/bert-base-chinese/tokenizer_config.json
[2022-11-15 17:13:34,426] [    INFO] - Special tokens file saved in /home/aistudio/.paddlenlp/models/bert-base-chinese/special_tokens_map.json
frontend done!
W1115 17:13:36.931214 11326 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W1115 17:13:36.935981 11326 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
acoustic model done!
voc done!
Building prefix dict from the default dictionary ...
[2022-11-15 17:13:38] [DEBUG] [__init__.py:113] Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
[2022-11-15 17:13:38] [DEBUG] [__init__.py:133] Loading model from cache /tmp/jieba.cache
Loading model cost 0.697 seconds.
[2022-11-15 17:13:38] [DEBUG] [__init__.py:165] Loading model cost 0.697 seconds.
Prefix dict has been built successfully.
[2022-11-15 17:13:38] [DEBUG] [__init__.py:166] Prefix dict has been built successfully.
Traceback (most recent call last):
  File "/home/aistudio/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 262, in <module>
    main()
  File "/home/aistudio/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 258, in main
    evaluate(args)
  File "/home/aistudio/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 136, in evaluate
    wav = voc_inference(mel)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlespeech/t2s/models/wavernn/wavernn.py", line 603, in forward
    normalized_mel, )
  File "<decorator-gen-442>", line 2, in generate
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlespeech/t2s/models/wavernn/wavernn.py", line 416, in generate
    output[-10 * self.hop_length:] *= fade_out
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2100] and the shape of Y = [3000]. Received [2100] in X is not equal to [3000] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_mul > error]
```

**Comment by yt605155624** [comment]
synthesize_e2e.py 走了动转静流程，可能是最新版的框架有不匹配的地方，可以尝试注释动转静部分
https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/examples/csmsc/tts3/local/synthesize_e2e.sh#L113

**Comment by kslz** [comment]
请问是

> synthesize_e2e.py 走了动转静流程，可能是最新版的框架有不匹配的地方，可以尝试注释动转静部分
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/examples/csmsc/tts3/local/synthesize_e2e.sh#L113

请问是这里的函数要换成别的吗
![image](https://user-images.githubusercontent.com/54951765/201893092-fb9183a0-70a1-4ff7-bc4a-5f25bc9f5fa2.png)
https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/exps/synthesize_e2e.py#L136

**Comment by yt605155624** [comment]
注释掉这行就行  --inference_dir=${train_output_path}/inference 别的不用改，这行上面那行后面的 "\" 可能也要注释掉

**Comment by kslz** [comment]
> 注释掉这行就行 --inference_dir=${train_output_path}/inference 别的不用改，这行上面那行后面的 "" 可能也要注释掉

这是我的命令 没加这个参数
```
python3 /home/aistudio/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py \
--am=fastspeech2_mix \
--am_config=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/default.yaml \
--am_ckpt=/home/aistudio/work/exp_spkxtdt/output/checkpoints/snapshot_iter_113958.pdz \
--am_stat=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/speech_stats.npy \
--voc=wavernn_csmsc \
--voc_config=/home/aistudio/checkpoint/wavernn_csmsc_ckpt_0.2.0/default.yaml \
--voc_ckpt=/home/aistudio/checkpoint/wavernn_csmsc_ckpt_0.2.0/snapshot_iter_400000.pdz \
--voc_stat=/home/aistudio/checkpoint/wavernn_csmsc_ckpt_0.2.0/feats_stats.npy \
--lang=mix \
--text=/home/aistudio/work/exp_spkxtdt/sentence.txt \
--output_dir=/home/aistudio/work/exp_spkxtdt/wav_out_rnn \
--phones_dict=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/phone_id_map.txt \
--speaker_dict=/home/aistudio/checkpoint/fastspeech2_mix_ckpt_1.2.0/speaker_id_map.txt \
--spk_id=0 \
--ngpu=1
```

**Comment by yt605155624** [comment]
那很奇怪，除了这一行，synthesize_e2e 和 [TTS cli](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/cli/tts/infer.py) 应该没什么区别
https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/exps/synthesize_e2e.py#L77

你自己 debug 下这行吧，我暂时没时间看

```text
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlespeech/t2s/models/wavernn/wavernn.py", line 416, in generate
    output[-10 * self.hop_length:] *= fade_out
```

**Comment by kslz** [comment]
> 

我好像发现问题了，是因为我的合成句子不一样，报错的合成句子是【第一章。。。 】我为了增加停顿加了许多标点，wavernn在这种情况下会报错

**Comment by kslz** [comment]
别的声码器都能应付这种情况，有什么建议么...

**Comment by kslz** [comment]
如果以后有好解决方案记得踢我，最好像wavernn一样好，又像pwgan一样快
