### ISSUE TITLE
[S2T]ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by KHLau96** [PaddlePaddle/PaddleSpeech#2672]
Any one install successful but run with error?

When I finished installation successfully with no error, I try to run [Punctuation Restoration]:
Command:   paddlespeech text --task punc --input 今天的天气真不错啊你下午有空吗我想约你一起去吃饭

Then, an error appear:

Traceback (most recent call last):
  File "/home/lgx/anaconda3/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/cli/text/__init__.py", line 14, in <module>
    from .infer import TextExecutor
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/cli/text/infer.py", line 29, in <module>
    from paddlespeech.text.models.ernie_linear import ErnieLinear
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/text/models/__init__.py", line 15, in <module>
    from .ernie_linear import ErnieLinear
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/text/models/ernie_linear/__init__.py", line 16, in <module>
    from .ernie_linear_updater import *
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/text/models/ernie_linear/ernie_linear_updater.py", line 24, in <module>
    from paddlespeech.t2s.training.extensions.evaluator import StandardEvaluator
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/t2s/__init__.py", line 18, in <module>
    from . import frontend
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/t2s/frontend/__init__.py", line 15, in <module>
    from .normalizer import *
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/t2s/frontend/normalizer/__init__.py", line 14, in <module>
    from paddlespeech.t2s.frontend.normalizer.normalizer import *
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/t2s/frontend/normalizer/normalizer.py", line 18, in <module>
    from paddlespeech.t2s.frontend.normalizer.numbers import normalize_numbers
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/paddlespeech/t2s/frontend/normalizer/numbers.py", line 17, in <module>
    import inflect
  File "/home/lgx/anaconda3/lib/python3.7/site-packages/inflect/__init__.py", line 76, in <module>
    from pydantic import Field, validate_arguments
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
    #   |
ImportError: cannot import name dataclass_transform

How can I fix it? thanks.

**Comment by zh794390558** [comment]
pydantic.dataclasses 没有安装吧

**Comment by wizardforcel** [comment]
@zh794390558 这个包根本就没加到依赖项里面

**Comment by vscv** [comment]
依照簡單安裝法，但使用時報錯。


$paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/cli/tts/infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/__init__.py", line 18, in <module>
    from . import frontend
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/__init__.py", line 15, in <module>
    from .normalizer import *
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/normalizer/__init__.py", line 14, in <module>
    from paddlespeech.t2s.frontend.normalizer.normalizer import *
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/normalizer/normalizer.py", line 18, in <module>
    from paddlespeech.t2s.frontend.normalizer.numbers import normalize_numbers
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/normalizer/numbers.py", line 17, in <module>
    import inflect
  File "/usr/local/lib/python3.8/dist-packages/inflect/__init__.py", line 76, in <module>
    from pydantic import Field, validate_arguments
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform
