### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 2088: illegal multibyte sequence

### ISSUE THREAD

**Issue by stuyun** [PaddlePaddle/PaddleSpeech#2689]
![image](https://user-images.githubusercontent.com/8639389/204082536-59031b28-0737-4286-abd7-40031fe45c45.png)

**Comment by stuyun** [comment]
处理了 修改编码
![image](https://user-images.githubusercontent.com/8639389/204083241-84c9a9ae-ed65-43ab-bbd0-946cede30993.png)

![image](https://user-images.githubusercontent.com/8639389/204083285-a826545f-c338-4740-86db-457299978d51.png)

**Comment by yt605155624** [comment]
感兴趣可以提个 pr

**Comment by bbqkj** [comment]
666 也没报错路径 这能找出来 得熟读源码啊

**Comment by yfqvip** [comment]
set PYTHONUTF8=1
可解决

**Comment by Darksiderlyd** [comment]
Traceback (most recent call last):
  File "D:\lvyaodong\python3\lib\runpy.py", line 196, in _run_module_as_main
    exec(code, run_globals)
  File "D:\aiworkspace\PaddleSpeech\.venv\Scripts\paddlespeech.exe\__main__.py", line 7, in <module>
    sys.exit(_execute())
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\paddlespeech\cli\entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\paddlespeech\cli\tts\__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\paddlespeech\cli\tts\infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\paddlespeech\t2s\exps\syn_utils.py", line 36, in <module>
    from paddlespeech.t2s.frontend.canton_frontend import CantonFrontend
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\paddlespeech\t2s\frontend\canton_frontend.py", line 19, in <module>
    import ToJyutping
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\ToJyutping\__init__.py", line 3, in <module>
    from .ToJyutping import *
  File "D:\aiworkspace\PaddleSpeech\.venv\lib\site-packages\ToJyutping\ToJyutping.py", line 9, in <module>
    for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x96 in position 2: illegal multibyte sequence

我也遇到问题了 develop分支
