### ISSUE TITLE
ST相关：FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by LaHeriody** [PaddlePaddle/PaddleSpeech#2691]
as I run `paddlespeech st --input en.wav`
I get 
`(venv) E:\Github_repository\PaddleSpeech>paddlespeech st --input en.wav
E:\Github_repository\PaddleSpeech\venv\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2022-11-27 20:24:35.447 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
2022-11-27 20:24:36.027 | INFO     | paddlespeech.s2t.models.u2_st.u2_st:_init_from_config:581 - U2 Encoder type: transformer
2022-11-27 20:24:38.496 | INFO     | paddlespeech.s2t.models.u2_st.u2_st:_init_from_config:596 - ASR Joint Training Weight: 0.5
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
(venv) E:\Github_repository\PaddleSpeech>
`
as I run the code below
`from paddlespeech.cli.st.infer import STExecutor
st = STExecutor()
result = st(audio_file="en.wav")
`
I get
`E:\Github_repository\PaddleSpeech\venv\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2022-11-27 20:21:40.534 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
2022-11-27 20:21:40.877 | INFO     | paddlespeech.s2t.models.u2_st.u2_st:_init_from_config:581 - U2 Encoder type: transformer
2022-11-27 20:21:42.771 | INFO     | paddlespeech.s2t.models.u2_st.u2_st:_init_from_config:596 - ASR Joint Training Weight: 0.5
Traceback (most recent call last):
  File "E:\Github_repository\PaddleSpeech\my_demo\en2zh_demo.py", line 7, in <module>
    result = st(audio_file="en.wav")
  File "E:\Github_repository\PaddleSpeech\paddlespeech\cli\utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "E:\Github_repository\PaddleSpeech\paddlespeech\cli\st\infer.py", line 346, in __call__
    self.preprocess(audio_file, model)
  File "E:\Github_repository\PaddleSpeech\paddlespeech\cli\st\infer.py", line 206, in preprocess
    fbank_extract_process = subprocess.Popen(
  File "D:\python\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\python\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Process finished with exit code 1
`

it seems to be something missing with my user_path or system_path environment parameters, but I have no idea.

**Comment by zh794390558** [comment]
ST can not running on win os, please use ubuntu.

**Comment by LaHeriody** [comment]
thank you so much
