### ISSUE TITLE
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wangtiance** [PaddlePaddle/PaddleSpeech#2715]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
How I installed: pip install paddlepaddle paddlespeech
Issue: I ran paddlespeech from the command line and got the following:

Error: Can not import paddle core while this file exists: /home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/spt/miniconda3/envs/xuanci/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .asr import ASRExecutor
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddlespeech/cli/asr/infer.py", line 24, in <module>
    import paddle
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/spt/miniconda3/envs/xuanci/lib/python3.10/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

**Environment (please complete the following information):**
 - OS: Centos 7
 - GCC/G++ Version 4.8.5
 - Python Version 3.10
paddle-bfloat      0.1.7
paddle2onnx        1.0.3
paddleaudio        1.0.2
paddlefsl          1.1.0
paddlenlp          2.4.4
paddlepaddle       2.4.0
paddlespeech       1.0.1
paddlespeech-feat  0.1.0

**Comment by wangtiance** [comment]
BTW, this file exists:
/home/spt/miniconda3/envs/xuanci/lib/libpython3.10.so.1.0

**Comment by wangtiance** [comment]
Okay, I solved the problem by
export LD_LIBRARY_PATH=/home/spt/miniconda3/envs/xuanci/lib/

**Comment by yt605155624** [comment]
This is the bug of paddle 2.4.0, please use paddle 2.3.x, check https://github.com/PaddlePaddle/PaddleNLP/pull/3859
