### ISSUE TITLE
[TTS]ERNIE-SAT个性化合成报错

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleSpeech#2752]
**Describe the bug**
`{'code': -1, 'result': None, 'message': 'SAT 合成失败，请从后台检查错误信息！'}`

**To Reproduce**
步骤参考的是[ERNIE-SAT 个性化合成体验](https://aistudio.baidu.com/aistudio/projectdetail/4573549?sUid=2470186&shared=1&ts=1663753541400)

```
url = "http://127.0.0.1:8010/vc/clone_sat"
methods = "post"
para = {
	'old_str': "请播放歌曲小苹果",
	'new_str': "你可以使用我的声音合成其它文本",
	'language': "zh",
	'function': "synthesize",
	'wav': "source/wav/SAT/upload/SSB03540307.wav",
	'filename': "SSB03540307.wav"
}
r = use_api(url, methods, json.dumps(para))
r.json()
```

**Screenshots**
```
/home/envs/paddle_speech_test/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
tmp_name in alignment: root_35741_a75f0b25dd7d6d18b3e60a7c8973819f
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
fstcompile: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
Setting up training data...
Calculating MFCCs...
Calculating CMVN...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
Done with setup.
100%|████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.34it/s]
Done! Everything took 3.393775463104248 seconds
Traceback (most recent call last):
  File "PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 474, in <module>
    task_name=args.task_name)
  File "PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 285, in get_wav
    n_shift=n_shift)
  File "PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 239, in get_mlm_output
    n_shift=n_shift)
  File "PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 175, in prep_feats
    n_shift=n_shift)
  File "PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 74, in prep_feats_with_dur
    n_shift=n_shift)
  File "/home/envs/paddle_speech_test/lib/python3.7/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 217, in get_phns_spans
    wav_path=wav_path, text=old_str, lang=lang, fs=fs, n_shift=n_shift)
  File "/home/envs/paddle_speech_test/lib/python3.7/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 136, in alignment
    phn_dur, word2phns = _readtg(tg_path, lang=lang)
  File "/home/envs/paddle_speech_test/lib/python3.7/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 39, in _readtg
    alignment = textgrid.openTextgrid(tg_path, includeEmptyIntervals=True)
  File "/home/envs/paddle_speech_test/lib/python3.7/site-packages/praatio/textgrid.py", line 70, in openTextgrid
    with io.open(fnFullPath, "r", encoding="utf-16") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_dir/root_35741_a75f0b25dd7d6d18b3e60a7c8973819f/root_35741_a75f0b25dd7d6d18b3e60a7c8973819f/SSB03540307.TextGrid'

            FLAGS_allocator_strategy=naive_best_fit             FLAGS_fraction_of_gpu_memory_to_use=0.01             python3 PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py                 --task_name=synthesize                 --wav_path=PaddleSpeech/demos/speech_web/speech_server/source/wav/SAT/upload/SSB03540307.wav                 --old_str='请播放歌曲小苹果'                 --new_str='你可以使用我的声音合成其它文本'                 --source_ --target_lang=zh                 --erniesat_config=PaddleSpeech/demos/speech_web/speech_server/source/model/erniesat_aishell3_ckpt_1.2.0/default.yaml                 --phones_dict=PaddleSpeech/demos/speech_web/speech_server/source/model/erniesat_aishell3_ckpt_1.2.0/phone_id_map.txt                 --erniesat_ckpt=PaddleSpeech/demos/speech_web/speech_server/source/model/erniesat_aishell3_ckpt_1.2.0/snapshot_iter_289500.pdz                 --erniesat_stat=PaddleSpeech/demos/speech_web/speech_server/source/model/erniesat_aishell3_ckpt_1.2.0/speech_stats.npy                 --voc=hifigan_aishell3                 --voc_config=PaddleSpeech/demos/speech_web/speech_server/source/model/hifigan_aishell3_ckpt_0.2.0/default.yaml                 --voc_ckpt=PaddleSpeech/demos/speech_web/speech_server/source/model/hifigan_aishell3_ckpt_0.2.0/snapshot_iter_2500000.pdz                 --voc_stat=PaddleSpeech/demos/speech_web/speech_server/source/model/hifigan_aishell3_ckpt_0.2.0/feats_stats.npy                 --output_name=PaddleSpeech/demos/speech_web/speech_server/source/wav/SAT/out/sat_syn_zh_SSB03540307.wav                 --ngpu=0
        
运行结果： 1

```

**Environment (please complete the following information):**
 - OS: Redhat
 - GCC/G++ Version: 4.8.5
 - Python Version: 3.7.10
 - PaddlePaddle Version: 2.4.1

**Comment by wjddd** [comment]
@iftaken 请问这个有什么方法可以解决？

**Comment by iftaken** [comment]
这里的报错是由于MFA环境不对引起的
> fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)

你切换成 Ubuntu 20.04 的系统或者对应的docker，如果你有root权限的话，可以尝试更新GLIBC, 可以参考这篇[【`GLIBC_2.23‘ not found问题解决】](https://blog.csdn.net/qq_50665031/article/details/108987205)

**Comment by wjddd** [comment]
> 这里的报错是由于MFA环境不对引起的
> 
> > fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
> 
> 你切换成 Ubuntu 20.04 的系统或者对应的docker，如果你有root权限的话，可以尝试更新GLIBC, 可以参考这篇[【`GLIBC_2.23‘ not found问题解决】](https://blog.csdn.net/qq_50665031/article/details/108987205)

谢谢，通过升级glibc解决了~
