### ISSUE TITLE
（arm平台）流式语音识别服务启动和被调用时报错（启动：[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error ；被调用：tensor  has not been initialized），识别出的文字都为空

### ISSUE THREAD

**Issue by LangJiHuangSha** [PaddlePaddle/PaddleSpeech#2762]
## linux系统版本
Linux localhost.localdomain 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
## 根据这个页面操作 
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/streaming_asr_server/README_cn.md
## 启动服务命令
paddlespeech_server start --config_file ./conf/ws_conformer_wenetspeech_application.yaml
### 日志
/usr/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
[2022-12-23 14:13:20,290] [    INFO] - start to init the engine
[2022-12-23 14:13:20,290] [    INFO] - asr : online engine.
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement paddlespeech_ctcdecoders (from versions: none)
ERROR: No matching distribution found for paddlespeech_ctcdecoders
2022-12-23 14:13:28.724 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
2022-12-23 14:13:39.032 | INFO     | paddlespeech.s2t.modules.embedding:__init__:150 - max len: 5000
[2022-12-23 14:13:44,891] [    INFO] - Initialize ASR server engine successfully on device: cpu.
INFO:     Started server process [77126]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)

## 调用服务命令
paddlespeech_client asr_online --server_ip 127.0.0.1 --port 8090 --input ../../../zh.wav
### 服务端日志
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
1   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor  has not been initialized, we can only slice initialized tensor please init it first with numpy or other tensor.
  [Hint: Expected self->tensor.initialized() == true, but received self->tensor.initialized():0 != true:1.] (at /workspace/paddleocr/Paddle/paddle/fluid/pybind/eager_method.cc:768)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "<decorator-gen-600>", line 2, in advance_decoding
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 356, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 483, in advance_decoding
    cnn_cache=self.cnn_cache)
  File "/usr/local/lib/python3.7/site-packages/paddlespeech/s2t/modules/encoder.py", line 254, in forward_chunk
    att_cache=att_cache[i:i + 1],
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 753, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: 
### 客户端日志
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
[2022-12-23 13:52:26,614] [    INFO] - asr websocket client start
[2022-12-23 13:52:26,615] [    INFO] - endpoint: None
[2022-12-23 13:52:26,615] [    INFO] - endpoint: ws://127.0.0.1:8090/paddlespeech/asr/streaming
[2022-12-23 13:52:26,695] [    INFO] - client receive msg={"status": "ok", "signal": "server_ready"}
[2022-12-23 13:52:26,738] [    INFO] - client receive msg={'result': ''}
[2022-12-23 13:52:26,752] [    INFO] - client receive msg={'result': ''}
... 后面一直是空文本，但音频文件实际上时由内容的

**Comment by zxcd** [comment]
please try:

> pip install paddlespeech_ctcdecoders

**Comment by zh794390558** [comment]
使用最新的代码，确认下是否是网络下载问题。另外最好找ubuntu 16.04 的linux机器测试下，排除环境问题。

**Comment by LangJiHuangSha** [comment]
> 请尝试：
> 
> > 点安装paddlespeech_ctcdecoders

没有匹配版本paddlespeech_ctcdecoders（这个错误曾在启动服务的日志里面出现过）
![image](https://user-images.githubusercontent.com/100844589/211274180-44df9bb5-b2ca-4696-a144-463b12f7f97b.png)


> 使用最新的代码，确认下是否是网络下载问题。另外最好找Ubuntu 16.04 的Linux机器测试下，排除环境问题。

嗯嗯，我先用ubuntu 16.04 的linux机器测试下

**Comment by LangJiHuangSha** [comment]
> > 请尝试：
> > > 点安装paddlespeech_ctcdecoders
> 
> 没有匹配版本paddlespeech_ctcdecoders（这个错误曾在启动服务的日志里面出现过） ![image](https://user-images.githubusercontent.com/100844589/211274180-44df9bb5-b2ca-4696-a144-463b12f7f97b.png)
> 
> > 使用最新的代码，确认下是否是网络下载问题。另外最好找Ubuntu 16.04 的Linux机器测试下，排除环境问题。
> 
> 嗯嗯，我先用ubuntu 16.04 的linux机器测试下



> 使用最新的代码，确认下是否是网络下载问题。另外最好找ubuntu 16.04 的linux机器测试下，排除环境问题。

我这边暂时没有ubuntu 16.04 的linux机器，用官方docker镜像测了一下是可以的，那估计是环境的问题了

然后我测了好多遍，报错主要是下面这些： 
[2023-01-10 10:16:24,447] [    INFO] - Online ASR extract the feat
[2023-01-10 10:16:24,456] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-01-10 10:16:24,456] [    INFO] - start to do model forward
[2023-01-10 10:16:24,623] [   ERROR] - 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
1   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor  has not been initialized, we can only slice initialized tensor please init it first with numpy or other tensor.
  [Hint: Expected self->tensor.initialized() == true, but received self->tensor.initialized():0 != true:1.] (at /workspace/paddleocr/Paddle/paddle/fluid/pybind/eager_method.cc:768)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "<decorator-gen-603>", line 2, in advance_decoding
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 356, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 483, in advance_decoding
    cnn_cache=self.cnn_cache)
  File "/usr/local/lib/python3.7/site-packages/paddlespeech/s2t/modules/encoder.py", line 254, in forward_chunk
    att_cache=att_cache[i:i + 1],
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 753, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
1   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor  has not been initialized, we can only slice initialized tensor please init it first with numpy or other tensor.
  [Hint: Expected self->tensor.initialized() == true, but received self->tensor.initialized():0 != true:1.] (at /workspace/paddleocr/Paddle/paddle/fluid/pybind/eager_method.cc:768)

**Comment by zh794390558** [comment]
看之前的log是网络问题，先把下载的模型删掉。再重新试下。
