### ISSUE TITLE
File "/root/anaconda3/envs/rpa/lib/python3.8/site-packages/yacs/config.py", line 141, in getattr raise AttributeError(name) AttributeError: preprocess_config

### ISSUE THREAD

**Issue by shumeirao** [PaddlePaddle/PaddleSpeech#2775]
跑脚本代码为： 
```bash
CUDA_VISIBLE_DEVICES=1 ./local/test_wav.sh conf/deepspeech2.yaml conf/tuning/decode.yaml exp/deepspeech2/checkpoints/avg_1 data/demo_01_03.wav，
```
报的错为：

Traceback (most recent call last):   File "/data/rshm/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py", line 201, in <module>     main(config, args)   File "/data/rshm/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py", line 169, in main     main_sp(config, args)   File "/data/rshm/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py", line 163, in main_sp     exp = DeepSpeech2Tester_hub(config, args)   File "/data/rshm/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py", line 42, in __init__     self.preprocess_conf = config.preprocess_config   File "/root/anaconda3/envs/rpa/lib/python3.8/site-packages/yacs/config.py", line 141, in __getattr__     raise AttributeError(name) AttributeError: preprocess_config

**Comment by zxcd** [comment]
可以查一下conf/deepspeech2.yaml 中是否有preprocess_config参数
