### ISSUE TITLE
TypeError: declarative() got an unexpected keyword argument 'property'

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleSpeech#2848]
代码：
from paddlespeech.cli.asr.infer import ASRExecutor
asr = ASRExecutor()
result = asr(audio_file="zh.wav")
print(result)

环境：
windows
cuda 11.0 cudnn7
paddlepaddle-gpu 2.3.2
paddlespeech 1.3.0

报错：

C:\Users\14548\Anaconda3\envs\paddlespeech\python.exe D:/PycharmProjects/Projects/SpeechRecognition/test/main.py
C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
100%|██████████| 487739/487739 [00:20<00:00, 23841.41it/s]
C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
W0128 15:06:29.214216 34136 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.0
W0128 15:06:29.221197 34136 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
2023-01-28 15:06:29.211 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
Traceback (most recent call last):
  File "D:/PycharmProjects/Projects/SpeechRecognition/test/main.py", line 3, in <module>
    result = asr(audio_file="./data/zh.wav")
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\cli\utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\cli\asr\infer.py", line 489, in __call__
    num_decoding_left_chunks, ckpt_path)
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\cli\asr\infer.py", line 199, in _init_from_path
    model_class = self.task_resource.get_model_class(model_name)
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\resource\resource.py", line 115, in get_model_class
    ret.append(dynamic_import(import_path))
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\utils\dynamic_import.py", line 37, in dynamic_import
    m = importlib.import_module(module_name)
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\s2t\models\u2\__init__.py", line 14, in <module>
    from .u2 import U2InferModel
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\s2t\models\u2\u2.py", line 65, in <module>
    class U2BaseModel(ASRInterface, nn.Layer):
  File "C:\Users\14548\Anaconda3\envs\paddlespeech\lib\site-packages\paddlespeech\s2t\models\u2\u2.py", line 611, in U2BaseModel
    @jit.to_static(property=True)
TypeError: declarative() got an unexpected keyword argument 'property'

Process finished with exit code 1

**Comment by zxcd** [comment]
Duplicate with https://github.com/PaddlePaddle/PaddleSpeech/issues/2512
