### ISSUE TITLE
[TTS]  使用ERNIE-SAT克隆语音时，No such file or directory: *.TextGrid'

### ISSUE THREAD

**Issue by 13604099691** [PaddlePaddle/PaddleSpeech#2878]
sh: 1: mfa_align: not found
tg_path:  tmp_dir/shang_12352_a75f0b25dd7d6d18b3e60a7c8973819f/shang_12352_a75f0b25dd7d6d18b3e60a7c8973819f/SSB03540307.TextGrid
Traceback (most recent call last):
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 469, in <module>
    wav_dict = get_wav(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 277, in get_wav
    outs = get_mlm_output(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 231, in get_mlm_output
    prep_feats_outs = prep_feats(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 167, in prep_feats
    with_dur_outs = prep_feats_with_dur(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 67, in prep_feats_with_dur
    phns_spans_outs = get_phns_spans(
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 219, in get_phns_spans
    phn, dur, w2p = alignment(
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 138, in alignment
    phn_dur, word2phns = _readtg(tg_path, lang=lang)
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 40, in _readtg
    alignment = textgrid.openTextgrid(tg_path, includeEmptyIntervals=True)
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/praatio/textgrid.py", line 72, in openTextgrid
    with io.open(fnFullPath, "r", encoding="utf-16") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_dir/shang_12352_a75f0b25dd7d6d18b3e60a7c8973819f/shang_12352_a75f0b25dd7d6d18b3e60a7c8973819f/SSB03540307.TextGrid'

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu20.04]
 - GCC/G++ Version [e.g. 5]
 - Python Version [e.g. 3.8]
 - PaddlePaddle Version [e.g. 2.0.0]
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Informationo [e.g. 3090-24GB]
 - CUDA/CUDNN Version [e.g. cuda-11.6]
 - MKL Version
- TensorRT Version

**Additional context**

**Comment by yt605155624** [comment]
报错是
```bash
sh: 1: mfa_align: not found
```
看看是不是没有按照 readme 配置好 MFA

**Comment by 13604099691** [comment]
> 报错是
> 
> ```shell
> sh: 1: mfa_align: not found
> ```
> 
> 看看是不是没有按照 readme 配置好 MFA

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install.md
请问MFA的配置步骤是在哪里，我在这里并没有看到MFA的相关配置步骤

**Comment by yt605155624** [comment]
你跑 ERNIE-SAT 自然是要看 ERNIE-SAT 的 readme https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3_vctk/ernie_sat

**Comment by 13604099691** [comment]
> 

W0206 14:06:44.218667 30680 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W0206 14:06:44.221520 30680 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
tmp_name in alignment: shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
/home/shang/python/PaddleSpeech/demos/speech_web/speech_server/tools/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Calculating CMVN...
Number of speakers in corpus: 1, average number of utterances per speaker: 1.0
Done with setup.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.28it/s]
Done! Everything took 1.6172871589660645 seconds
tg_path:  tmp_dir/shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f/shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f/SSB03540307.TextGrid
Traceback (most recent call last):
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 469, in <module>
    wav_dict = get_wav(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 277, in get_wav
    outs = get_mlm_output(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 231, in get_mlm_output
    prep_feats_outs = prep_feats(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 167, in prep_feats
    with_dur_outs = prep_feats_with_dur(
  File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 67, in prep_feats_with_dur
    phns_spans_outs = get_phns_spans(
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 219, in get_phns_spans
    phn, dur, w2p = alignment(
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 138, in alignment
    phn_dur, word2phns = _readtg(tg_path, lang=lang)
  File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 45, in _readtg
    for interval in alignment.tierDict['words'].entryList:
AttributeError: 'Textgrid' object has no attribute 'tierDict'
MFA装好了，现在报这个错了

**Comment by 13604099691** [comment]
> 你跑 ERNIE-SAT 自然是要看 ERNIE-SAT 的 readme https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3_vctk/ernie_sat

tg_path: tmp_dir/shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f/shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f/SSB03540307.TextGrid
Traceback (most recent call last):
File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 469, in
wav_dict = get_wav(
File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 277, in get_wav
outs = get_mlm_output(
File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 231, in get_mlm_output
prep_feats_outs = prep_feats(
File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 167, in prep_feats
with_dur_outs = prep_feats_with_dur(
File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 67, in prep_feats_with_dur
phns_spans_outs = get_phns_spans(
File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 219, in get_phns_spans
phn, dur, w2p = alignment(
File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 138, in alignment
phn_dur, word2phns = _readtg(tg_path, lang=lang)
File "/home/shang/anaconda3/envs/TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py", line 45, in _readtg
for interval in alignment.tierDict['words'].entryList:
AttributeError: 'Textgrid' object has no attribute 'tierDict'

请问  出现这个现象的原因是什么呢

**Comment by 13604099691** [comment]
> > 你跑 ERNIE-SAT 当然是要看 ERNIE-SAT 的自述文件https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3_vctk/ernie_sat
> 
> tg_path: tmp_dir/shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f/shang_30680_a75f0b25dd7d6d18b3e60a7c8973819f/SSB03540307.TextGrid Traceback (most recent call last): File "/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py", line 469, in wav_dict = get_wav （ 文件“/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py”，第 277 行，在 get_wav outs = get_mlm_output（ 文件“/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps /ernie_sat/synthesize_e2e.py”，第 231 行，在 get_mlm_output prep_feats_outs = prep_feats( 文件“/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py”，第 167 行，在 prep_feats with_dur_outs = prep_feats_with_dur( 文件“/home/shang/python/PaddleSpeech/paddlespeech/t2s/exps/ernie_sat/synthesize_e2e.py”，第 67 行，在 prep_feats_with_dur phns_spans_outs = get_phns_spans( 文件“/home/shang/anaconda3/envs/TTS3.8/lib/ python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py”，第 219 行，在 get_phns_spans phn, dur, w2p = alignment( File "/home/shang/anaconda3/envs/TTS3.8/lib /python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py”，第 138 行，对齐 phn_dur，word2phns = _readtg(tg_path，lang=lang) 文件“/home/shang/anaconda3/envs/ TTS3.8/lib/python3.8/site-packages/paddlespeech/t2s/exps/ernie_sat/align.py”，第 45 行，在 _readtg 中用于 alignment.tierDict['words'].entryList 中的间隔： AttributeError: 'Textgrid' 对象没有属性 'tierDict'
> 
> 请问出现这个现象的原因是什么呢

改成Python3.7版本已解决！
