### ISSUE TITLE
ASR训练u2++模型的时候报错

### ISSUE THREAD

**Issue by upcmb** [PaddlePaddle/PaddleSpeech#2903]
感觉把manifest.train里面的内容作为路径去读取了....

**错误详情**
2023-02-09 11:36:33.600 | INFO     | paddlespeech.s2t.training.trainer:resume_or_scratch:221 - Init from scratch!
2023-02-09 11:36:37.840 | INFO     | paddlespeech.s2t.utils.checkpoint:_save_parameters:286 - Saved model to exp/chunk_conformer_u2pp/checkpoints/init.pdparams
2023-02-09 11:36:37.841 | INFO     | paddlespeech.s2t.utils.checkpoint:_save_parameters:292 - Saved optimzier state to exp/chunk_conformer_u2pp/checkpoints/init.pdopt
[2023-02-09 11:36:38,409] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:0
[2023-02-09 11:36:38,410] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:1
[2023-02-09 11:36:38,410] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:3
[2023-02-09 11:36:38,410] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:2
[2023-02-09 11:36:38,410] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:4
[2023-02-09 11:36:38,411] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:5
[2023-02-09 11:36:38,411] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:6
[2023-02-09 11:36:38,411] [    INFO] - paddlespeech.audio.streamdata.shardlists | num_workers:8, worker:7
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 674, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 172, in reraise
    raise self.exc_type(msg)
FileNotFoundError: DataLoader worker(5) caught FileNotFoundError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 339, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 107, in fetch
    data = next(self.dataset_iter)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/pipeline.py", line 67, in iterator
    for sample in self.iterator1():
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 990, in _audio_cmvn
    for batch in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 962, in _audio_padding
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 912, in _batched
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 885, in _sort
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 218, in _shuffle
    for sample in data:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 847, in _audio_spec_aug
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 791, in _audio_compute_fbank
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 756, in _audio_resample
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 653, in _audio_data_filter
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/filters.py", line 706, in _audio_tokenize
    for sample in source:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/tariterators.py", line 221, in tar_file_and_group_expander
    for source in data:
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/tariterators.py", line 79, in url_opener
    if handler(exn):
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/handlers.py", line 22, in reraise_exception
    raise exn
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/tariterators.py", line 74, in url_opener
    stream = gopen.gopen(url, **kw)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/audio/streamdata/gopen.py", line 315, in gopen
    return open(url, mode, buffering=bufsize)
FileNotFoundError: [Errno 2] No such file or directory: '{"input": [{"name": "input1", "shape": [1.28, 80], "feat": "/home/aistudio/work/PaddleSpeech/dataset/tal_cs/TALCS_corpus/train_set/wav/308c413eea021d9f4c12bd2f910be944.wav", "filetype": "sound"}], "output": [{"name": "target1", "shape": [1, 29], "text": "o", "token": "o", "tokenid": "16"}], "utt": "308c413eea021d9f4c12bd2f910be944", "utt2spk": "308c413eea021d9f4c12bd2f910be944"}'
**配置：chunk_conformer_u2pp.yaml**
############################################
#           Network Architecture           #
############################################
cmvn_file: "data/mean_std.json"
cmvn_file_type: "json"
# encoder related
encoder: conformer
encoder_conf:
    output_size: 512    # dimension of attention
    attention_heads: 8
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: True
    use_cnn_module: True
    cnn_module_kernel: 15
    activation_type: swish
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    causal: true
    use_dynamic_chunk: true
    cnn_module_norm: 'layer_norm' # using nn.LayerNorm makes model converge faster
    use_dynamic_left_chunk: false
# decoder related
decoder: bitransformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 3     # the number of encoder blocks
    r_num_blocks: 3   #only for bitransformer
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false
    reverse_weight: 0.3    # only for bitransformer decoder
    init_type: 'kaiming_uniform' # !Warning: need to convergence

###########################################
#                   Data                  #
###########################################
train_manifest: data/manifest.train
dev_manifest: data/manifest.dev
test_manifest: data/manifest.test

###########################################
#              Dataloader                 #
###########################################
use_stream_data: True
vocab_filepath: data/lang_char/vocab.txt 
unit_type: 'char'
preprocess_config: conf/preprocess.yaml
spm_model_prefix: ''
feat_dim: 80
stride_ms: 10.0
window_ms: 25.0
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs 
batch_size: 32
do_filter: True
dither: 0.1
resample_rate: 16000
maxlen_in: 1200  # if do_filter == False && input length  > maxlen-in, batchsize is automatically reduced
maxlen_out: 100  # if do_filter == False && output length > maxlen-out, batchsize is automatically reduced
minlen_in: 10
minlen_out: 0
minibatches: 0 # for debug
batch_count: auto
batch_bins: 0 
batch_frames_in: 0
batch_frames_out: 0
batch_frames_inout: 0
subsampling_factor: 1
num_encs: 1
shuffle_size: 1500 # read number of 'shuffle_size' data as a chunk, shuffle the data in the chunk
sort_size: 1000  # read number of 'sort_size' data as a chunk, sort the data in the chunk 
num_workers: 8
prefetch_factor: 10

###########################################
#                 Training                #
###########################################
n_epoch: 150 
accum_grad: 8
global_grad_clip: 5.0
dist_sampler: False
optim: adam
optim_conf:
  lr: 0.002
  weight_decay: 1.0e-6
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
  lr_decay: 1.0
log_interval: 100
checkpoint:
  kbest_n: 50
  latest_n: 5
**chunk_decode.yaml 配置**
beam_size: 10
decoding_method: attention # 'attention', 'ctc_greedy_search', 'ctc_prefix_beam_search', 'attention_rescoring'
ctc_weight: 0.5 # ctc weight for attention rescoring decode mode.
reverse_weight: 0.3 # reverse weight for attention rescoring decode mode.
decoding_chunk_size: 16 # decoding chunk size. Defaults to -1.
    # <0: for decoding, use full chunk.
    # >0: for decoding, use fixed chunk size as set.
    # 0: used for training, it's prohibited here. 
num_decoding_left_chunks: -1  # number of left chunks for decoding. Defaults to -1.
simulate_streaming: True  # simulate streaming inference. Defaults to False.
decode_batch_size: 128
error_rate_type: cer

**Comment by zxcd** [comment]
确认一下你用的是不是最新的develop代码

**Comment by upcmb** [comment]
> 确认一下你用的是不是最新的develop代码

是的，最新的develop代码。

**Comment by zxcd** [comment]
这个模型不能这么直接替换成chunk_conformer_u2pp.yaml，你现在使用的conf包括建模单元、数据处理和dataloader都不太一致。如果非要这么用你可以自己尝试修改一下。

**Comment by upcmb** [comment]
> 这个模型不能这么直接替换成chunk_conformer_u2pp.yaml，你现在使用的conf包括建模单元、数据处理和dataloader都不太一致。如果非要这么用你可以自己尝试修改一下。

@zxcd 我是用 examples/wenetspeech/asr1 下的这个配置：chunk_conformer_u2pp.yaml，现在没有别的U2++模型的配置可以参考，如何修改才能算是正确的配置方式？

**Comment by zxcd** [comment]
你现在是想使用自己的数据从头开始，还是想接着我们开出来tal_cs的模型使用自己的数据finetune?

**Comment by upcmb** [comment]
> 你现在是想使用自己的数据从头开始，还是想接着我们开出来tal_cs的模型使用自己的数据finetune?

这两种方式有多大的不同？
我们想用自己的数据从头开始先训练一个简单模型，作为测试用，测试可行的后，最终是想用预训练的模型的基础上，再用自己的数据finetune。

**Comment by zxcd** [comment]
由于我们目前开源的是u2模型，如果预想是模型finetune的话，建议直接使用tal_cs中的config，不然模型结构无法匹配。

**Comment by upcmb** [comment]
@zxcd  你好，如何在tal_cs的模型使用自己的数据finetune? 可有详细的步骤？

**Comment by zxcd** [comment]
> @zxcd 你好，如何在tal_cs的模型使用自己的数据finetune? 可有详细的步骤？

可以参考https://github.com/PaddlePaddle/PaddleSpeech/discussions/1972
