### ISSUE TITLE
[Install] gpu版本安装成功，运行报错

### ISSUE THREAD

**Issue by yeapllg** [PaddlePaddle/PaddleSpeech#2905]
gpu：4080（公版）
cuda版本：12.0
具体如下：
Thu Feb  9 22:03:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:83:00.0 Off |                  N/A |
| 30%   26C    P0    32W / 320W |      0MiB / 16376MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:12:58_PDT_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0

#define CUDNN_MAJOR 8
#define CUDNN_MINOR 8
#define CUDNN_PATCHLEVEL 0
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

/* cannot use constexpr here since this is a C-only file */

paddlepaddle                   2.4.1
paddlespeech                   1.0.1

运行后报如下错误：
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/yeapllg/video/test.py", line 72, in <module>
    from paddlespeech.cli.tts.infer import TTSExecutor
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .asr import ASRExecutor
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/cli/asr/infer.py", line 24, in <module>
    import paddle
  File "/usr/local/lib/python3.10/dist-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

提示libcudart.so.10.2这包没有

经过检查发现，cuda12.0版本的libcudart.so包版本为libcudart.so.12,

root@ubuntu:/home/yeapllg/video# ls /usr/local/cuda/lib64/libcudart*
/usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libcudart.so.12  /usr/local/cuda/lib64/libcudart.so.12.0.107  /usr/local/cuda/lib64/libcudart_static.a

**Comment by yt605155624** [comment]
paddle 安装问题请移步 paddle issue 区

**Comment by yaleimeng** [comment]
我前面在Ubuntu22.04试过，python3.10版本似乎有问题。你换3.9或3.8版本应该就没问题了
PS：CUDA 12.0版本似乎太新了吧，paddlepaddle底层支持了吗？似乎暂时还是最高11.7啊  [参考页面](https://www.paddlepaddle.org.cn/install/quick)

**Comment by angiewlz** [comment]
运行时报错：ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by angiewlz** [comment]
运行：paddlespeech vector --task spk --input zh.wav
报错：ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
