### ISSUE TITLE
docker版本paddlespeech-cpu运行demo报错

### ISSUE THREAD

**Issue by fuguohong1024** [PaddlePaddle/PaddleSpeech#2926]
```shell
1. pull images
docker pull paddlecloud/paddlespeech:develop-cpu-bb7f2a
2. run 参照https://hub.docker.com/r/paddlecloud/paddlespeech
docker run --name dev -v $PWD:/mnt -p 8888:8888 -it docker.io/paddlecloud/paddlespeech:develop-cpu-bb7f2a  /bin/bash
3. cd demo dir
cd /home/PaddleSpeech/demos/speaker_verification
4. run
 ./run.sh
--2023-02-11 08:59:56--  https://paddlespeech.bj.bcebos.com/vector/audio/85236145389.wav
Resolving paddlespeech.bj.bcebos.com (paddlespeech.bj.bcebos.com)... 220.181.33.44, 2409:8c04:1001:1002:0:ff:b001:368a
Connecting to paddlespeech.bj.bcebos.com (paddlespeech.bj.bcebos.com)|220.181.33.44|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-02-11 08:59:57--  https://paddlespeech.bj.bcebos.com/vector/audio/123456789.wav
Resolving paddlespeech.bj.bcebos.com (paddlespeech.bj.bcebos.com)... 220.181.33.44, 2409:8c04:1001:1002:0:ff:b001:368a
Connecting to paddlespeech.bj.bcebos.com (paddlespeech.bj.bcebos.com)|220.181.33.44|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/base_commands.py", line 19, in <module>
    from ..resource import CommonTaskResource
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/utils.py", line 28, in <module>
    import soundfile as sf
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/base_commands.py", line 19, in <module>
    from ..resource import CommonTaskResource
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/utils.py", line 28, in <module>
    import soundfile as sf
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

**Comment by fuguohong1024** [comment]
docker engine版本19.03.4
CentOS Linux release 7.6.1810 (Core)

**Comment by yt605155624** [comment]
```bash
sudo apt-get install libsndfile1
```
