### ISSUE TITLE
 nvidia Jetson Xavier NX 平台上 paddlespeech安装报错，pyworld报错

### ISSUE THREAD

**Issue by geekplusaa** [PaddlePaddle/PaddleSpeech#2930]
nvidia Jetson Xavier NX 平台上 paddlespeech安装不上，用 pip install paddlespeech 安装不上。是否可以提供一个编译好的 aarch64 的包。依赖的paddlepaddle版本是2.3.2

我执行的命令是 pip install paddlespeech

**环境:**
 - OS: Jetson Xavier NX 
 - jp:4.6.1
 - Python Version 3.7
 - PaddlePaddle Version 2.3.2
 - CUDA/CUDNN Version 10.2
- TensorRT 7.0

**Comment by lizezheng** [comment]
贴一下报错相关log？

**Comment by geekplusaa** [comment]
(speech) nvidia@nvidia-desktop:~$ pip install paddlespeech
Collecting paddlespeech
  Using cached paddlespeech-1.3.0-py3-none-any.whl (1.4 MB)
Collecting kaldiio
  Using cached kaldiio-2.17.2.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting braceexpand
  Using cached braceexpand-0.1.7-py2.py3-none-any.whl (5.9 kB)
Requirement already satisfied: soundfile~=0.10 in ./.local/lib/python3.7/site-packages (from paddlespeech) (0.11.0)
Requirement already satisfied: tqdm in ./.local/lib/python3.7/site-packages (from paddlespeech) (4.64.1)
Requirement already satisfied: Pillow>=9.0.0 in ./.local/lib/python3.7/site-packages (from paddlespeech) (9.4.0)
Collecting nara-wpe
  Using cached nara_wpe-0.0.9-py3-none-any.whl (33 kB)
Requirement already satisfied: jieba in ./.local/lib/python3.7/site-packages (from paddlespeech) (0.42.1)
Collecting g2pM
  Using cached g2pM-0.1.2.5-py3-none-any.whl (1.7 MB)
Collecting pyworld==0.2.12
  Using cached pyworld-0.2.12.tar.gz (222 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [143 lines of output]
        WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facb5a750>: Failed to establish a new connection: [Errno -2] Name or service not known')': /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
        WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facb5aa90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
        WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facb5a990>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
        WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
        WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facbd0150>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
      ERROR: Exception:
      Traceback (most recent call last):
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 175, in _new_conn
          (self._dns_host, self.port), self.timeout, **extra_kw
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/util/connection.py", line 95, in create_connection
          raise err
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/util/connection.py", line 85, in create_connection
          sock.connect(sa)
      OSError: [Errno 101] Network is unreachable
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 710, in urlopen
          chunked=chunked,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 386, in _make_request
          self._validate_conn(conn)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 1042, in _validate_conn
          conn.connect()
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 358, in connect
          self.sock = conn = self._new_conn()
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 187, in _new_conn
          self, "Failed to establish a new connection: %s" % e
      pip._vendor.urllib3.exceptions.NewConnectionError: <pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facbd0450>: Failed to establish a new connection: [Errno 101] Network is unreachable
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/requests/adapters.py", line 499, in send
          timeout=timeout,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 828, in urlopen
          **response_kw
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 828, in urlopen
          **response_kw
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 828, in urlopen
          **response_kw
        [Previous line repeated 2 more times]
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 788, in urlopen
          method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/util/retry.py", line 592, in increment
          raise MaxRetryError(_pool, url, error or ResponseError(cause))
      pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facbd0450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
          status = run_func(*args)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/commands/wheel.py", line 170, in run
          requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
          collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
          version=version,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
          version=version,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
          self.dist = self._prepare()
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
          dist = self._prepare_distribution()
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 542, in _prepare_linked_requirement
          hashes,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 170, in unpack_url
          hashes=hashes,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
          from_path, content_type = download(link, temp_dir.path)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/network/download.py", line 134, in __call__
          resp = _http_get_download(self._session, link)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/network/download.py", line 117, in _http_get_download
          resp = session.get(target_url, headers=HEADERS, stream=True)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 600, in get
          return self.request("GET", url, **kwargs)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_internal/network/session.py", line 518, in request
          return super().request(method, url, *args, **kwargs)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 587, in request
          resp = self.send(prep, **send_kwargs)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 701, in send
          r = adapter.send(request, **kwargs)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 57, in send
          resp = super(CacheControlAdapter, self).send(request, **kw)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/requests/adapters.py", line 565, in send
          raise ConnectionError(e, request=request)
      pip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b7/0d/86662f93102e42545cdf031da4fddf0ace9030ec67478932a628afc5973b/numpy-1.21.6-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7facbd0450>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
      /home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/dist.py:773: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        % (opt, underscore_opt)
      /home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      Traceback (most recent call last):
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/nvidia/anaconda3/envs/speech/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp65i6cg8n', '--quiet', 'numpy']' returned non-zero exit status 2.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d_n8_k0b/pyworld_7f154c3cf3e0417b9de8d9c93b3037a0/setup.py", line 66, in <module>
          classifiers=[],
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/dist.py", line 877, in fetch_build_eggs
          replace_conflicting=True,
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
          replace_conflicting=replace_conflicting
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/nvidia/anaconda3/envs/speech/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp65i6cg8n', '--quiet', 'numpy']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by lizezheng** [comment]
看着像是 subprocess 中安装依赖 网络有问题？你 pip 一下看看 pyworld装上没有

**Comment by geekplusaa** [comment]
> 看着像是 subprocess 中安装依赖 网络有问题？你 pip 一下看看 pyworld装上没有

pyworld没有安装成功。 应该就是这个包的问题。

**Comment by lizezheng** [comment]
File "/home/nvidia/anaconda3/envs/speech/lib/python3.7/site-packages/pip/_vendor/urllib3/util/connection.py", line 85, in create_connection
sock.connect(sa)
OSError: [Errno 101] Network is unreachable  换个国内 pip 源试试

**Comment by sunqb** [comment]
> pyworld

pyworld安装不上，确实是这个问题，换了国内源也一样报同样的错误
