### ISSUE TITLE
[TTS]tts3_rhy韵律预测报错 AttributeError: 'ErnieForTokenClassification' object has no attribute 'num_labels'

### ISSUE THREAD

**Issue by Zz-ww** [PaddlePaddle/PaddleSpeech#2951]
说明文档中没有要求paddlenlp的版本要求，我使用paddlenlp==2.3.0和2.2.5版本都出现了，PaddleSpeech/examples/csmsc/tts3_rhy下synthesize_e2e.sh的推理都存在报错。报错信息如下：

Traceback (most recent call last):
  File "/home/aaa/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 281, in <module>
    main()
  File "/home/aaa/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 277, in main
    evaluate(args)
  File "/home/aaa/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 50, in evaluate
    frontend = get_frontend(
  File "/home/aaa/PaddleSpeech/paddlespeech/t2s/exps/syn_utils.py", line 266, in get_frontend
    frontend = Frontend(
  File "/home/aaa/PaddleSpeech/paddlespeech/t2s/frontend/zh_frontend.py", line 113, in __init__
    self.rhy_predictor = RhyPredictor()
  File "/home/aaa/PaddleSpeech/paddlespeech/t2s/frontend/rhy_prediction/rhy_predictor.py", line 48, in __init__
    self.model = DefinedClassifier["ErnieLinear"](**config["model"])
  File "/home/aaa/PaddleSpeech/paddlespeech/text/models/ernie_linear/ernie_linear.py", line 48, in __init__
    self.num_classes = self.ernie.num_labels
  File "/home/aaa/anaconda3/envs/paddlespeech/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1123, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieForTokenClassification' object has no attribute 'num_labels'

升级paddlenlp==2.5.0，这个报错消失，能正常推理。

**Comment by yt605155624** [comment]
是的，这是 paddlenlp 的一个不兼容升级导致的，paddlenlp 2.4.8 应该也行
