### ISSUE TITLE
example中的csmsc数据集的voc5的train.sh的问题

### ISSUE THREAD

**Issue by wrz1999** [PaddlePaddle/PaddleSpeech#2961]
Traceback (most recent call last):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 674, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 172, in reraise
    raise self.exc_type(msg)
FileNotFoundError: DataLoader worker(0) caught FileNotFoundError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 339, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/datasets/data_table.py", line 118, in __getitem__
    example = self._convert(meta_datum)
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/datasets/data_table.py", line 100, in _convert
    converted_field = converter(meta_datum_field)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/aistudio/data/PaddleSpeech/examples/csmsc/voc5/dump/train/norm/001271_wave.npy'

  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 108, in update
    batch = self.read_batch()
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 178, in read_batch
    batch = next(self.train_iterator)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
    self._reader.read_next_list()[0])
Trainer extensions will try to handle the extension. Then all extensions will finalize.Traceback (most recent call last):
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 274, in <module>
    main()
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 270, in main
    train_sp(args, config)
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 239, in train_sp
    trainer.run()
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 198, in run
    six.reraise(*exc_info)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 108, in update
    batch = self.read_batch()
  File "/home/aistudio/work/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 178, in read_batch
    batch = next(self.train_iterator)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
    self._reader.read_next_list()[0])
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:175)
运行stage1时候报这个错误是为什么?

**Comment by yt605155624** [comment]
报错如下
```text
FileNotFoundError: DataLoader worker(0) caught FileNotFoundError with message:
```
检查下是不是数据预处理没有成功执行
