### ISSUE TITLE
Python3.9.13  安装paddle失败

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleSpeech#3001]
## General Question

然后发现这个库自2011年就没再更新过了，为什么要依赖这么古老的一个库

**Comment by Matiz7** [comment]
PS D:\src> pip install paddle
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ada\AppData\Local\Temp\pip-install-bpajl1_u\paddle_cf72afa194a64a4391ea23755418bbd7\setup.py", line 3, in <module>
          import paddle
        File "C:\Users\ada\AppData\Local\Temp\pip-install-bpajl1_u\paddle_cf72afa194a64a4391ea23755418bbd7\paddle\__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yt605155624** [comment]
这个问题应该是你自己的环境问题
根据报错，你安装的 paddle 版本是错的，现在 paddle 已经到 2.4.2 了
```text
paddle-1.0.2.tar.gz
```
安装文档参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

paddle 发版的 CI 会测试到 py39 不会有什么问题, 建议以后 paddle 安装问题请移步 https://github.com/PaddlePaddle/Paddle
