### ISSUE TITLE
paddlespeech安装使用问题

### ISSUE THREAD

**Issue by Matiz7** [PaddlePaddle/PaddleSpeech#3011]
Python3.10.9

## General Question
[2023-03-09 15:32:53,123] [ WARNING] warnings.py:109 - D:\Python310\lib\site-packages\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,

Traceback (most recent call last):
  File "D:\src\paddspeech.py", line 19, in <module>
    text = asr_executor(
  File "D:\Python310\lib\site-packages\paddlespeech\cli\utils.py", line 338, in _warpper
    return executor_func(self, *args, **kwargs)
TypeError: ASRExecutor.__call__() got an unexpected keyword argument 'codeswitch'

**Comment by zxcd** [comment]
duplicate with https://github.com/PaddlePaddle/PaddleSpeech/issues/2845
