### ISSUE TITLE
tts_finetune的readme流程执行报错，提示'get mfa result'时'lack of features'是什么原因？

### ISSUE THREAD

**Issue by zhaolibo1989** [PaddlePaddle/PaddleSpeech#3020]
## General Question

简述：
工作目录 `(paddle_env) root@ubuntu-desktop:~/PaddleSpeech/examples/other/tts_finetune/tts3#`
参考tts_finetune的[readme](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tts_finetune/tts3)，测试中文微调。只下载、准备与中文训练（微调）相关的数据。执行`run.sh`后报错。经调试推测问题出在`get mfa result`步骤，但具体原因就找不到了，无奈。

主要日志：
```
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 198.0
...
Setting up training data...
Calculating MFCCs...
Some utterances were ignored due to lack of features, please see /root/Documents/MFA/newdir/logging/corpus.log for more information.
Calculating CMVN...
Number of speakers in corpus: 1, average number of utterances per speaker: 0.0
...
AssertionError: This dataset has no examples
```
数据集中有200条数据，这里第一次能识别到 utterances 的数量为 198，但第二次识别不到。
最终导致`AssertionError`错误。

其他程序运行日志：
```
(paddle_env) root@ubuntu-desktop:~/PaddleSpeech/examples/other/tts_finetune/tts3# ./run.sh
check oov
get mfa result
DEBUG >>> python3 local/get_mfa_result.py --input_dir=./input/csmsc_mini/newdir --mfa_dir=./mfa_result --lang=zh
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 198.0
/root/PaddleSpeech/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Some utterances were ignored due to lack of features, please see /root/Documents/MFA/newdir/logging/corpus.log for more information.
Calculating CMVN...
Number of speakers in corpus: 1, average number of utterances per speaker: 0.0
Done with setup.
100%|#################################################################################################| 2/2 [00:01<00:00,  1.05it/s]
Done! Everything took 8.438562870025635 seconds
generate durations.txt
extract feature
/root/anaconda3/envs/paddle_env/lib/python3.10/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
196 1
100%|██████████████████████████████████████████████████████████████████████████████████████████| 196/196 [00:00<00:00, 18817.58it/s]
Done
Traceback (most recent call last):
  File "/root/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 346, in <module>
    extract_feature(
  File "/root/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 266, in extract_feature
    normalize(speech_scaler, pitch_scaler, energy_scaler, vocab_phones,
  File "/root/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 155, in normalize
    dataset = DataTable(
  File "/root/PaddleSpeech/paddlespeech/t2s/datasets/data_table.py", line 45, in __init__
    assert len(data) > 0, "This dataset has no examples"
AssertionError: This dataset has no examples
```

/root/Documents/MFA/newdir/logging/corpus.log
```
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 198.0
Setting up training data...
The following utterances were ignored due to lack of features: 000001, 000002, 000003, 000004, 000005, 000006, 000007, 000008, 000009, 000010, 000011, 000012, 000013, 000014, 000015, 000016, 000017, 000018, 000019, 000020, 000021, 000022, 000023, 000024, 000025, 000026, 000027, 000028, 000030, 000031, 000032, 000033, 000034, 000035, 000036, 000037, 000038, 000039, 000040, 000041, 000042, 000043, 000044, 000045, 000046, 000047, 000048, 000049, 000050, 000051, 000052, 000053, 000054, 000055, 000056, 000057, 000058, 000059, 000060, 000061, 000062, 000063, 000064, 000065, 000066, 000067, 000068, 000069, 000070, 000071, 000072, 000073, 000074, 000075, 000076, 000077, 000078, 000079, 000080, 000081, 000082, 000083, 000084, 000085, 000086, 000087, 000088, 000089, 000090, 000091, 000092, 000093, 000094, 000095, 000096, 000097, 000098, 000099, 000100, 000101, 000102, 000103, 000104, 000105, 000106, 000107, 000108, 000109, 000110, 000111, 000112, 000113, 000114, 000115, 000116, 000117, 000118, 000119, 000120, 000121, 000122, 000123, 000124, 000125, 000126, 000127, 000128, 000129, 000130, 000131, 000132, 000133, 000134, 000135, 000136, 000137, 000138, 000139, 000140, 000141, 000142, 000143, 000144, 000145, 000146, 000147, 000148, 000149, 000150, 000151, 000152, 000153, 000154, 000155, 000156, 000157, 000158, 000159, 000160, 000161, 000162, 000163, 000164, 000165, 000166, 000167, 000168, 000169, 000170, 000171, 000172, 000173, 000174, 000175, 000176, 000177, 000178, 000179, 000180, 000181, 000182, 000183, 000184, 000185, 000186, 000187, 000188, 000189, 000190, 000191, 000192, 000193, 000194, 000196, 000197, 000198, 000199, 000200.  See relevant logs for more information
Number of speakers in corpus: 1, average number of utterances per speaker: 0.0
```

操作系统： ubuntu 18.04
源码版本： r1.3.0
Python 3.10.9
PaddlePaddle 2.4.1
mfa: binary v1.0.1

**Comment by yt605155624** [comment]
查看下音频格式是否正常吧，一般需要单声道的 16bit 的 wav 文件
如果还是不行，建议直接去 MFA 仓库搜下问题 https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

**Comment by zhaolibo1989** [comment]
> 

我是通过 readme 上指导的命令去下载的，编写这个脚本的人应该不得弄错喔。我正在努力在各种渠道找原因。。。

**Comment by zhaolibo1989** [comment]
> 查看下音频格式是否正常吧，一般需要单声道的 16bit 的 wav 文件 如果还是不行，建议直接去 MFA 仓库搜下问题 https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

多谢指点。
我遇到的这个问题类似[这个](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/130)但又不太一样，这个问题也提交很久了，看下面也有不少人遇到，但最后也没有满意的答案。

**Comment by zhaolibo1989** [comment]
> 查看下音频格式是否正常吧，一般需要单声道的 16bit 的 wav 文件 如果还是不行，建议直接去 MFA 仓库搜下问题 https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

确认了。wav 文件是单声道 16bit 的。

**Comment by zhaolibo1989** [comment]
@yt605155624 
这个问题你们需要进一步了解吗，如果没有的话，我就关闭好了，虽然我的问题还没有解决。

**Comment by maize-j** [comment]
我也遇到这个问题，不过当时的音频是24bit、48k，后面把音频转成了16bit、48k后就没问题了

**Comment by wjddd** [comment]
@zhaolibo1989 您好，请问这个问题最后解决了吗？
