### ISSUE TITLE
[TTS] 导出ONNX模型，推理代码报错

### ISSUE THREAD

**Issue by JunZhan2000** [PaddlePaddle/PaddleSpeech#3021]
我微调了fastspeech2_mix模型，paddle2onnx导出了一个onnx模型
然后我照着这个教程里的onnx推理代码运行的时候，报错

> Traceback (most recent call last):
  File "/remote-home/share/jzhan/EN-ZH-TTS/SpeechClone/inference_onnx.py", line 44, in <module>
    wav = inference(text)
  File "/remote-home/share/jzhan/EN-ZH-TTS/SpeechClone/inference_onnx.py", line 34, in inference
    am_output_data = am_infer_sess.run(None, input_feed={'text': phone_ids[0].numpy()})
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 196, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 2 inputs. Input Feed contains 1

是我哪一步出了问题？

**Comment by JunZhan2000** [comment]
自己用fastspeech2_mix导出的ONNX模型，要传入两个参数，第二个参数是spk_id，所以教程里要改一下代码：
am_output_data = am_infer_sess.run(None, input_feed={'text': phone_ids[0].numpy(), 'spk_id': np.array([0])})
   这个spk_id好像设什么都一样
