### ISSUE TITLE
No module named '_soundfile_data'

### ISSUE THREAD

**Issue by KajiMaCN** [PaddlePaddle/PaddleSpeech#3044]
File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/soundfile.py", line 170, in <module>
    raise OSError('sndfile library not found using ctypes.util.find_library')
OSError: sndfile library not found using ctypes.util.find_library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/Server.py", line 76, in infer
    result['return'],result['result'] = od.predict([infer_path], self.cfg, self.writer)
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/offline_detected.py", line 398, in predict
    result,word=deal_result(sound,wav,speech_timestamps,offline_asr,cfg,writer)
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/result_process.py", line 148, in deal_result
    word=punctuation_restoration(word,save_path,writer)
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/result_process.py", line 76, in punctuation_restoration
    from paddlespeech.cli.text.infer import TextExecutor
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/cli/base_commands.py", line 20, in <module>
    from ..resource import CommonTaskResource
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 28, in <module>
    import soundfile as sf
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory

**Comment by zxcd** [comment]
Please try https://github.com/PaddlePaddle/PaddleSpeech/issues/440

**Comment by KajiMaCN** [comment]
> Please try #440

Thank you, but now I have another issue:
Traceback (most recent call last):
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/Server.py", line 76, in infer
    result['return'],result['result'] = od.predict([infer_path], self.cfg, self.writer)
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/offline_detected.py", line 398, in predict
    result,word=deal_result(sound,wav,speech_timestamps,offline_asr,cfg,writer)
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/result_process.py", line 148, in deal_result
    word=punctuation_restoration(word,save_path,writer)
  File "/workspace/sherpa/bin/pruned_transducer_statelessX/result_process.py", line 76, in punctuation_restoration
    from paddlespeech.cli.text.infer import TextExecutor
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/cli/text/__init__.py", line 14, in <module>
    from .infer import TextExecutor
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/cli/text/infer.py", line 29, in <module>
    from paddlespeech.text.models.ernie_linear import ErnieLinear
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/text/models/__init__.py", line 15, in <module>
    from .ernie_linear import ErnieLinear
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/text/models/ernie_linear/__init__.py", line 16, in <module>
    from .ernie_linear_updater import *
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/text/models/ernie_linear/ernie_linear_updater.py", line 24, in <module>
    from paddlespeech.t2s.training.extensions.evaluator import StandardEvaluator
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/__init__.py", line 19, in <module>
    from . import models
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/models/__init__.py", line 14, in <module>
    from .ernie_sat import *
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/models/ernie_sat/__init__.py", line 14, in <module>
    from .ernie_sat import *
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/models/ernie_sat/ernie_sat.py", line 21, in <module>
    from paddlespeech.t2s.modules.activation import get_activation
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/modules/__init__.py", line 16, in <module>
    from .losses import *
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/modules/losses.py", line 23, in <module>
    from paddlespeech.t2s.modules.nets_utils import make_non_pad_mask
  File "/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/paddlespeech/t2s/modules/nets_utils.py", line 21, in <module>
    from typeguard import check_argument_types
ImportError: cannot import name 'check_argument_types' from 'typeguard' (/home/anaconda3/envs/autoasr/lib/python3.8/site-packages/typeguard/__init__.py)

**Comment by zxcd** [comment]
Please try https://github.com/PaddlePaddle/PaddleSpeech/issues/3051

**Comment by moseranliunian** [comment]
hello， i want to ask about
import _soundfile_data # ImportError if this doesn't exist
ModuleNotFoundError: No module named '_soundfile_data'
how do you solve this problem?

**Comment by KajiMaCN** [comment]
> hello， i want to ask about import _soundfile_data # ImportError if this doesn't exist ModuleNotFoundError: No module named '_soundfile_data' how do you solve this problem?

Im try https://github.com/PaddlePaddle/PaddleSpeech/issues/440 and https://github.com/PaddlePaddle/PaddleSpeech/issues/3051 , they worked for me.
