### ISSUE TITLE
ImportError: cannot import name 'check_argument_types' from 'typeguard'

### ISSUE THREAD

**Issue by wangqingbang-austin** [PaddlePaddle/PaddleSpeech#3051]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/sparse/sputils.py:16: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
Traceback (most recent call last):
  File "/home/aistudio/.data/webide/pip/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/cli/text/__init__.py", line 14, in <module>
    from .infer import TextExecutor
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/cli/text/infer.py", line 29, in <module>
    from paddlespeech.text.models.ernie_linear import ErnieLinear
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/text/models/__init__.py", line 15, in <module>
    from .ernie_linear import ErnieLinear
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/text/models/ernie_linear/__init__.py", line 16, in <module>
    from .ernie_linear_updater import *
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/text/models/ernie_linear/ernie_linear_updater.py", line 24, in <module>
    from paddlespeech.t2s.training.extensions.evaluator import StandardEvaluator
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/__init__.py", line 19, in <module>
    from . import models
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/models/__init__.py", line 14, in <module>
    from .ernie_sat import *
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/models/ernie_sat/__init__.py", line 14, in <module>
    from .ernie_sat import *
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/models/ernie_sat/ernie_sat.py", line 21, in <module>
    from paddlespeech.t2s.modules.activation import get_activation
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/modules/__init__.py", line 16, in <module>
    from .losses import *
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/modules/losses.py", line 23, in <module>
    from paddlespeech.t2s.modules.nets_utils import make_non_pad_mask
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlespeech/t2s/modules/nets_utils.py", line 21, in <module>
    from typeguard import check_argument_types
ImportError: cannot import name 'check_argument_types' from 'typeguard' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/typeguard/__init__.py)

**Comment by wangqingbang-austin** [comment]
AI studio 实验室按照教程步骤复现也出现了同样的问题

**Comment by hollykbuck** [comment]
I believe this is due to a breaking update of typeguard: it removed the `check_argument_types` API.

> BACKWARD INCOMPATIBLE Removed the check_argument_types() and check_return_type() functions (use @typechecked instead)
> 
> https://typeguard.readthedocs.io/en/stable/versionhistory.html

downgrade to typeguard==2.13.3 works for me.

**Comment by wangqingbang-austin** [comment]
Thank you for your reply, which successfully solved my problem

> I believe this is due to a breaking update of typeguard: it removed the `check_argument_types` API.
> 
> > BACKWARD INCOMPATIBLE Removed the check_argument_types() and check_return_type() functions (use @TypeChecked instead)
> > https://typeguard.readthedocs.io/en/stable/versionhistory.html
> 
> downgrade to typeguard==2.13.3 works for me.

**Comment by achaosss** [comment]
> I believe this is due to a breaking update of typeguard: it removed the `check_argument_types` API.
> 
> > BACKWARD INCOMPATIBLE Removed the check_argument_types() and check_return_type() functions (use @TypeChecked instead)
> > https://typeguard.readthedocs.io/en/stable/versionhistory.html
> 
> downgrade to typeguard==2.13.3 works for me.

OK for me

**Comment by nyngwang** [comment]
[It's `@typechecked`, not `@TypeChecked`](https://typeguard.readthedocs.io/en/stable/versionhistory.html).

**Comment by hitjcl** [comment]
> 

No okay for me using AI studio

**Comment by pwatx** [comment]
这个错误是因为typeguard 库的版本问题。
typeguard 3.0版本中check_argument_types 已被移除，更改 typeguard==2.13.3 即可
