### ISSUE TITLE
[TTS]ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by vscv** [PaddlePaddle/PaddleSpeech#3072]
依照簡單方法安裝，但使用時報錯。

$sudo pip install pytest-runner
$sudo pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
$sudo pip install paddlespeech

$paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/cli/tts/infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/__init__.py", line 18, in <module>
    from . import frontend
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/__init__.py", line 15, in <module>
    from .normalizer import *
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/normalizer/__init__.py", line 14, in <module>
    from paddlespeech.t2s.frontend.normalizer.normalizer import *
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/normalizer/normalizer.py", line 18, in <module>
    from paddlespeech.t2s.frontend.normalizer.numbers import normalize_numbers
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/t2s/frontend/normalizer/numbers.py", line 17, in <module>
    import inflect
  File "/usr/local/lib/python3.8/dist-packages/inflect/__init__.py", line 76, in <module>
    from pydantic import Field, validate_arguments
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform

**Comment by lym0302** [comment]
看样子好像是 inflect 依赖库的问题，再 check 下依赖库吧，大概率是没有安装好。

**Comment by vscv** [comment]
剛試了安裝inflect，不過錯誤還是一樣。

Name: inflect
Version: 6.0.2
Summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
Home-page: https://github.com/jaraco/inflect
Author: Paul Dyson
Author-email: pwdyson@yahoo.com
License: 
Location: /usr/local/lib/python3.8/dist-packages
Requires: pydantic
Required-by: g2p-en, paddlespeech
