### ISSUE TITLE
请问一下，有人在运行TTS项目时，有遇到过pypinyin这个错误吗？应该怎么解决呢，暂时没有找到解决的办法

### ISSUE THREAD

**Issue by yyanning** [PaddlePaddle/PaddleSpeech#3082]
Traceback (most recent call last):
  File ".\start.py", line 15, in <module>
    from src.transcribe import TTSExecutor, pretrained_models, front_models
  File "F:\TTS\py_scripts\src\transcribe.py", line 31, in <module>
    from paddlespeech.t2s.frontend import English
  File "F\paddlespeech\t2s\__init__.py", line 18, in <module>
    from . import frontend
  File "F:\paddlespeech\t2s\frontend\__init__.py", line 16, in <module>
    from .phonectic import *
  File "F:\paddlespeech\t2s\frontend\phonectic.py", line 26, in <module>
    from paddlespeech.t2s.frontend.zh_normalization.text_normlization import TextNormalizer
  File "F:\paddlespeech\t2s\frontend\zh_normalization\__init__.py", line 14, in <module>
    from paddlespeech.t2s.frontend.zh_normalization.text_normlization import *
  File "F:\paddlespeech\t2s\frontend\zh_normalization\text_normlization.py", line 25, in <module>
    from .constants import F2H_ASCII_LETTERS
  File "F:\paddlespeech\t2s\frontend\zh_normalization\constants.py", line 17, in <module>
    from pypinyin.constants import SUPPORT_UCS4
ModuleNotFoundError: No module named 'pypinyin.constants'; 'pypinyin' is not a package

**Comment by zxcd** [comment]
Try this: https://github.com/PaddlePaddle/PaddleSpeech/issues/2363

**Comment by lym0302** [comment]
大概率是因为依赖库没有安装好，你再check 一下~

**Comment by yyanning** [comment]
更新一下，已经解决了这个问题，重新安装paddlespeech 即可！

**Comment by yyanning** [comment]
> 大概率是因为依赖库没有安装好，你再check 一下~

好的谢谢！成功解决了
