### ISSUE TITLE
Docker 容器无法直接使用, 报错OSError: cannot load library 'libsndfile.so'

### ISSUE THREAD

**Issue by Colin-XKL** [PaddlePaddle/PaddleSpeech#3090]
现象:
使用 docker 运行最新的 docker 镜像, 执行 paddlespeech 指令报错, OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory

复现:
```shell
sudo docker run -it --name paddlespeech-test   -p 8888:8888  paddlecloud/paddlespeech:develop-cpu-6894a2  /bin/bash

// 进入容器后 执行
paddlespeech --help
```

报错信息
```shell
λ 1a25409e403f /home/PaddleSpeech paddlespeech --help
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 161, in <module>
    import _soundfile_data  # ImportError if this doesn't exist
ModuleNotFoundError: No module named '_soundfile_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 170, in <module>
    raise OSError('sndfile library not found using ctypes.util.find_library')
OSError: sndfile library not found using ctypes.util.find_library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/base_commands.py", line 20, in <module>
    from ..resource import CommonTaskResource
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/utils.py", line 28, in <module>
    import soundfile as sf
  File "/usr/local/lib/python3.7/dist-packages/soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
λ 1a25409e403f /home/PaddleSpeech 


```

**Comment by Colin-XKL** [comment]
补充信息:
宿主机环境:
Debian 11  5.10.149-2 (2022-10-21) x86_64
Docker CE 23.0.1

**Comment by zxcd** [comment]
Please try:
`sudo apt-get install libsndfile1`
