### ISSUE TITLE
'mfa_align' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by makeukus** [PaddlePaddle/PaddleSpeech#3122]
## General Question

我按照（[文章](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tts_finetune/tts3)）的步骤进行操作，运行run.sh有报错

Administrator@DESKTOP-1B5BUG2 MINGW64 /i/Github/PaddleSpeech-develop/examples/other/tts_finetune/tts3
$ ./run.sh
check oov
get mfa result
'mfa_align' is not recognized as an internal or external command,
operable program or batch file.
./input/csmsc_mini/newdir
./mfa_result
generate durations.txt
Traceback (most recent call last):
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\generate_duration.py", line 17, in <module>
    from utils.gen_duration_from_textgrid import gen_duration_from_textgrid
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\utils\gen_duration_from_textgrid.py", line 18, in <module>
    import librosa
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\librosa\__init__.py", line 210, in <module>
    from ._cache import cache
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\librosa\_cache.py", line 6, in <module>
    from joblib import Memory
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\joblib\__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\joblib\memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\joblib\_store_backends.py", line 15, in <module>
    from .backports import concurrency_safe_rename
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\joblib\backports.py", line 125, in <module>
    import numpy as np
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

我应该怎样处理？

**Comment by makeukus** [comment]
我尝试使用python310，但是仍然有报错。
$ ./run.sh
check oov
get mfa result
'mfa_align' is not recognized as an internal or external command,
operable program or batch file.

generate durations.txt
extract feature
I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
-2 1
create finetune env
finetune...
C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\win32\lib\pywintypes.py:51: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
  found = _win32sysloader.GetModuleFilename(filename)
C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\win32\lib\pywintypes.py:65: DeprecationWarning: getargs: The 'u' format is deprecated. Use 'U' instead.
  found = _win32sysloader.LoadModule(filename)
I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
rank: 0, pid: 19092, parent_pid: 21764
multiple speaker fastspeech2!
spk_num: 174
Traceback (most recent call last):
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\finetune.py", line 269, in <module>
    train_sp(train_args, config)
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\finetune.py", line 120, in train_sp
    with jsonlines.open(args.train_metadata, 'r') as reader:
  File "I:\Github\PaddleSpeech-develop\examples\other\tts_finetune\tts3\local\jsonlines\jsonlines.py", line 627, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump\\train\\norm\\metadata.jsonl'

**Comment by makeukus** [comment]
我在Centos 7系统上，运行run.sh，仍然有错误。
[root@localhost tts3]# ./run.sh
check oov
get mfa result
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 198.0
/root/\udce6\udca1\udc8c\udce9\udc9d\udca2/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstcompile)
fstcompile: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstarcsort)
fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstcompile)
fstcompile: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstcompile: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by fstarcsort)
fstarcsort: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfstscript.so.13)
fstarcsort: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/thirdparty/bin/libfst.so.13)
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/newdir/train/mfcc/raw_mfcc.0.scp'
[21274] Failed to execute script align
generate durations.txt
Traceback (most recent call last):
  File "/root/桌面/PaddleSpeech-develop/examples/other/tts_finetune/tts3/local/generate_duration.py", line 17, in <module>
    from utils.gen_duration_from_textgrid import gen_duration_from_textgrid
  File "/root/桌面/PaddleSpeech-develop/utils/gen_duration_from_textgrid.py", line 18, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

python3.9
Centos 7 64

**Comment by makeukus** [comment]
这是一个悲伤的事情
[root@localhost tts3]# ./run.sh
check oov
get mfa result
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 198.0
/root/develop/PaddleSpeech-develop/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/newdir/train/mfcc/raw_mfcc.0.scp'
[46067] Failed to execute script align
generate durations.txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/scipy/__init__.py", line 154, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/usr/local/lib/python3.9/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/develop/PaddleSpeech-develop/examples/other/tts_finetune/tts3/local/generate_duration.py", line 17, in <module>
    from utils.gen_duration_from_textgrid import gen_duration_from_textgrid
  File "/root/develop/PaddleSpeech-develop/utils/gen_duration_from_textgrid.py", line 18, in <module>
    import librosa
  File "/usr/local/lib/python3.9/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.9/site-packages/librosa/core/__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.9/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.9/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.9/site-packages/librosa/util/utils.py", line 5, in <module>
    import scipy.ndimage
  File "/usr/local/lib/python3.9/site-packages/scipy/__init__.py", line 159, in <module>
    raise ImportError(msg) from e
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

CentOS 8
python 3.9

**Comment by lym0302** [comment]
目前看起来是环境问题，你再check下。如果有其他问题可以先在 issue 上搜一下，issue 置顶有小样本微调相关问题及解决方案，可以看下对你有没有帮助。

**Comment by makeukus** [comment]
> 目前看起来是环境问题，你再check下。如果有其他问题可以先在 issue 上搜一下，issue 置顶有小样本微调相关问题及解决方案，可以看下对你有没有帮助。

应该是，我现在直接在Aistudio上运行了。

**Comment by zyb8543d** [comment]
@lym0302 遇到同样的问题，我是在paddlespeech的镜像里运行的
```
get mfa result
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 198.0
/home/examples/other/tts_finetune/tts3/tools/montreal-forced-aligner/lib/aligner/models.py:87: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/newdir/train/mfcc/raw_mfcc.0.scp'
[892] Failed to execute script align

Traceback (most recent call last):
  File "local/extract_feature.py", line 352, in <module>
    replace_spkid=args.replace_spkid)
  File "local/extract_feature.py", line 267, in extract_feature
    vocab_speaker, dump_dir, "train")
  File "local/extract_feature.py", line 160, in normalize
    "energy": np.load,
  File "/home/paddlespeech/t2s/datasets/data_table.py", line 45, in __init__
    assert len(data) > 0, "This dataset has no examples"
AssertionError: This dataset has no examples

```

**Comment by lancelee98** [comment]
可以把git_mfa_result.py 中51行，CMD语句的mfa_align换成mfa_align.exe的绝对路径， 如c:\\xxxxxxxx\tools\montreal-forced-aligner/bin/mfa_align.exe

**Comment by HsiangLeekwok** [comment]
同样的问题：./run_mix.sh
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 94, in align_corpus
  File "aligner/aligner/pretrained.py", line 74, in __init__
  File "aligner/aligner/pretrained.py", line 122, in setup
  File "aligner/aligner/base.py", line 89, in setup
  File "aligner/corpus.py", line 979, in initialize_corpus
  File "aligner/corpus.py", line 852, in create_mfccs
  File "aligner/corpus.py", line 863, in _combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/root/Documents/MFA/newdir/train/mfcc/raw_mfcc.0.scp'
[18373] Failed to execute script align
generate durations.txt
extract feature
13 1
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 2564.36it/s]
Done

CentOS7 cpu模式跑
(paddle) [root@localhost tts3]# pip list|grep paddle
paddle2onnx                 1.1.0
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.5.2
paddlepaddle                2.5.2
paddlesde                   0.2.5
paddleslim                  2.4.1
paddlespeech                0.0.0
paddlespeech-ctcdecoders    0.2.0
paddlespeech-feat           0.1.0
