### ISSUE TITLE
[TTS]Docker develop-gpu-cuda10.2-cudnn7-latest 缺失 libsndfile1-dev 和 環境參數CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by kenny-chen** [PaddlePaddle/PaddleSpeech#3158]
**Describe the bug**
Docker develop-gpu-cuda10.2-cudnn7-latest 缺失:
1. apt install libsndfile1-dev
2. 環境參數 os.environ["CUDA_VISIBLE_DEVICES"] = "0"

**To Reproduce**
1. 按照官方教程，使用Docker鏡像部署 `docker pull paddlecloud/paddlespeech:develop-gpu-cuda10.2-cudnn7-latest`
2. 進入Docker鏡像 `nvidia-docker run --runtime=nvidia -it -v ~/PycharmProjects/PaddleSpeech:/home paddlecloud/paddlespeech:develop-gpu-cuda10.2-cudnn7-latest /bin/bash`
3. 成功捕獲顯示卡 `nvidia-smi`
![image](https://user-images.githubusercontent.com/68576845/231620916-031193a5-e04e-4acd-b74f-7be0d91e38c3.png)
`nvcc -V`
![image](https://user-images.githubusercontent.com/68576845/231621003-690c0d9b-754b-45b4-aba8-1a4a08537a61.png)
`./test_cuda`
![image](https://user-images.githubusercontent.com/68576845/231621163-2294e2f4-c9e9-4987-b72c-95ab50fc17a2.png)
4. 但執行demo項目，`cd demos/style_fs2 && ./run.sh` 出現error

**Bug**
1. 缺失 libsndfile1-dev
`Traceback (most recent call last):
  File "style_syn.py", line 22, in <module>
    import soundfile as sf
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/soundfile.py", line 192, in <module>
    _snd = _ffi.dlopen(_explicit_libname)
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory`
我猜測，這是CUDA10.2官方docker的bug，里面缺少了libsndfile1-dev。
當執行`apt install libsndfile1-dev`後，成功解決。

2. 缺失 環境參數CUDA_VISIBLE_DEVICES
`Traceback (most recent call last):
  File "style_syn.py", line 228, in <module>
    main()
  File "style_syn.py", line 209, in main
    paddle.set_device("gpu")
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/device/__init__.py", line 313, in set_device
    place = _convert_to_place(device)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/device/__init__.py", line 204, in _convert_to_place
    place = core.CUDAPlace(ParallelEnv().dev_id)
OSError: (External) CUDA error(100), no CUDA-capable device is detected.
  [Hint: 'cudaErrorNoDevice'. This indicates that no CUDA-capable devices were detected by the installed CUDA driver. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)`
因缺失 環境參數CUDA_VISIBLE_DEVICES，導致PaddleSpeech失敗獲取GPU。
`import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"`
當設置CUDA_VISIBLE_DEVICES=0後，成功解決。

**Environment:**
 - Docker: develop-gpu-cuda10.2-cudnn7-latest
 - CUDA: 10.2
 - CUDNN: 7

**Suggestion**
1. 在docker `develop-gpu-cuda10.2-cudnn7-latest` 鏡像 再安裝 `apt install libsndfile1-dev`
2. 在 `/demos/style_fs2/style_syn.py` 新增 `import os os.environ["CUDA_VISIBLE_DEVICES"] = "0"`

**Comment by lizezheng** [comment]
非常感謝提出的寶貴建議，歡迎持續關注 paddlespeech 並貢獻代碼

**Comment by kenny-chen** [comment]
> 非常感謝提出的寶貴建議，歡迎持續關注 paddlespeech 並貢獻代碼

你好，请问有develop-gpu-cuda10.2-cudnn7-latest的dockerfile吗?
这样我可以修改dockerfile代码。
