### ISSUE TITLE
microphone_client.py  NotImplementedError

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#3229]
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/tests/asr/online/microphone_client.py

```python
if __name__ == "__main__":

    logging.basicConfig(level=logging.INFO)
    logging.info("asr websocket client start")

    handler = ASRWsAudioHandler("127.0.0.1", 8090)
    loop = asyncio.get_event_loop()
    main_task = asyncio.ensure_future(handler.run())
    for signal in [SIGINT, SIGTERM]:
        loop.add_signal_handler(signal, main_task.cancel)
    try:
        loop.run_until_complete(main_task)
    finally:
        loop.close()

    logging.info("asr websocket client finished")

```

microphone_client 报错
```
INFO:root:asr websocket client start
Traceback (most recent call last):
  File "microphone_client.py", line 155, in <module>
    loop.add_signal_handler(signal, main_task.cancel)
  File "D:\anaconda3\envs\PaddleSpeech\lib\asyncio\events.py", line 540, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

服务器端启动
```
paddlespeech_server start --config_file ./conf/ws_conformer_wenetspeech_application.yaml
D:\anaconda3\envs\PaddleSpeech\lib\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
D:\anaconda3\envs\PaddleSpeech\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\anaconda3\envs\PaddleSpeech\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 11004] getaddrinfo failed>
[nltk_data] Error loading cmudict: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
[2023-05-05 23:01:57,339] [    INFO] - start to init the engine
[2023-05-05 23:01:57,339] [    INFO] - asr : online engine.
2023-05-05 23:01:57.419 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
W0505 23:02:00.958895  2532 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W0505 23:02:00.964898  2532 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
2023-05-05 23:02:05.351 | INFO     | paddlespeech.s2t.modules.embedding:__init__:150 - max len: 5000
[2023-05-05 23:02:06,135] [    INFO] - Initialize ASR server engine successfully on device: gpu:0.
INFO:     Started server process [2076]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8090 (Press CTRL+C to quit)
```

**Comment by MolianWH** [comment]
@monkeycc 
我也遇到了这个错误。原因是因为Windows不支持signal。通过修改代码已成功运行。
修改[154行](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/tests/asr/online/microphone_client.py#L154)
```python
signal.signal(signal.SIGINT, main_task.cancel)
signal.signal(signal.SIGTERM, main_task.cancel)
# for signal in [SIGINT, SIGTERM]:
#     loop.add_signal_handler(signal, main_task.cancel)
```
在文件头部需要添加import signal
同时，此时收到的数据是没有解码的，需要在[`#send bytes data`这段注释下](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/tests/asr/online/microphone_client.py#L112)，添加一行json.loads，代码如下：
```python
# send bytes data
  logging.info("结束录音请: Ctrl + c。继续请按回车。")
  try:
      while True:
          while len(self._frames) > 0:
              await ws.send(self._frames.pop(0))
              msg = await ws.recv()
              msg = json.loads(msg)
              logging.info("receive msg={}".format(msg))
```
还需要注意的是端口号是否一致，我的端口是8090
![image](https://user-images.githubusercontent.com/33748947/236615015-55cca480-ac0a-48d4-9865-d8777d8e3356.png)

**Comment by monkeycc** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/issues/3231

大佬 改了之后出现这个问题
有没遇到过
@MolianWH

**Comment by zh794390558** [comment]
建议在ubuntu上测试下吧。看着是系统库调用出错。

**Comment by monkeycc** [comment]
@zh794390558 

大佬
ubuntu和win 会出现这个问题
https://github.com/PaddlePaddle/PaddleSpeech/issues/3231

**Comment by Skypow2012** [comment]
按 @MolianWH 的调整后，我本地windows可以跑了，先到 `PaddleSpeech\paddlespeech\server` 目录，然后本地启动服务
```shell
paddlespeech_server start --config_file conf/ws_conformer_application.yaml
```
```python
class ASRWsAudioHandler(threading.Thread):
    def __init__(self, url="127.0.0.1", port=8091):
        threading.Thread.__init__(self)
        self.url = url
        self.port = port
        self.url = "ws://" + self.url + ":" + str(self.port) + "/ws/asr"
.....
handler = ASRWsAudioHandler("127.0.0.1", 8091)
```
改8091为8090端口、改路径/ws/asr为/paddlespeech/asr/streamin，变成下面这样
```python
class ASRWsAudioHandler(threading.Thread):
    def __init__(self, url="127.0.0.1", port=8090):
        threading.Thread.__init__(self)
        self.url = url
        self.port = port
        self.url = "ws://" + self.url + ":" + str(self.port) + "/paddlespeech/asr/streaming"
.....
handler = ASRWsAudioHandler("127.0.0.1", 8090)
```
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/18132118/68db7e14-ab39-411a-b960-cf356182b4ff)
