### ISSUE TITLE
numpy1.24.3报错

### ISSUE THREAD

**Issue by gxmlfx** [PaddlePaddle/PaddleSpeech#3235]
## General Question

刚装好后，运行了：
paddlespeech asr --lang zh --input zh.wav
log如下：
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/paddle/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/paddlespeech/cli/asr/infer.py", line 24, in <module>
    import librosa
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/core/__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/core/constantq.py", line 1059, in <module>
    dtype=np.complex,
  File "/home/user1/miniconda3/envs/paddle/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by mgsky1** [comment]
+1，有同样的问题

**Comment by hhuyzp** [comment]
我也遇到了一样的问题，一个个的改底层，找到报错的地方，把np.float还有np.complex去掉np.就好了

**Comment by mgsky1** [comment]
原来在setup.py的Librosa库是0.8.1，太老了，然后我们的numpy比较新，就有这个问题。
直接把Librosa删掉，安装0.10.0就行

**Comment by hhuyzp** [comment]
万分感谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSpeech"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSpeech] numpy1.24.3报错 (Issue #3235)





 
原来在setup.py的Librosa库是0.8.1，太老了，然后我们的numpy比较新，就有这个问题。
 直接把Librosa删掉，安装0.10.0就行

**Comment by hhuyzp** [comment]
Installing collected packages: msgpack, soxr, lazy-loader, Librosa
&nbsp; Attempting uninstall: Librosa
&nbsp; &nbsp; Found existing installation: librosa 0.8.1
&nbsp; &nbsp; Uninstalling librosa-0.8.1:
&nbsp; &nbsp; &nbsp; Successfully uninstalled librosa-0.8.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddleaudio 1.1.0 requires librosa==0.8.1, but you have librosa 0.10.0 which is incompatible.
paddlespeech 0.0.0 requires librosa==0.8.1, but you have librosa 0.10.0 which is incompatible.
Successfully installed Librosa-0.10.0 lazy-loader-0.2 msgpack-1.0.5 soxr-0.3.5


依然有依赖项报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSpeech"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSpeech] numpy1.24.3报错 (Issue #3235)





 
原来在setup.py的Librosa库是0.8.1，太老了，然后我们的numpy比较新，就有这个问题。
 直接把Librosa删掉，安装0.10.0就行

**Comment by mgsky1** [comment]
还有一种方式，librosa不变，numpy降级为1.23.5
> The deprecation for the aliases np.object, np.bool, np.float, np.complex, np.str, and np.int is expired (introduces NumPy 1.20). Some of these will now give a FutureWarning in addition to raising an error since they will be mapped to the NumPy scalars in the future.

https://numpy.org/devdocs/release/1.24.0-notes.html

refer:https://github.com/coqui-ai/TTS/issues/2442

**Comment by hhuyzp** [comment]
这个方法可行，只会警告，但不会报错，谢谢你呀


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleSpeech"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 中午12:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleSpeech] numpy1.24.3报错 (Issue #3235)





 
还有一种方式，librosa不变，numpy降级为1.23.5

**Comment by mgsky1** [comment]
已经提PR了，不知道会不会被合入～感觉应该是一个过渡手段，最好是把代码进行修改做兼容

**Comment by gxmlfx** [comment]
官方的docker镜像也会提示numpy complex的问题。
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
但是这里可以继续，这似乎是一个仍可用的numpy版本

运行paddlespeech_server start会报 raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
log如下：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
Traceback (most recent call last):
  File "/usr/local/bin/paddlespeech_server", line 5, in <module>
    from paddlespeech.server.entry import server_execute
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/__init__.py", line 16, in <module>
    from .base_commands import ClientBaseCommand
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/base_commands.py", line 18, in <module>
    from .util import cli_client_register
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/util.py", line 32, in <module>
    from . import download
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/download.py", line 30, in <module>
    from paddlespeech.cli.log import logger
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/__init__.py", line 23, in <module>
    from .tts import TTSExecutor
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/tts/infer.py", line 36, in <module>
    from paddlespeech.t2s.frontend import English
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/t2s/__init__.py", line 18, in <module>
    from . import frontend
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/t2s/frontend/__init__.py", line 16, in <module>
    from .phonectic import *
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/t2s/frontend/phonectic.py", line 20, in <module>
    from g2p_en import G2p
  File "/usr/local/lib/python3.7/dist-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/usr/local/lib/python3.7/dist-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/usr/local/lib/python3.7/dist-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python3.7/dist-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python3.7/dist-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by mgsky1** [comment]
那个只是warning，并不是报错。
那个zip的错误，可以看看这个issue：https://github.com/PaddlePaddle/PaddleSpeech/issues/1925

**Comment by gxmlfx** [comment]
感谢，我试一下

**Comment by mgsky1** [comment]
我最后把这个问题移到【安装报错留言区】了，感觉这样好一些，本质上不是代码问题，只是环境上的问题

**Comment by xtdhwl** [comment]
conda install -c conda-forge librosa

https://librosa.org/doc/latest/install.html
升级librosa

**Comment by androidfans** [comment]
> 原来在setup.py的Librosa库是0.8.1，太老了，然后我们的numpy比较新，就有这个问题。 直接把Librosa删掉，安装0.10.0就行

请问在官方的这个lab页面里面要怎么做这个操作啊  https://aistudio.baidu.com/bd-gpu-01/user/3279555/6931268/lab/tree/main.ipynb

**Comment by alittlenico** [comment]
> 还有一种方式，librosa不变，numpy降级为1.23.5
> 
> > The deprecation for the aliases np.object, np.bool, np.float, np.complex, np.str, and np.int is expired (introduces NumPy 1.20). Some of these will now give a FutureWarning in addition to raising an error since they will be mapped to the NumPy scalars in the future.
> 
> https://numpy.org/devdocs/release/1.24.0-notes.html
> 
> refer:[coqui-ai/TTS#2442](https://github.com/coqui-ai/TTS/issues/2442)

谢谢 也解决了我的问题

**Comment by ilovejs** [comment]
pip install -U librosa
pip freeze | grep librosa
`# 1.10.*`
