### ISSUE TITLE
[TTS]examples/aishell3/tts

### ISSUE THREAD

**Issue by yeyeyeyeeeee** [PaddlePaddle/PaddleSpeech#3278]
跑样例过程中，在Synthesizing这一步中报错，请问是哪里的问题
multiple speaker fastspeech2!
Traceback (most recent call last):
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize.py", line 259, in <module>
    main()
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize.py", line 255, in main
    evaluate(args)
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize.py", line 109, in evaluate
    phone_ids, spk_id=spk_id, spk_emb=spk_emb)
  File "/home/ubuntu/miniconda3/envs/pdspeech/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 926, in forward
    text, spk_id=spk_id, spk_emb=spk_emb)
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 822, in inference
    tone_id=tone_id)
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 623, in _forward
    hs = self._integrate_with_spk_embed(hs, spk_emb)
  File "/home/ubuntu/yqk/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 845, in _integrate_with_spk_embed
    spk_emb = F.normalize(spk_emb).unsqueeze(1).expand(
  File "/home/ubuntu/miniconda3/envs/pdspeech/lib/python3.7/site-packages/paddle/nn/functional/norm.py", line 82, in normalize
    out = _C_ops.p_norm(x, float(p), axis, epsilon, True, False)
ValueError: (InvalidArgument) Attr(axis) value should be in range [-R, R-1], R is the rank of Input(X). But received axis: 1, R: 1. Current Input(X)'s shape is=[256].
  [Hint: Expected axis < x_rank, but received axis:1 >= x_rank:1.] (at ../paddle/phi/infermeta/unary.cc:2751)

**Comment by yeyeyeyeeeee** [comment]
paddlepaddle-gpu使用开发版出现错误，修改回稳定版即可

**Comment by GDbbq** [comment]
我也遇到了这个问题。。

**Comment by bardenthenry** [comment]
我用 2.5.1 的版本也遇到這個錯誤，請問是否解決了？
