### ISSUE TITLE
[TTS]语音韵律合成MFA问题

### ISSUE THREAD

**Issue by zapjone** [PaddlePaddle/PaddleSpeech#3322]
参照https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/csmsc/tts3_rhy文档进行韵律标签生成时。
执行sh run.sh --rhy-with-duration出现以下错误，请问大佬们，谁遇到过这种问题，怎么解决的呢？
generating lexicon...
Done!
lexicon done
reorganizing baker corpus...
resampling: 0it [00:00, ?it/s]
transcription process: 100%|███████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:00<00:00, 29822.81it/s]
Done!
reorganization done. Check output in exp/baker_corpus.
audio files are resampled to 16kHz
transcription for each audio file is saved with the same namd in exp/baker_corpus 
detecting oov...
Namespace(corpus_dir='exp/baker_corpus', lexicon_path='exp/simple.lexicon', pattern='*.lab')
WARNING:root:005107.lab has OOV ng1 .
WARNING:root:002365.lab has OOV P .
WARNING:root:002365.lab has OOV IY1 .
detecting oov done. you may consider regenerate lexicon if there is unexpected OOVs.
Start MFA training...
Setting up corpus information...
set()
Traceback (most recent call last):
  File "aligner/command_line/train_and_align.py", line 171, in <module>
  File "aligner/command_line/train_and_align.py", line 53, in align_corpus
  File "aligner/dictionary.py", line 128, in __init__
  File "aligner/dictionary.py", line 18, in compile_graphemes
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/re.py", line 233, in compile
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/re.py", line 301, in _compile
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/sre_compile.py", line 562, in compile
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/sre_parse.py", line 855, in parse
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/sre_parse.py", line 416, in _parse_sub
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/sre_parse.py", line 765, in _parse
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/sre_parse.py", line 416, in _parse_sub
  File "/home/michael/miniconda3/envs/aligner/lib/python3.6/sre_parse.py", line 523, in _parse
sre_constants.error: unterminated character set at position 5
[2503831] Failed to execute script train_and_align
training done!
results: exp/baker_alignment
model: exp/baker_model

**Comment by zh794390558** [comment]
报错点在mfa上，确认是否可以正常工作吧。建议用ubuntu的机器。

**Comment by zapjone** [comment]
就是使用的ubantu的机器

**Comment by zapjone** [comment]
已解决了，删除montreal-forced-aligner/lib/thirdparty/bin/libopenblas.so.0文件，使用系统的文件就成功执行了。
