### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by OneTrueSum95** [PaddlePaddle/PaddleSpeech#3326]
E:\jy\test>python app.py
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 11004] getaddrinfo failed>
[nltk_data] Error loading cmudict: <urlopen error [Errno 11004]
[nltk_data]     getaddrinfo failed>
C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[2023-06-10 01:41:51,157] [    INFO] - Already cached C:\Users\79420\.paddlenlp\models\bert-base-chinese\bert-base-chinese-vocab.txt
[2023-06-10 01:41:51,543] [    INFO] - tokenizer config file saved in C:\Users\79420\.paddlenlp\models\bert-base-chinese\tokenizer_config.json
[2023-06-10 01:41:51,544] [    INFO] - Special tokens file saved in C:\Users\79420\.paddlenlp\models\bert-base-chinese\special_tokens_map.json
Traceback (most recent call last):
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\corpus\util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource cmudict not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('cmudict')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/cmudict.zip/cmudict/

  Searched in:
    - 'C:\\Users\\79420/nltk_data'
    - 'C:\\Users\\79420\\AppData\\Local\\Programs\\Python\\Python39\\nltk_data'
    - 'C:\\Users\\79420\\AppData\\Local\\Programs\\Python\\Python39\\share\\nltk_data'
    - 'C:\\Users\\79420\\AppData\\Local\\Programs\\Python\\Python39\\lib\\nltk_data'
    - 'C:\\Users\\79420\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\jy\test\app.py", line 26, in <module>
    frontend = get_frontend(
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\paddlespeech\t2s\exps\syn_utils.py", line 274, in get_frontend
    frontend = MixFrontend(
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\paddlespeech\t2s\frontend\mix_frontend.py", line 34, in __init__
    self.en_frontend = English(phone_vocab_path=phone_vocab_path)
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\paddlespeech\t2s\frontend\phonectic.py", line 53, in __init__
    self.backend = G2p()
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\g2p_en\g2p.py", line 71, in __init__
    self.cmu = cmudict.dict()
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\corpus\util.py", line 121, in __getattr__
    self.__load()
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\corpus\util.py", line 86, in __load
    raise e
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\corpus\util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "C:\Users\79420\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource cmudict not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('cmudict')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/cmudict

  Searched in:
    - 'C:\\Users\\79420/nltk_data'
    - 'C:\\Users\\79420\\AppData\\Local\\Programs\\Python\\Python39\\nltk_data'
    - 'C:\\Users\\79420\\AppData\\Local\\Programs\\Python\\Python39\\share\\nltk_data'
    - 'C:\\Users\\79420\\AppData\\Local\\Programs\\Python\\Python39\\lib\\nltk_data'
    - 'C:\\Users\\79420\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

环境：windows11
python版本：3.9.9
nltk_data也已重新下载
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>>
>>> nltk.find('.')
FileSystemPathPointer('E:\\nltk_data')

**Comment by zh794390558** [comment]
在issue里搜下 nltk 的问题。

**Comment by OneTrueSum95** [comment]
> 

换了nltk_data，已解决
