### ISSUE TITLE
[TTS]语音合成数据处理

### ISSUE THREAD

**Issue by zapjone** [PaddlePaddle/PaddleSpeech#3351]
Generate durations_baker.txt from MFA results ...
Traceback (most recent call last):
  File "/data/tts/PaddleSpeech/utils/gen_duration_from_textgrid.py", line 18, in <module>
    import librosa
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/icksys/miniconda3/envs/paddle/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/zh_en_tts/tts3/README.md
按照这里例子进行操作中英文混合数据合成时，报这种错误，是哪个库依赖版本不对吗？

**Comment by zapjone** [comment]
虽然没人回答，但还是要提

**Comment by LLouice** [comment]
我成功运行的环境中的版本，供参考
- librosa 0.10.0
- numba 0.57.0
