### ISSUE TITLE
请问如何进行本地语音模型训练啊,我准备好了WAV文件不知道如何本地训练

### ISSUE THREAD

**Issue by lckj2009** [PaddlePaddle/PaddleSpeech#3388]
听说最近支持了无标注的本地语音模型训练,请问如何做啊.

TTS3广东话那个 运行 ./run.sh
结果就

AssertionError
Get features' stats ...
Traceback (most recent call last):
  File "/home/taipu/TTT/PaddleSpeech/utils/compute_statistics.py", line 109, in <module>
    main()
  File "/home/taipu/TTT/PaddleSpeech/utils/compute_statistics.py", line 84, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/home/taipu/anaconda3/envs/TTT/lib/python3.9/site-packages/jsonlines/jsonlines.py", line 627, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'

这样了

**Comment by zh794390558** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'

报错信息如上，可以看上上个流程是否成功。

**Comment by lckj2009** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'
> 
> 报错信息如上，可以看上上个流程是否成功。

有5个问题:
1, 项目文档中说的 ~/datasets/ 目录是哪个目录?  是LINUX服务器 ~/datasets/目录,   还是 PaddleSpeech 项目根目录下的目录?比如说   ......../PaddleSpeech/datasets/  到底是哪个位置呢?

2,我要做无文本标注语音训练, 是不是非要在PaddleSpeech/examples/canton/tts3 这个目录下?其他目录下的训练是不是也是无文本标注的模型训练?

3,PaddleSpeech/examples/canton/tts3 是不是只能做广东话训练,  普通话或者其他的中文语言可以训练吗?

4,MFA是不是一定要用,如果我用自己的普通话,那么MFA该怎么获取?  ./我的普通话_alignment是怎么得到的呢?  ./我的普通话_alignment 应该放在哪个文件夹下呢?

5,dump/train/raw/metadata.jsonl是不是训练过程中自动生成的?

望解答一下,谢谢

**Comment by zxcd** [comment]
1、datasets指你使用的git clone 下的PaddleSpeech/datasets/ 你代码放到哪就是哪。
2、每一个目录下都有对应任务的readme， 里面针对不同数据和任务都写的很清楚，你可以按照你所需要的任务类型来选择。
3、可以，因为我们是使用canton广东话数据集来训练的，所以训练出来的是支持广东话的模型，如果你有其他数据，也可以使用该任务训练一个自己的合成模型。
4、这个部分可以看一下对应的readme。
5、这个文件找不到应该是你的对齐有问题。可以参考这个看看https://github.com/PaddlePaddle/PaddleSpeech/issues/2461

**Comment by lckj2009** [comment]
> 1、datasets指你使用的git clone 下的PaddleSpeech/datasets/ 你代码放到哪就是哪。 2、每一个目录下都有对应任务的readme， 里面针对不同数据和任务都写的很清楚，你可以按照你所需要的任务类型来选择。 3、可以，因为我们是使用canton广东话数据集来训练的，所以训练出来的是支持广东话的模型，如果你有其他数据，也可以使用该任务训练一个自己的合成模型。 4、这个部分可以看一下对应的readme。 5、这个文件找不到应该是你的对齐有问题。可以参考这个看看#2461

谢谢.再问一下: PaddleSpeech 目录下有一个 dataset 文件夹.  这个文件夹跟我们要做的 datasets 文件夹没有关系吧.  我要新建一个datasets文件夹来放 WAV文件才对吧.   PaddleSpeech/datasets/wav/1.wav  像这样的放数据集对吗? 是否还需要修改什么配置文件?
