### ISSUE TITLE
streaming_asr_server 3060环境运行报错

### ISSUE THREAD

**Issue by seeseee** [PaddlePaddle/PaddleSpeech#3393]
streaming_asr_server 在1650显卡，cuda10.2，cudnn7.5环境下可以正常运行，迁移到3060显卡主机后可以正常启动，语音识别报错
以下为错误日志
```
E0713 19:34:39.524367 15232 top_k_function_cuda.h:1003] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E0713 19:34:39.526362 15232 top_k_function_cuda.h:1003] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
[2023-07-13 19:34:39,527] [   ERROR] - <method '_getitem_index_not_tensor' of 'Tensor' objects> returned a result with an error set
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\server\engine\asr\online\python\asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddle\fluid\dygraph\base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\server\engine\asr\online\python\asr_engine.py", line 504, in advance_decoding
    self.searcher.search(ctc_probs, self.cached_feat.place)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddle\fluid\dygraph\base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\server\engine\asr\online\ctc_search.py", line 108, in search
    ps = logp[s].item()
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 753, in __getitem__
    return self._getitem_index_not_tensor(item)
SystemError: <method '_getitem_index_not_tensor' of 'Tensor' objects> returned a result with an error set
```
```
[2023-07-13 19:34:57,436] [   ERROR] - offset: 4992 + x.shape[1]: 16 is larger than the max_len: 5000
Traceback (most recent call last):
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\server\engine\asr\online\python\asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddle\fluid\dygraph\base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\server\engine\asr\online\python\asr_engine.py", line 478, in advance_decoding
    self.cnn_cache) = self.model.encoder.forward_chunk(
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\s2t\modules\encoder.py", line 233, in forward_chunk
    xs, pos_emb, _ = self.embed(xs, tmp_masks, offset=offset)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\s2t\modules\subsampling.py", line 144, in forward
    x, pos_emb = self.pos_enc(x, offset)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\miniconda3\envs\PaddleSpeech-develop\lib\site-packages\paddlespeech\s2t\modules\embedding.py", line 161, in forward
    assert offset + x.shape[
AssertionError: offset: 4992 + x.shape[1]: 16 is larger than the max_len: 5000
```
我没找到相关issue，请问是否支持30系显卡

**Comment by zxcd** [comment]
可以尝试升级cuda版本，原因可能是30系列的显卡不支持CUDA10了，可以参考https://github.com/PaddlePaddle/Paddle/issues/44077

**Comment by seeseee** [comment]
我之前尝试使用cuda版本11.7，cudnn版本为8.6 提示找不到文件cudnn64_7.dll,之后降的版本，可以成功运行，但是使用是就会报这个错
