### ISSUE TITLE
遇到了循环引用的问题ImportError: cannot import name 'CommonTaskResource' from partially initialized module 'paddlespeech.resource' (most likely due to a circular import) (D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\resource\__init__.py)

### ISSUE THREAD

**Issue by 2625009538** [PaddlePaddle/PaddleSpeech#3406]
D:\Anaconda\envs\kty_paddle\python.exe D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddle.py 
Traceback (most recent call last):
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddle.py", line 14, in <module>
    from paddlespeech.cli.asr.infer import ASRExecutor
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\cli\__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\cli\base_commands.py", line 20, in <module>
    from ..resource import CommonTaskResource
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\resource\__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\resource\resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\cli\utils.py", line 26, in <module>
    import paddle
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddle.py", line 14, in <module>
    from paddlespeech.cli.asr.infer import ASRExecutor
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\cli\asr\__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\cli\asr\infer.py", line 32, in <module>
    from ..executor import BaseExecutor
  File "D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\cli\executor.py", line 27, in <module>
    from ..resource import CommonTaskResource
ImportError: cannot import name 'CommonTaskResource' from partially initialized module 'paddlespeech.resource' (most likely due to a circular import) (D:\Onedrive\Study\postgraduate\project\KongTianYuan\PaddleSpeech\paddlespeech\resource\__init__.py)

Process finished with exit code 1

**Comment by zxcd** [comment]
你在跑什么，是否存在两个python文件互相引用的情况?
