### ISSUE TITLE
[S2T]wenetspeech数据集训练报错，(Fatal) Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by Chuyaoyuan** [PaddlePaddle/PaddleSpeech#3435]
### 环境
python==3.8
paddlepaddle==0.0.0（2.5.0开发版）
paddlespeech==0.0.0 从develop分支编译安装
### 问题描述
按照 [wenetspeech/asr1](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/wenetspeech/asr1)中示例训练wenetspeech数据集，epoch ：0 已完毕，执行 epoch：1 训练报错，提示 (Fatal) Blocking queue is killed because the data reader raises an exception.

### 指令：
`bash run.sh --gpus 0,1 --stage 1 --stop_stage 1`
训练脚本：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/wenetspeech/asr1/local/train.sh
### 日志：

```
2023-07-28 06:32:17.457 | INFO     | paddlespeech.s2t.exps.u2.model:do_train:214 - Train: Rank: 0, epoch: 1, step: 15723, lr: 0.00056392, loss: 63.29914856, att_loss: 51.07065582, ctc_loss: 91.83230591, batch_size: 16, accum: 32, step_cost: 0.31190991, iter: 46900, reader_cost: 0.00034237, batch_cost: 0.31225228, samples: 16, ips: 51.24061814 samples/s
2023-07-28 06:32:56.869 | INFO     | paddlespeech.s2t.exps.u2.model:do_train:214 - Train: Rank: 0, epoch: 1, step: 15726, lr: 0.00056387, loss: 127.69183350, att_loss: 100.78931427, ctc_loss: 190.46438599, batch_size: 16, accum: 32, step_cost: 0.69754767, iter: 47000, reader_cost: 0.00041556, batch_cost: 0.69796324, samples: 16, ips: 22.92384346 samples/s
LAUNCH INFO 2023-07-28 06:33:48,632 Pod failed
LAUNCH ERROR 2023-07-28 06:33:48,632 Container failed !!!
Container rank 1 status failed cmd ['/usr/local/bin/python3', '-u', '/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/bin/train.py', '--ngpu', '2', '--seed', '0', '--config', 'conf/conformer.yaml', '--output', 'exp/conformer', '--profiler-options', '', '--benchmark-batch-size', '0', '--benchmark-max-step', '0'] code 1 log log/workerlog.1 
env {'NCCL_SOCKET_IFNAME': 'eth0', 'GREP_COLOR': '1;31', 'CPLUS_INCLUDE_PATH': '/usr/local/python3.7.0/include/python3.7:', 'CUDNN_VERSION': '7.6.5.32', 'HOSTNAME': '4756b3140789', 'NVIDIA_REQUIRE_CUDA': 'cuda>=10.2 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441', 'TERM': 'xterm', 'CLICOLOR': '1', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'LC_ALL': 'C', 'PYTHONIOENCODING': 'UTF-8', 'NVIDIA_VISIBLE_DEVICES': 'all', 'LD_LIBRARY_PATH': '/usr/local/python3.7.0/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib/', 'BIN_DIR': '/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/bin', 'WITH_AVX': 'ON', 'MAIN_ROOT': '/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'FLAGS_allocator_strategy': 'naive_best_fit', 'PATH': '/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop:/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/utils:/usr/local/python3.7.0/bin:/usr/local/python3.7.0/include:/home/cmake-3.16.0-Linux-x86_64/bin:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/gopath/bin', 'PWD': '/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/examples/wenetspeech/asr1', 'CUDA_VISIBLE_DEVICES': '0,1', 'LANG': 'en_US.UTF-8', 'CUDA_PKG_VERSION': '10-2=10.2.89-1', 'CUDA_VERSION': '10.2.89', 'PYTHONDONTWRITEBYTECODE': '1', 'SHLVL': '3', 'HOME': '/root', 'LANGUAGE': 'en_US.UTF-8', 'GOROOT': '/usr/local/go', 'GREP_OPTIONS': '--color=auto', 'NCCL_VERSION': '2.8.3', 'PYTHONPATH': '/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop:', 'GOPATH': '/root/gopath', 'WITH_GPU': 'ON', '_': '/usr/local/bin/python3', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'POD_NAME': 'ipvtqs', 'PADDLE_MASTER': '172.17.0.5:41620', 'PADDLE_GLOBAL_SIZE': '2', 'PADDLE_LOCAL_SIZE': '2', 'PADDLE_GLOBAL_RANK': '1', 'PADDLE_LOCAL_RANK': '1', 'PADDLE_NNODES': '1', 'PADDLE_CURRENT_ENDPOINT': '172.17.0.5:41622', 'PADDLE_TRAINER_ID': '1', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_RANK_IN_NODE': '1', 'PADDLE_TRAINER_ENDPOINTS': '172.17.0.5:41621,172.17.0.5:41622', 'FLAGS_selected_gpus': '1'}
LAUNCH INFO 2023-07-28 06:33:48,633 ------------------------- ERROR LOG DETAIL -------------------------
 (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paddle/io/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 108, in get
2023-07-28 06:33:45.265 | ERROR    | paddlespeech.s2t.exps.u2.model:do_train:217 - (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at ../paddle/fluid/operators/reader/blocking_queue.h:175)

    raise Empty2023-07-28 06:33:45.276 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Epoch-Train Time Cost: 4:25:36.522684

Traceback (most recent call last):
  File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/bin/train.py", line 46, in <module>
_queue.Empty2023-07-28 06:33:45.276 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Training Done: 4:25:43.693273


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    pr.runcall(main, config, args)
  File "/usr/lib/python3.8/cProfile.py", line 124, in runcall
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
        return func(*args, **kw)self._target(*self._args, **self._kwargs)

  File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/bin/train.py", line 32, in main
  File "/usr/local/lib/python3.8/dist-packages/paddle/io/dataloader/dataloader_iter.py", line 604, in _thread_loop
    main_sp(config, args)
  File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/bin/train.py", line 28, in main_sp
    batch = self._get_data()
  File "/usr/local/lib/python3.8/dist-packages/paddle/io/dataloader/dataloader_iter.py", line 708, in _get_data
    exp.run()
      File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/training/trainer.py", line 351, in run
raise RuntimeError(
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 151
    self.do_train()
  File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/model.py", line 218, in do_train
    raise e
  File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/s2t/exps/u2/model.py", line 184, in do_train
    for batch_index, batch in enumerate(self.train_loader):
  File "/home/PaddleSpeech/4756b3140789/PaddleSpeech-develop/paddlespeech/audio/streamdata/pipeline.py", line 67, in iterator
    for sample in self.iterator1():
  File "/usr/local/lib/python3.8/dist-packages/paddle/io/dataloader/dataloader_iter.py", line 826, in __next__
    self._reader.read_next_list()[0]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at ../paddle/fluid/operators/reader/blocking_queue.h:175)

LAUNCH INFO 2023-07-28 06:33:49,234 Exit code -15
```

### 其他
是我的数据集问题？还是环境硬件问题？还请帮忙，多谢

**Comment by zxcd** [comment]
是否为内存不够？

**Comment by Chuyaoyuan** [comment]
> 是否为内存不够？

@zxcd 我们的机器内存为128G，显卡为Tesla T4 16G * 2 （batch_size: 16），这个配置训练wenetspeech数据集会内存不够吗，或者可以调整哪个参数，在训练时适当减少内存占用，多谢

**Comment by Tian14267** [comment]
@Chuyaoyuan 我也遇到类似问题。也看到这篇：https://blog.csdn.net/qq_37668436/article/details/114336142
但是还是不知道咋解决~~~~

**Comment by ainndejj11** [comment]
> > 是否为内存不够？
> 
> @zxcd 我们的机器内存为128G，显卡为Tesla T4 16G * 2 （batch_size: 16），这个配置训练wenetspeech数据集会内存不够吗，或者可以调整哪个参数，在训练时适当减少内存占用，多谢

请问解决了么

**Comment by Chuyaoyuan** [comment]
> > > 是否为内存不够？
> > 
> > 
> > @zxcd 我们的机器内存为128G，显卡为Tesla T4 16G * 2 （batch_size: 16），这个配置训练wenetspeech数据集会内存不够吗，或者可以调整哪个参数，在训练时适当减少内存占用，多谢
> 
> 请问解决了么

并没有，目前在尝试 减少配置文件 conformer.yaml 的batch_size 和num_workers，看会不会稳定一些

**Comment by Chuyaoyuan** [comment]
> @Chuyaoyuan 我也遇到类似问题。也看到这篇：https://blog.csdn.net/qq_37668436/article/details/114336142 但是还是不知道咋解决~~~~

@Tian14267  感谢分享，看文章说 要调整 paddle 的 dataloader处理，还不知道在哪里修改，麻烦问下 你那训练 wenetspeech数据集 完成了吗，还是训练的其他数据集，是否顺利呢

**Comment by ainndejj11** [comment]
我是训练时候没问题，然后单个音频推理时候，有这个错误的。
后来我把paddlepaddle-gpu换成老版本的2.3.2   就能正常推理音频了。  训练还是用paddlepaddle-gpu==2.5.1
