### ISSUE TITLE
[S2T] paddlespeech 1.4.1 在Paddle 2.5.1环境中 示例跑不通

### ISSUE THREAD

**Issue by geniuszxd** [PaddlePaddle/PaddleSpeech#3442]
换了三台机器，捣鼓了一天时间

环境：
Windows10 / 11
Python 3.10
Paddle 2.5.1 GPU版 （conda install paddlepaddle-gpu==2.5.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge）
paddlespeech 1.4.1 （pip install paddlespeech）

问题：

1
运行 paddlespeech asr --input zh.wav，先是抛出了一个numpy异常：module 'numpy' has no attribute 'complex'
卸掉1.24，重装1.23解决。

2
继续paddlespeech asr --input zh.wav，另一个问题：
Traceback (most recent call last):
  File "D:\Python\envs\Paddle_GPU\lib\site-packages\paddlespeech\cli\asr\infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "D:\Python\envs\Paddle_GPU\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Python\envs\Paddle_GPU\lib\site-packages\paddle\fluid\dygraph\base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "D:\Python\envs\Paddle_GPU\lib\site-packages\paddlespeech\s2t\models\u2\u2.py", line 818, in decode
    hyp = self.attention_rescoring(
  File "D:\Python\envs\Paddle_GPU\lib\site-packages\paddlespeech\s2t\models\u2\u2.py", line 532, in attention_rescoring
    assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range
KeyError: 'result'

paddlespeech 1.4.1在paddle 2.4.2.post117下是能跑通示例的。但是还有其他乱七八糟依赖库的不兼容问题。

**Comment by momei123** [comment]
same problem

**Comment by cooolinx** [comment]
same issure here

**Comment by cooolinx** [comment]
I have resolved this problem by installing paddlepaddle-gpu, see 
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

if the problem still there, try this: https://github.com/PaddlePaddle/Paddle/issues/53775#issuecomment-1545772337

**Comment by zxcd** [comment]
如果需要使用paddlepaddle>=2.5.0 尽可能使用paddlespeech==develop对应。
paddle在新版本中更新了一些内容，这些内容paddlespeech加到了develop里面，还没有合入正式版本。

**Comment by cooolinx** [comment]
> 如果需要使用paddlepaddle>=2.5.0 尽可能使用paddlespeech==develop对应。 paddle在新版本中更新了一些内容，这些内容paddlespeech加到了develop里面，还没有合入正式版本。

感谢，我这边成功了。在官方 https://github.com/PaddlePaddle/PaddleSpeech#readme 的流程中，安装 PaddleSpeech 时，官方是直接安装，改成用当前代码库编译即可。
（另外安装 PaddlePaddle 时，官方是直接安装，而我是CUDA 12.0 ，所以只能在 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html 里安装 paddlepaddle-gpu 2.5.1 ，用官方直接装的不知道行不行）

思路就是大佬提示的，PaddleSpeech 当前 PyPI 的最新版本是 1.4.1 https://pypi.org/project/paddlespeech/#history 为 2023.3.16 发布；相比之下 PaddlePaddle 是 2.5.1，在7月27日发布，其中可能有兼容性问题。

所以要么降低 PaddlePaddle 版本要么提高 PaddleSpeech 版本，由于我的GPU是CUDA12.0，PaddlePaddle 2.5.0以上才支持，所以我只能升级 PaddleSpeech，也就是用当前库内代码安装。也许把 PaddlePaddle 版本降低到 2.4.2 （2023.2发布）也可以？

**Comment by cjjcn** [comment]
same problem

**Comment by pangdahua** [comment]
@cooolinx LGTM

**Comment by 450586509** [comment]
same problem

**Comment by yi1z** [comment]
> > 如果需要使用paddlepaddle>=2.5.0 尽可能使用paddlespeech==develop对应。 paddle在新版本中更新了一些内容，这些内容paddlespeech加到了develop里面，还没有合入正式版本。
> 
> 感谢，我这边成功了。在官方 https://github.com/PaddlePaddle/PaddleSpeech#readme 的流程中，安装 PaddleSpeech 时，官方是直接安装，改成用当前代码库编译即可。 （另外安装 PaddlePaddle 时，官方是直接安装，而我是CUDA 12.0 ，所以只能在 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html 里安装 paddlepaddle-gpu 2.5.1 ，用官方直接装的不知道行不行）
> 
> 思路就是大佬提示的，PaddleSpeech 当前 PyPI 的最新版本是 1.4.1 https://pypi.org/project/paddlespeech/#history 为 2023.3.16 发布；相比之下 PaddlePaddle 是 2.5.1，在7月27日发布，其中可能有兼容性问题。
> 
> 所以要么降低 PaddlePaddle 版本要么提高 PaddleSpeech 版本，由于我的GPU是CUDA12.0，PaddlePaddle 2.5.0以上才支持，所以我只能升级 PaddleSpeech，也就是用当前库内代码安装。也许把 PaddlePaddle 版本降低到 2.4.2 （2023.2发布）也可以？

确实是可以，我paddlepaddle降到2.4.2，paddlespeech 1.4.1就能用了
Dropping paddlepaddle to 2.4.2 and having paddlespeech to 1.4.1 does solve my problem XD

**Comment by ys830** [comment]
> > 如果需要使用paddlepaddle>=2.5.0 尽可能使用paddlespeech==develop对应。 paddle在新版本中更新了一些内容，这些内容paddlespeech加到了develop里面，还没有合入正式版本。
> 
> 感谢，我这边成功了。在官方 https://github.com/PaddlePaddle/PaddleSpeech#readme 的流程中，安装 PaddleSpeech 时，官方是直接安装，改成用当前代码库编译即可。 （另外安装 PaddlePaddle 时，官方是直接安装，而我是CUDA 12.0 ，所以只能在 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html 里安装 paddlepaddle-gpu 2.5.1 ，用官方直接装的不知道行不行）
> 
> 思路就是大佬提示的，PaddleSpeech 当前 PyPI 的最新版本是 1.4.1 https://pypi.org/project/paddlespeech/#history 为 2023.3.16 发布；相比之下 PaddlePaddle 是 2.5.1，在7月27日发布，其中可能有兼容性问题。
> 
> 所以要么降低 PaddlePaddle 版本要么提高 PaddleSpeech 版本，由于我的GPU是CUDA12.0，PaddlePaddle 2.5.0以上才支持，所以我只能升级 PaddleSpeech，也就是用当前库内代码安装。也许把 PaddlePaddle 版本降低到 2.4.2 （2023.2发布）也可以？

你好，请问是如何用当前库内代码安装的呀，我按照官方教程

> git clone https://github.com/PaddlePaddle/PaddleSpeech.git
> cd PaddleSpeech
> pip install pytest-runner
> pip install .
发现安装的paddlespeech是0.0.0版本，运行时也会报错，大佬按照库内代码安装的是什么版本呢

**Comment by lihuikenny** [comment]
> > > 如果需要使用paddlepaddle>=2.5.0 尽可能使用paddlespeech==develop对应。 paddle在新版本中更新了一些内容，这些内容paddlespeech加到了develop里面，还没有合入正式版本。
> > 
> > 
> > 感谢，我这边成功了。在官方 https://github.com/PaddlePaddle/PaddleSpeech#readme 的流程中，安装 PaddleSpeech 时，官方是直接安装，改成用当前代码库编译即可。 （另外安装 PaddlePaddle 时，官方是直接安装，而我是CUDA 12.0 ，所以只能在 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html 里安装 paddlepaddle-gpu 2.5.1 ，用官方直接装的不知道行不行）
> > 思路就是大佬提示的，PaddleSpeech 当前 PyPI 的最新版本是 1.4.1 https://pypi.org/project/paddlespeech/#history 为 2023.3.16 发布；相比之下 PaddlePaddle 是 2.5.1，在7月27日发布，其中可能有兼容性问题。
> > 所以要么降低 PaddlePaddle 版本要么提高 PaddleSpeech 版本，由于我的GPU是CUDA12.0，PaddlePaddle 2.5.0以上才支持，所以我只能升级 PaddleSpeech，也就是用当前库内代码安装。也许把 PaddlePaddle 版本降低到 2.4.2 （2023.2发布）也可以？
> 
> 你好，请问是如何用当前库内代码安装的呀，我按照官方教程
> 
> > git clone https://github.com/PaddlePaddle/PaddleSpeech.git
> > cd PaddleSpeech
> > pip install pytest-runner
> > pip install .
> > 发现安装的paddlespeech是0.0.0版本，运行时也会报错，大佬按照库内代码安装的是什么版本呢

这个问题解决了吗？我也是这样
