### ISSUE TITLE
[S2T]Mac 系统运行 S2T 报错

### ISSUE THREAD

**Issue by 0xBayMax** [PaddlePaddle/PaddleSpeech#3452]
Traceback (most recent call last):
  File "/Users/x/Library/Python/3.8/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/paddlespeech/cli/asr/__init__.py", line 14, in <module>
    from .infer import ASRExecutor
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/paddlespeech/cli/asr/infer.py", line 24, in <module>
    import librosa
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/librosa/core/__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/librosa/core/constantq.py", line 1059, in <module>
    dtype=np.complex,
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by zxcd** [comment]
看起来是librosa的版本问题
