### ISSUE TITLE
关于推理时，openssl的报错问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleSpeech#3454]
anaconda创建的python=3.8的虚拟环境  默认openssl是3.x的版本。执行推理命令paddlespeech asr --lang zh --input zh.wav
然后会出现以下报错：

Error: Can not import paddle core while this file exists: /home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/paddle_speech/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddlespeech/cli/base_commands.py", line 20, in <module>
    from ..resource import CommonTaskResource
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddlespeech/cli/utils.py", line 26, in <module>
    import paddle
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

然后重新创建虚拟环境，指定openssl版本： conda create -n test python=3.8 openssl=1.1.1  后，查询openssl version   显示确实是1.1.1v 版本了   但是执行命令  还是报这个错 。请问这个openssl的该如何解决呀

**Comment by lgscfronz** [comment]
请问是解决了吗？我这边碰到同样的问题

**Comment by ainndejj11** [comment]
> 

目录下终端输入这两行
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

**Comment by sudofeng** [comment]
> 目录下终端输入这两行 wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
可以了，很棒

**Comment by meoqi** [comment]
> > 
> 
> 目录下终端输入这两行 wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

这个地址似乎存在一些问题，我目前下载用的是 wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
