### ISSUE TITLE
测试deepspeech2 代码报错 example/aishell/asr0下 train报错

### ISSUE THREAD

**Issue by huangwentao123** [PaddlePaddle/PaddleSpeech#3455]
## 报错信息

2023-08-07 17:14:18.057 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Epoch-Train Time Cost: 0:00:05.856052
2023-08-07 17:14:18.058 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Training Done: 0:00:08.406099
Traceback (most recent call last):
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 49, in <module>
    main(config, args)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 29, in main
    main_sp(config, args)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 25, in main_sp
    exp.run()
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 351, in run
    self.do_train()
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 316, in do_train
    raise e
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 286, in do_train
    for batch_index, batch in enumerate(self.train_loader):
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
    self._reader.read_next_list()[0])
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:175)

## 环境
Python 3.8.6 (default, Jun 12 2023, 10:59:46) 

paddle-bfloat               0.1.7
paddle2onnx                 1.0.8
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.5.2
paddlepaddle-gpu            2.4.2
paddleslim                  2.4.1
paddlespeech                1.4.0
paddlespeech-ctcdecoders    0.2.1
paddlespeech-feat           0.1.0

## 额外
train之前报错过deepspeech2.yaml 的Dataloader少了属性参数，我就把online 的复制过来了。可能是这个问题。能不能提供一份完整的yaml模型配置。此外，文档中提供的模型ASR结果明显错误，可能是和模型yaml decode.yaml不适配的原因

## deepspeech2.yaml 
# https://yaml.org/type/float.html
###########################################
#                   Data                  #
###########################################
train_manifest: data/manifest.train
dev_manifest: data/manifest.dev
test_manifest: data/manifest.test
min_input_len: 0.0
max_input_len: 27.0 # second
min_output_len: 0.0
max_output_len: .inf
min_output_input_ratio: 0.00
max_output_input_ratio: .inf

###########################################
#              Dataloader                 #
###########################################
batch_size: 64 # one gpu
maxlen_in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen_out: 150  # if output length > maxlen-out, batchsize is automatically reduced
minibatches: 0 # for debug
mean_std_filepath: data/mean_std.json
unit_type: char
batch_count: auto
batch_bins: 0 
batch_frames_in: 0
batch_frames_out: 0
batch_frames_inout: 0
vocab_filepath: data/lang_char/vocab.txt 
augmentation_config: conf/augmentation.json
preprocess_config: conf/preprocess.yaml
random_seed: 0
spm_model_prefix: 
spectrum_type: linear
feat_dim: 161
delta_delta: False
stride_ms: 10.0
window_ms: 20.0
n_fft: None
max_freq: None
target_sample_rate: 16000
use_dB_normalization: True
target_dB: -20
dither: 1.0
keep_transcription_text: False
sortagrad: True
shuffle_method: batch_shuffle
num_workers: 2
subsampling_factor: 1
num_encs: 1

############################################
#           Network Architecture           #
############################################
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 1024
use_gru: True 
share_rnn_weights: False
blank_id: 0
ctc_grad_norm_type: instance 
rnn_direction: forward # [forward, bidirect]
num_fc_layers: 0
fc_layers_size_list: -1,

###########################################
#                Training                 #
###########################################
n_epoch: 80
accum_grad: 1
lr: 2.0e-3
lr_decay: 0.83
weight_decay: 1.0e-6
global_grad_clip: 3.0
log_interval: 100
checkpoint:
  kbest_n: 50
  latest_n: 5

**Comment by huangwentao123** [comment]
## 真正报错信息
如下所示，是不是版本的问题，我用的代码为 r1.4 分支的example 

Traceback (most recent call last):
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/fluid/dataloader/worker.py", line 339, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/io/dataset.py", line 120, in __getitem__
    return self.converter([self.reader(self.data[idx], return_uttid=True)])
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/io/reader.py", line 154, in __call__
    return_batch[x_name] = self.preprocessing(
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/audio/transform/transformation.py", line 142, in __call__
    xs = [
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/audio/transform/transformation.py", line 143, in <listcomp>
    func(x, u, **_kwargs)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/audio/transform/cmvn.py", line 197, in __call__
    x = np.subtract(x, self.mean)
ValueError: operands could not be broadcast together with shapes (346,161) (80,)

**Comment by huangwentao123** [comment]
想了一下，大概是默认处理为161维的feat，mean文件图省事 用conformer模型的预处理结果（80feat_dim）用了，才有报错，待会改改试试看

**Comment by huangwentao123** [comment]
## 修改feat后新报错
想再问一下，对同样的数据集 ，为什么deepspeech和conformer的feat_dim 设置不同？？？
  [Hint: Expected weights_size_ == sizeof(T) * weight_numel_, but received weights_size_:27942912 != sizeof(T) * weight_numel_:20078592.] (at /paddle/paddle/phi/kernels/gpu/rnn_functor.h:186)
  [operator < rnn > error]
2023-08-07 18:09:21.394 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Epoch-Train Time Cost: 0:00:02.089624
Traceback (most recent call last):
2023-08-07 18:09:21.394 | INFO     | paddlespeech.s2t.training.timer:__exit__:44 - Training Done: 0:00:07.045577
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 49, in <module>
    main(config, args)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 29, in main
    main_sp(config, args)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 25, in main_sp
    exp.run()
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 351, in run
    self.do_train()
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 316, in do_train
    raise e
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 295, in do_train
    self.train_batch(batch_index, batch, msg)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/model.py", line 54, in train_batch
    loss = self.model(audio, audio_len, text, text_len)
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/models/ds2/deepspeech2.py", line 290, in forward
    eouts, eouts_len, final_state_h_box, final_state_c_box = self.encoder(
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/hwt/demo-ml/PaddleSpeech/paddlespeech/s2t/models/ds2/deepspeech2.py", line 130, in forward
    x, final_state = self.rnn[i](x, init_state_list[i],
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/nn/layer/rnn.py", line 1082, in forward
    return self._cudnn_impl(inputs, initial_states, sequence_length)
  File "/root/hwt/py3env/lib/python3.8/site-packages/paddle/nn/layer/rnn.py", line 1016, in _cudnn_impl
    _, _, out, state = _legacy_C_ops.rnn(
ValueError: (InvalidArgument) The cudnn rnn and setting weight size should be same.
  [Hint: Expected weights_size_ == sizeof(T) * weight_numel_, but received weights_size_:27942912 != sizeof(T) * weight_numel_:20078592.] (at /paddle/paddle/phi/kernels/gpu/rnn_functor.h:186)
  [operator < rnn > error]
