### ISSUE TITLE
Deepspeech2：Stage3出错！argparse.ArgumentError: argument --result_file: conflicting option string: --result_file

### ISSUE THREAD

**Issue by policemanxxx** [PaddlePaddle/PaddleSpeech#3464]
【过程】
0 Process data -> 1 Train the mode -> 2 Get the final model -> 3 Test the final model performance

【错误描述】
通过命令 bash run.sh --stage 3 --stop_stage 3进行Stage3。
无法正确执行，尝试各种方法无果，请求协助！

【环境变量】
cuda11.2
paddleaudio 1.0.2
paddlepaddle-gpu 2.5.0
paddlespeech 0.0.0

【具体报错如下】
(asr38) root@station-Super-Server:/home/chenwh/ai/PaddleSpeech/examples/aishell/asr0# bash run.sh --stage 3 --stop_stage 3
checkpoint name deepspeech2
using 1 gpus...
Start downloading the language model. The language model is large, please wait for a moment ...
Download the language model sucessfully
----------- format_rsl.py Configuration Arguments -----------
origin_hyp: 
origin_ref: data/manifest.test.raw
trans_hyp: 
trans_hyp_sclite: 
trans_ref: data/manifest.test.text
trans_ref_sclite: 
transform_hyp output: data/manifest.test.text
Traceback (most recent call last):
  File "/home/chenwh/ai/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/test.py", line 36, in <module>
    parser.add_argument(
  File "/root/anaconda3/envs/asr38/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/root/anaconda3/envs/asr38/lib/python3.8/argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "/root/anaconda3/envs/asr38/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/root/anaconda3/envs/asr38/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/root/anaconda3/envs/asr38/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/root/anaconda3/envs/asr38/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --result_file: conflicting option string: --result_file
Failed in evaluation!

**Comment by policemanxxx** [comment]
rename result_file

**Comment by policemanxxx** [comment]
rename result_file

**Comment by ainndejj11** [comment]
> rename result_file

请问解决了么，应该在哪里修改
