### ISSUE TITLE
[S2T]使用自己录制的音频进行stream asr报错

### ISSUE THREAD

**Issue by ScottXiao233** [PaddlePaddle/PaddleSpeech#3475]
环境为：`registry.baidubce.com/paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4`
录制的音频已经通过Adobe Audition把sample rate改为了16000
已经成功运行了`punc_server.py`和`streaming_asr_server.py`，配置文件中也都是16000的sample_rate
将websocket_client.py中的”--wavfile“的路径写的就是我自己录制的音频。运行后报错：
```
Traceback (most recent call last):
  File "websocket_client.py", line 88, in <module>
    main(args)
  File "websocket_client.py", line 40, in main
    result = loop.run_until_complete(handler.run(args.wavfile))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/utils/audio_handler.py", line 166, in run
    for chunk_data in self.read_wave(wavfile_path):
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/server/utils/audio_handler.py", line 121, in read_wave
    padded_x = np.concatenate([samples, padding], axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
```

**Comment by ScottXiao233** [comment]
找到问题了，因为我的音频是左右声道的，输入文件只能是单声道的。
