### ISSUE TITLE
cuda 12.1 ，运行时报错

### ISSUE THREAD

**Issue by sudofeng** [PaddlePaddle/PaddleSpeech#3480]
我的是cuda 是12.1 ，官网文档最新是12.0 ，所以我安装了cuda 12.0 ，导入的时候报错。
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by sudofeng** [comment]
[解决了](https://github.com/PaddlePaddle/PaddleSpeech/issues/3454#issuecomment-1680415563)
