### ISSUE TITLE
  PreconditionNotMetError: The third-party dynamic library (libcublas.so) that Paddle depends on is not configured correctly. (error code is libcublas.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by sudofeng** [PaddlePaddle/PaddleSpeech#3482]
(paddlespeech) quanlian@quanlian3060:~/aigc/PaddleSpeech$ python
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0817 17:37:56.241706 2912090 interpretercore.cc:237] New Executor is Running.
W0817 17:37:56.241897 2912090 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 12.0
W0817 17:37:56.242406 2912090 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/utils/install_check.py", line 249, in run_check
    _run_static_single(use_cuda, use_xpu)
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/utils/install_check.py", line 147, in _run_static_single
    exe.run(
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1618, in _run_impl
    ret = new_exe.run(
  File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>

    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/nn/functional/common.py", line 1860, in linear
      helper.append_op(
    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/home/quanlian/mambaforge/envs/paddlespeech/lib/python3.10/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The third-party dynamic library (libcublas.so) that Paddle depends on is not configured correctly. (error code is libcublas.so: cannot open shared object file: No such file or directory)
      Suggestions:
      1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
      2. Configure third-party dynamic library environment variables as follows:
      - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
      - Windows: set PATH by `set PATH=XXX; (at ../paddle/phi/backends/dynload/dynamic_loader.cc:300)
      [operator < matmul_v2 > error]

**Comment by sudofeng** [comment]
conda，cuda12.1 ,但是根据官网文档最新支持的是12.0  ，是因为这个原因么？
