### ISSUE TITLE
docker paddle-> 2.5.1镜像安装 paddleSpeech 1.4.0 版本 启动demos/speech_web/speech_server/main.py 报错，求助

### ISSUE THREAD

**Issue by shujuncernet** [PaddlePaddle/PaddleSpeech#3499]
采用docker paddle-> 2.5.1镜像安装编译 paddleSpeech 1.4.0 版本的，启动 demos/speech_web/speech_server/main.py 的时候，报如下错误，求助原因：

[2023-09-05 01:14:41,309] [ WARNING] - The sample rate of the input file is not 16000.
                             The program will resample the wav file to 16000.
                             If the result does not meet your expectations，
                             Please input the 16k 16 bit 1 channel wav file.                         
[2023-09-05 01:14:41,917] [   ERROR] - list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/asr/infer.py", line 323, in infer
    simulate_streaming=cfg.simulate_streaming)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 826, in decode
    reverse_weight=reverse_weight)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 532, in attention_rescoring
    assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    asr_config, tts_config, asr_init_path, ie_model_path=ie_model_path)
  File "/opt/paddle/PaddleSpeech/demos/speech_web/speech_server/src/robot.py", line 26, in __init__
    self.warm_up_asrmodel(asr_init_path)
  File "/opt/paddle/PaddleSpeech/demos/speech_web/speech_server/src/robot.py", line 44, in warm_up_asrmodel
    force_yes=True)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/asr/infer.py", line 512, in __call__
    res = self.postprocess()  # Retrieve result of asr.
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/asr/infer.py", line 335, in postprocess
    return self._outputs["result"]
KeyError: 'result'

**Comment by liduang** [comment]
我也是遇到这个问题，咋解决啊
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/37337756/ab45e893-23a7-4714-9ead-ccaeb87e1f0a)

**Comment by diaojinlong** [comment]
The sample rate of the input file is not 16000.
是不是音频文件不是16000Hz的导致的，用官方zh.wav文件试试呢

**Comment by achaosss** [comment]
改成paddlepaddle==2.4.2
