### ISSUE TITLE
 cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' 

### ISSUE THREAD

**Issue by xiaoyaoamiao** [PaddlePaddle/PaddleSpeech#3513]
(venv_ocr) (base) miaog001@C02DWCXFMD6M Downloads % paddlespeech asr --lang zh --input zh.wav
Traceback (most recent call last):
  File "/Users/miaog001/opt/anaconda3/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddlespeech/cli/base_commands.py", line 20, in <module>
    from ..resource import CommonTaskResource
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddlespeech/cli/utils.py", line 26, in <module>
    import paddle
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import) (/Users/miaog001/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/__init__.py)

**Comment by xiaoyaoamiao** [comment]
安装过程中没有报错，最后运行报错了。
另外gcc >= 4.8.5 怎么安装

**Comment by imomoe233** [comment]
解决了吗 我也有这个问题
