### ISSUE TITLE
[S2T] Index error: list index out of range

### ISSUE THREAD

**Issue by Yoloex** [PaddlePaddle/PaddleSpeech#3521]
I tried an inference with ReadMe's guide.
While doing inference, got the following error.

```terminal
Traceback (most recent call last):
  File "C:\Users\Elsa\anaconda3\envs\pytorch\lib\site-packages\paddlespeech\cli\asr\infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "C:\Users\Elsa\anaconda3\envs\pytorch\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\Elsa\anaconda3\envs\pytorch\lib\site-packages\paddle\fluid\dygraph\base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "C:\Users\Elsa\anaconda3\envs\pytorch\lib\site-packages\paddlespeech\s2t\models\u2\u2.py", line 818, in decode
    hyp = self.attention_rescoring(
  File "C:\Users\Elsa\anaconda3\envs\pytorch\lib\site-packages\paddlespeech\s2t\models\u2\u2.py", line 532, in attention_rescoring
    assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range
```
It seems the package wants the matched batch size. But while debugging, found even their type mismatched.

**To Reproduce**

```python
from paddlespeech.cli.asr.infer import ASRExecutor
asr = ASRExecutor()
result = asr(audio_file="zh.wav")
```
**Environment**
 - OS: Win 10
 - Python Version 3.10.12
 - PaddlePaddle Version 2.5.1

**Comment by OOXXXXOO** [comment]
这错误太离谱了。更新版本都不测试的吗

**Comment by 1416924176** [comment]
俺也一样出现了这个问题，顶一下

**Comment by neuxys** [comment]
[The same problem](https://github.com/PaddlePaddle/PaddleSpeech/issues/3523#issuecomment-1722232362) occurred while I was running. How did you solve this problem?

**Comment by yaowt05** [comment]
install paddlespeech via compiling from source, this happens on paddlepaddle>=2.5.0

**Comment by OOXXXXOO** [comment]
I have same issue , you should install from develop branch by source could work

**Comment by mrzjl** [comment]
在 site-packages/paddlespeech/cli/asr/infer.py
`audio_len = paddle.to_tensor(audio.shape[0])` 修改成 `audio_len = paddle.to_tensor(audio.shape[0]).unsqueeze(axis=0)`
