### ISSUE TITLE
[TTS]Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:593)

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#3534]
大神们好。我再训练TTS的时候，出现这个错误：
```
Exception in main training loop: (External) CUBLAS error(7). 
  [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:593)
  [operator < linear > error]
Traceback (most recent call last):
Exception in main training loop: (External) CUBLAS error(7). 
  [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:593)
  [operator < linear > error]
Traceback (most recent call last):
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 110, in update
    self.update_core(batch)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2_updater.py", line 86, in update_core
    before_outs, after_outs, d_outs, p_outs, e_outs, ys, olens, spk_logits = self.model(
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 573, in forward
    before_outs, after_outs, d_outs, p_outs, e_outs, spk_logits = self._forward(
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 110, in update
    self.update_core(batch)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 608, in _forward
    hs, _ = self.encoder(xs, x_masks)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2_updater.py", line 86, in update_core
    before_outs, after_outs, d_outs, p_outs, e_outs, ys, olens, spk_logits = self.model(
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/encoder.py", line 424, in forward
    xs, masks = self.encoders(xs, masks)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 573, in forward
    before_outs, after_outs, d_outs, p_outs, e_outs, spk_logits = self._forward(
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 608, in _forward
    hs, _ = self.encoder(xs, x_masks)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/repeat.py", line 25, in forward
    args = m(*args)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/encoder.py", line 424, in forward
    xs, masks = self.encoders(xs, masks)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/encoder_layer.py", line 99, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/repeat.py", line 25, in forward
    args = m(*args)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/attention.py", line 140, in forward
    q, k, v = self.forward_qkv(query, key, value)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/attention.py", line 72, in forward_qkv
    self.linear_q(query), [n_batch, -1, self.h, self.d_k])
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/encoder_layer.py", line 99, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 175, in forward
    out = F.linear(
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/attention.py", line 140, in forward
    q, k, v = self.forward_qkv(query, key, value)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/attention.py", line 72, in forward_qkv
    self.linear_q(query), [n_batch, -1, self.h, self.d_k])
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 175, in forward
    out = F.linear(
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
Trainer extensions will try to handle the extension. Then all extensions will finalize.Trainer extensions will try to handle the extension. Then all extensions will finalize.I0926 17:10:01.418354  6365 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
Traceback (most recent call last):
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 234, in <module>
    main()
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 228, in main
    dist.spawn(train_sp, (args, config), nprocs=args.ngpu)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 606, in spawn
    while not context.join():
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 413, in join
    self._throw_exception(error_index)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 431, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 0 terminated with the following error:
----------------------------------------------

```

**Environment (please complete the following information):**
 - OS: **centos7**
 - GCC/G++ Version
 - Python Version：**python 3.8**
 - PaddlePaddle Version：**2.4.1.post11.6**
 - GPU/DRIVER Informationo：**Tesla V100**
 - CUDA/CUDNN Version ：**cuda-11.6**

请问这个错误是啥情况啊

**Comment by Tian14267** [comment]
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/27938135/e4b9e287-d84f-40b9-a250-fa238d9490e8)

**Comment by Tian14267** [comment]
```
Trainer extensions will try to handle the extension. Then all extensions will finalize.Trainer extensions will try to handle the extension. Then all extensions will finalize.I0926 17:31:57.252800 16080 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
Traceback (most recent call last):
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 234, in <module>
    main()
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 228, in main
    dist.spawn(train_sp, (args, config), nprocs=args.ngpu)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 606, in spawn
    while not context.join():
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 413, in join
    self._throw_exception(error_index)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 431, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 361, in _func_wrapper
    result = func(*args)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 182, in train_sp
    trainer.run()
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 198, in run
    six.reraise(*exc_info)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/training/updaters/standard_updater.py", line 110, in update
    self.update_core(batch)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2_updater.py", line 86, in update_core
    before_outs, after_outs, d_outs, p_outs, e_outs, ys, olens, spk_logits = self.model(
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 573, in forward
    before_outs, after_outs, d_outs, p_outs, e_outs, spk_logits = self._forward(
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 608, in _forward
    hs, _ = self.encoder(xs, x_masks)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/encoder.py", line 424, in forward
    xs, masks = self.encoders(xs, masks)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/repeat.py", line 25, in forward
    args = m(*args)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/encoder_layer.py", line 99, in forward
    x = residual + self.dropout(self.self_attn(x_q, x, x, mask))
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/attention.py", line 140, in forward
    q, k, v = self.forward_qkv(query, key, value)
  File "/ultra/fffan/0_TTS/00_relevant_experiment/PaddleSpeech-develop/paddlespeech/t2s/modules/transformer/attention.py", line 72, in forward_qkv
    self.linear_q(query), [n_batch, -1, self.h, self.d_k])
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 175, in forward
    out = F.linear(
  File "/root/anaconda3/envs/paddle_py38/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
OSError: (External) CUBLAS error(7). 
  [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:593)
  [operator < linear > error]
```
