### ISSUE TITLE
tts微调， 不使用官方提供的libfstscript.so.13，自己安装openfst后微调报错

### ISSUE THREAD

**Issue by wmlgl** [PaddlePaddle/PaddleSpeech#3548]
这个文件依赖glib 2.23, 今天把系统搞蹦了两次-_-||。
第一次直接安装glib 2.23，导致系统崩溃，恢复了。
然后第二次指定prefix安装，也崩溃了，然后又恢复。
对c++不熟，centos7的系统，只能用glib2 2.17。
然后搜索看网上说用conda安装glib也会导致conda环境崩溃。
所以只能直接编译一个libfstscript.so才行了

**Comment by wmlgl** [comment]
找到了， 是openfst-1.8.1对吧

**Comment by wmlgl** [comment]
使用conda install openfst==1.8.1 安装了openfst, 然后把tools里重复的文件删除了，运行报错，生成的durations.txt是空的
```
check oov
get mfa result
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 69, in align_corpus
TypeError: 'NoneType' object is not subscriptable
[30039] Failed to execute script align
generate durations.txt
extract feature
16 1
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 7119.55it/s]
Done
Traceback (most recent call last):
  File "/home/backup/yangyp/ai/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 346, in <module>
    extract_feature(
  File "/home/backup/yangyp/ai/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 266, in extract_feature
    normalize(speech_scaler, pitch_scaler, energy_scaler, vocab_phones,
  File "/home/backup/yangyp/ai/PaddleSpeech/examples/other/tts_finetune/tts3/local/extract_feature.py", line 155, in normalize
    dataset = DataTable(
  File "/home/backup/yangyp/ai/PaddleSpeech/paddlespeech/t2s/datasets/data_table.py", line 47, in __init__
    assert len(data) > 0, "This dataset has no examples"
AssertionError: This dataset has no examples

```

但是样本有被处理：
```
./input/ljspeech_mini3/newdir
./input/ljspeech_mini3/newdir/LJ001-0001.wav
./input/ljspeech_mini3/newdir/LJ001-0001.txt
./input/ljspeech_mini3/newdir/LJ001-0002.wav
./input/ljspeech_mini3/newdir/LJ001-0002.txt
./input/ljspeech_mini3/newdir/LJ001-0004.wav
./input/ljspeech_mini3/newdir/LJ001-0004.txt
./input/ljspeech_mini3/newdir/LJ001-0005.wav
./input/ljspeech_mini3/newdir/LJ001-0005.txt
./input/ljspeech_mini3/newdir/LJ001-0006.wav
./input/ljspeech_mini3/newdir/LJ001-0006.txt
./input/ljspeech_mini3/newdir/LJ001-0008.wav
./input/ljspeech_mini3/newdir/LJ001-0008.txt
./input/ljspeech_mini3/newdir/LJ001-0009.wav
./input/ljspeech_mini3/newdir/LJ001-0009.txt
./input/ljspeech_mini3/newdir/LJ001-0011.wav
```

aligner/command_line/align.py 这个文件没看到再哪里

**Comment by wmlgl** [comment]
搞定了,安装了以下几个依赖：
```
openfst                   1.7.6
openblas                  0.3.21
openssl                   1.1.1w
kaldi                     5.5.1016
```
