### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by syg1996419** [PaddlePaddle/PaddleSpeech#3559]
## General Question

W1024 10:07:50.310557 266636 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W1024 10:07:50.312556 266636 dynamic_loader.cc:278] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "dect.py", line 14, in <module>
    result = asr(audio_file='./video/zh.wav')
  File "F:\paddleSpeech_develop\paddlespeech\cli\utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "F:\paddleSpeech_develop\paddlespeech\cli\asr\infer.py", line 504, in __call__
    self._init_from_path(model, lang, codeswitch, sample_rate, config,
  File "F:\paddleSpeech_develop\paddlespeech\cli\asr\infer.py", line 211, in _init_from_path
    model_class = self.task_resource.get_model_class(model_name)
  File "F:\paddleSpeech_develop\paddlespeech\resource\resource.py", line 115, in get_model_class
    ret.append(dynamic_import(import_path))
  File "F:\paddleSpeech_develop\paddlespeech\utils\dynamic_import.py", line 37, in dynamic_import
    m = importlib.import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\paddlespeech\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\paddleSpeech_develop\paddlespeech\s2t\models\u2\__init__.py", line 14, in <module>
    from .u2 import U2InferModel
  File "F:\paddleSpeech_develop\paddlespeech\s2t\models\u2\u2.py", line 43, in <module>
    from paddlespeech.s2t.modules.decoder import BiTransformerDecoder
  File "F:\paddleSpeech_develop\paddlespeech\s2t\modules\decoder.py", line 30, in <module>
    from paddlespeech.s2t.modules.attention import MultiHeadedAttention
  File "F:\paddleSpeech_develop\paddlespeech\s2t\modules\attention.py", line 40, in <module>
    class MultiHeadedAttention(nn.Layer):
  File "F:\paddleSpeech_develop\paddlespeech\s2t\modules\attention.py", line 96, in MultiHeadedAttention
    mask: paddle.Tensor=paddle.ones([0, 0, 0], dtype=paddle.bool)
  File "C:\ProgramData\Anaconda3\envs\paddlespeech\lib\site-packages\paddle\tensor\creation.py", line 750, in ones
    return fill_constant(value=1.0, shape=shape, dtype=dtype, name=name)
  File "C:\ProgramData\Anaconda3\envs\paddlespeech\lib\site-packages\paddle\fluid\layers\tensor.py", line 832, in fill_constant
    out = _C_ops.full(shape, float(value), dtype, place)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at D:\home\workspace\Paddle\paddle\phi\backends\dynload\dynamic_loader.cc:305)

**Comment by RechinW** [comment]
Suggestions:

1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
2. Configure third-party dynamic library environment variables as follows:

- Linux: set LD_LIBRARY_PATH by export LD_LIBRARY_PATH=...
- Windows: set PATH by `set PATH=XXX; (at D:\home\workspace\Paddle\paddle\phi\backends\dynload\dynamic_loader.cc:305)

**Comment by yvway** [comment]
我也碰到了一样的问题，请问如何解决呢？
