### ISSUE TITLE
[S2T] keyerror paddlespeech asr --lang zh --input zh.wav

### ISSUE THREAD

**Issue by Popukar0421** [PaddlePaddle/PaddleSpeech#3560]
我按照安装教程，环境都配好了，执行这个asr服务报错
W1025 11:49:38.739352 41545 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.6, Runtime API Version: 11.6
W1025 11:49:38.740468 41545 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
[2023-10-25 11:49:44,056] [   ERROR] - too many positional arguments
Traceback (most recent call last):
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddle/base/dygraph/base.py", line 350, in _decorate_function
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 818, in decode
    hyp = self.attention_rescoring(
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 543, in attention_rescoring
    hyps, encoder_out = self._ctc_prefix_beam_search(
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 424, in _ctc_prefix_beam_search
    encoder_out, encoder_mask = self._forward_encoder(
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 229, in _forward_encoder
    encoder_out, encoder_mask = self.encoder(
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/modules/encoder.py", line 189, in forward
    xs, chunk_masks, _, _ = layer(xs, chunk_masks, pos_emb, mask_pad)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/modules/encoder_layer.py", line 242, in forward
    x_att, new_att_cache = self.self_attn(
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1343, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/modules/attention.py", line 324, in forward
    q, k, v = self.forward_qkv(query, key, value)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/paddlespeech/s2t/modules/attention.py", line 82, in forward_qkv
    q = self.linear_q(query).view(n_batch, -1, self.h, self.d_k)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
  File "/root/anaconda3/envs/tts/lib/python3.8/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.8/inspect.py", line 2958, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
KeyError: 'result'

**Comment by Popukar0421** [comment]
飞浆系列包版本如下：
paddle2onnx                 1.1.0
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.6.1
paddlepaddle-gpu            0.0.0.post116
paddlesde                   0.2.5
paddleslim                  2.4.1
paddlespeech                0.0.0
paddlespeech-ctcdecoders    0.2.1
paddlespeech-feat           0.1.0

**Comment by zxcd** [comment]
duplicate with https://github.com/PaddlePaddle/PaddleSpeech/issues/3442

**Comment by luyao-cv** [comment]
一样的，用paddlepaddle-gpu 0.0.0，就会出现这样的问题，改成2.5.1就可以
