### ISSUE TITLE
训练 FastSpeech2 模型，执行run.sh时报错No such file or directory: 'pwg_baker_ckpt_0.4/pwg_default.yaml'

### ISSUE THREAD

**Issue by shadowlkx** [PaddlePaddle/PaddleSpeech#3566]
训练集拆分及训练语音模型已完成，
已生成dump和exp目录

执行语音合成报错
:~/PaddleSpeech/examples/csmsc/tts3# ./run.sh --stage 2 --stop-stage 2
Traceback (most recent call last):
  File "/root/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize.py", line 257, in <module>
    main()
  File "/root/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize.py", line 253, in main
    evaluate(args)
  File "/root/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/../synthesize.py", line 43, in evaluate
    with open(args.voc_config) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pwg_baker_ckpt_0.4/pwg_default.yaml'

且已按要求将baker_alignment_tone解压至run.sh同级目录
:~/PaddleSpeech/examples/csmsc/tts3# ll 
total 2136
drwxr-xr-x  7 root root    4096 10月 30 13:42 ./
drwxr-xr-x 13 root root    4096 10月 29 11:21 ../
drwxr-xr-x  3 root root    4096 10月 30 13:53 baker_alignment_tone/
drwxr-xr-x  2 root root    4096 10月 30 12:17 conf/
drwxr-xr-x  5 root root    4096 10月 30 13:26 dump/
-rw-r--r--  1 root root 2097388 10月 30 13:26 durations.txt
drwxr-xr-x  3 root root    4096 10月 30 13:42 exp/
drwxr-xr-x  2 root root    4096 10月 29 11:21 local/
-rwxr-xr-x  1 root root     377 10月 29 11:21 path.sh*
-rw-r--r--  1 root root   13807 10月 29 11:21 README_cn.md
-rw-r--r--  1 root root   16431 10月 29 11:21 README.md
-rwxr-xr-x  1 root root    5587 10月 29 11:21 run_cnndecoder.sh*
-rwxr-xr-x  1 root root    3696 10月 29 11:21 run.sh*
-rw-r--r--  1 root root    1403 10月 29 11:21 run_xpu.sh

请问是什么问题导致？

**Comment by shadowlkx** [comment]
下载声码器pwg_baker_ckpt_0.4.zip并解压到run.sh同级目录已解决
