### ISSUE TITLE
[S2T]语音转文字时提示系统找不到指定文件

### ISSUE THREAD

**Issue by chn112211** [PaddlePaddle/PaddleSpeech#3571]
Traceback (most recent call last):
  File "D:\kzj\PaddleSpeech-develop\kzj\test3.py", line 3, in <module>
    result = st(audio_file="en.wav")
  File "D:\kzj\PaddleSpeech-develop\paddlespeech\cli\utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "D:\kzj\PaddleSpeech-develop\paddlespeech\cli\st\infer.py", line 347, in __call__
    self.preprocess(audio_file, model)
  File "D:\kzj\PaddleSpeech-develop\paddlespeech\cli\st\infer.py", line 206, in preprocess
    fbank_extract_process = subprocess.Popen(
  File "C:\Users\keith\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 853, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\keith\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1306, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - GCC/G++ Version [6.3.0]
 - Python Version [3.8.5]
 - PaddlePaddle Version [2.4.1]
 - Model Version [e.g. 2.0.0]

**Additional context**
from paddlespeech.cli.st.infer import STExecutor
st = STExecutor()
result = st(audio_file="en.wav")
print(result)

**Comment by chn112211** [comment]
查找到之前的回答了，ST无法在win上运行。。。
