### ISSUE TITLE
Permission denied: 'git'

### ISSUE THREAD

**Issue by xxch** [PaddlePaddle/PaddleSpeech#3596]
在linux环境安装paddleSpeech1.4.1版本，使用了pyhton1.8和3.10都会报这样的错误。
`Building wheels for collected packages: paddlespeech
  Building wheel for paddlespeech (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      
      __version__ = '0.0.0'
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/app/paddle/PaddleSpeech/setup.py", line 331, in <module>
          with version_info():
        File "/app/anconda3/conda/envs/paddle38/lib/python3.8/contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "/app/paddle/PaddleSpeech/setup.py", line 247, in version_info
          write_version_py()
        File "/app/paddle/PaddleSpeech/setup.py", line 225, in write_version_py
          COMMITID = check_output("git rev-parse HEAD")
        File "/app/paddle/PaddleSpeech/setup.py", line 115, in check_output
          out_bytes = sp.check_output(cmd.split())
        File "/app/anconda3/conda/envs/paddle38/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/app/anconda3/conda/envs/paddle38/lib/python3.8/subprocess.py", line 493, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/app/anconda3/conda/envs/paddle38/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/app/anconda3/conda/envs/paddle38/lib/python3.8/subprocess.py", line 1720, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      PermissionError: [Errno 13] Permission denied: 'git'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for paddlespeech
  Running setup.py clean for paddlespeech
Failed to build paddlespeech
ERROR: Could not build wheels for paddlespeech, which is required to install pyproject.toml-based projects`

**Comment by xxch** [comment]
源码安装的方式

**Comment by skyboooox** [comment]
+1
windows 环境,dev源代码安装
