### ISSUE TITLE
[TTS]windows下启动报错

### ISSUE THREAD

**Issue by Coloryr** [PaddlePaddle/PaddleSpeech#3605]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
windows下启动`online-onnx`报错

**To Reproduce**
```
# -*- coding: utf-8 -*-

from paddlespeech.server.bin.paddlespeech_server import ServerExecutor

server_executor = ServerExecutor()
server_executor(
    config_file="./application.yaml", 
    log_file="./paddlespeech.log")
```

```
python main.py -X utf8
```

**Expected behavior**
```
PS E:\temp_code\server> python main.py -X utf8
E:\environment\python\lib\site-packages\paddleaudio\_extension.py:141: UserWarning: paddleaudio C++ extension is not available.
  warnings.warn("paddleaudio C++ extension is not available.")
[2023-11-22 10:10:19,579] [    INFO] - start to init the engine
[2023-11-22 10:10:19,580] [    INFO] - tts : online-onnx engine.
[2023-11-22 10:10:23,437] [   ERROR] - Failed to get model related files.
[2023-11-22 10:10:23,437] [   ERROR] - Initialize TTS server engine Failed on device: cpu.
Traceback (most recent call last):
  File "E:\environment\python\lib\site-packages\paddlespeech\server\engine\tts\online\onnx\tts_engine.py", line 235, in init      
    self.executor._init_from_path(
  File "E:\environment\python\lib\site-packages\paddlespeech\server\engine\tts\online\onnx\tts_engine.py", line 158, in _init_from_path
    phn_id = [line.strip().split() for line in f.readlines()]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 2088: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\temp_code\server\main.py", line 6, in <module>
    server_executor(
  File "E:\environment\python\lib\site-packages\paddlespeech\server\util.py", line 365, in _warpper
    return executor_func(self, *args, **kwargs)
  File "E:\environment\python\lib\site-packages\paddlespeech\server\bin\paddlespeech_server.py", line 116, in __call__
    if self.init(config):
  File "E:\environment\python\lib\site-packages\paddlespeech\server\bin\paddlespeech_server.py", line 89, in init
    if not init_engine_pool(config):
  File "E:\environment\python\lib\site-packages\paddlespeech\server\engine\engine_pool.py", line 38, in init_engine_pool
    if not ENGINE_POOL[engine].init(config=config[engine_and_type]):
  File "E:\environment\python\lib\site-packages\paddlespeech\server\engine\tts\online\onnx\tts_engine.py", line 254, in init      
    logger(e)
TypeError: Logger.__call__() missing 1 required positional argument: 'msg'
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windoes
 - GCC/G++ Version 无
 - Python Version 3.10
 - PaddlePaddle Version 最新
 - Model Version 最新
 - GPU/DRIVER Informationo 无
 - CUDA/CUDNN Version 无
 - MKL Version 无
- TensorRT Version 无

**Additional context**

**Comment by zxcd** [comment]
报错 UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 2088: illegal multibyte sequence
查一下你的输入文本格式是否为gbk
