### ISSUE TITLE
[S2T] ImportError: cannot import name 'sequence_mask' from 'paddle.fluid.layers' 

### ISSUE THREAD

**Issue by bestlee666** [PaddlePaddle/PaddleSpeech#3626]
- OS: Ubuntu 22.04
 - Python Version  3.11
 - PaddlePaddle Version   2.5.2

~/code/PaddleSpeech$ paddlespeech asr --lang zh --input zh.wav
Traceback (most recent call last):
  File "/home/lihuan/anaconda3/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/cli/__init__.py", line 23, in <module>
    from .tts import TTSExecutor
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/cli/tts/infer.py", line 36, in <module>
    from paddlespeech.t2s.frontend import English
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/t2s/__init__.py", line 19, in <module>
    from . import models
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/t2s/models/__init__.py", line 14, in <module>
    from .fastspeech2 import *
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/t2s/models/fastspeech2/__init__.py", line 14, in <module>
    from .fastspeech2 import *
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 28, in <module>
    from paddlespeech.t2s.modules.nets_utils import initialize
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/t2s/modules/__init__.py", line 16, in <module>
    from .losses import *
  File "/home/lihuan/anaconda3/lib/python3.11/site-packages/paddlespeech/t2s/modules/losses.py", line 20, in <module>
    from paddle.fluid.layers import sequence_mask
ImportError: cannot import name 'sequence_mask' from 'paddle.fluid.layers' (/home/lihuan/anaconda3/lib/python3.11/site-packages/paddle/fluid/layers/__init__.py)
(base) lihuan@lihuan:~/code/PaddleSpeech$

**Comment by zxcd** [comment]
version problem can follow: https://github.com/PaddlePaddle/PaddleSpeech/issues/3528
