### ISSUE TITLE
[S2T] bug crash

### ISSUE THREAD

**Issue by idreamerhx** [PaddlePaddle/PaddleSpeech#3653]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
quick start crash

**To Reproduce**
(5d25475b9480) root@5d25475b9480:/opt/quick-start# paddlespeech tts --input "hello" --output output.wav
W1220 14:30:21.064070   724 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.3, Runtime API Version: 11.8
W1220 14:30:21.066586   724 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
I1220 14:30:21.533761   724 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
I1220 14:30:21.534078   724 eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' . In order to avoid this problem, 0D Tensor will be changed to 1D numpy currently, but it's not correct and will be removed in release 2.6. For Tensor contain only one element, Please modify  'Tensor.numpy()[0]' to 'float(Tensor)' as soon as possible, otherwise 'Tensor.numpy()[0]' will raise error in release 2.6.
/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py:1897: UserWarning: Skip loading for encoder.embed.1.alpha. encoder.embed.1.alpha receives a shape [1], but the expected shape is [].
  warnings.warn(f"Skip loading for {key}. " + str(err))
/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py:1897: UserWarning: Skip loading for decoder.embed.0.alpha. decoder.embed.0.alpha receives a shape [1], but the expected shape is [].
  warnings.warn(f"Skip loading for {key}. " + str(err))
KeyError: 'phone_ids'

(5d25475b9480) root@5d25475b9480:/opt/quick-start# paddlespeech asr --lang zh --input zh.wav
W1220 14:35:27.887745   802 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.3, Runtime API Version: 11.8
W1220 14:35:27.889140   802 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
[2023-12-20 14:35:29,613] [   ERROR] - list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/cli/asr/infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 818, in decode
    hyp = self.attention_rescoring(
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 532, in attention_rescoring
    assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
root@5d25475b9480:/opt/quick-start# pip list |grep -i paddle
paddle2onnx                 1.1.0
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.6.1
paddlepaddle-gpu            2.5.2
paddlesde                   0.2.5
paddleslim                  2.4.1
paddlespeech                1.4.1
paddlespeech-ctcdecoders    0.2.0
paddlespeech-feat           0.1.0

**Additional context**

**Comment by idreamerhx** [comment]
我目前能成功启动asr quick statrt的方法描述下：
镜像：paddlecloud/paddlespeech   develop-gpu-cuda10.2-cudnn7-latest   785d98ebc121 
pip install paddlepaddle==2.4.2 paddlespeech==1.4.1

原始镜像本身运行报错。另外试过匹配paddle gpu的 cu121  cu118等环境 github源码安装都报错。

目前我找到的唯一安心好用的开源asr tts  希望大佬们维护下去啊。

另主要是之前有一个能用的版本，但tts不能调语速，想看看最近一年有没有更新。

**Comment by idreamerhx** [comment]
paddlepaddle-gpu==2.4.2  显存可以加载 但python进程100% cpu，卡死
