### ISSUE TITLE
[S2T]argparse.ArgumentError: argument --audio_file: conflicting option string: --audio_file

### ISSUE THREAD

**Issue by xdchuan011209** [PaddlePaddle/PaddleSpeech#3658]
Traceback (most recent call last):
  File "/raid/ASR/paddlespeech/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py", line 174, in <module>
    parser.add_argument("--audio_file", type=str, help='audio file path')
  File "/home/shj/miniconda3/envs/Paddlenv/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/home/shj/miniconda3/envs/Paddlenv/lib/python3.8/argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "/home/shj/miniconda3/envs/Paddlenv/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/home/shj/miniconda3/envs/Paddlenv/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/home/shj/miniconda3/envs/Paddlenv/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/home/shj/miniconda3/envs/Paddlenv/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --audio_file: conflicting option string: --audio_file

**Comment by zxcd** [comment]
怎么用的 paddle和paddlespeech的版本分别是什么？
