### ISSUE TITLE
[TTS]UnicodeDecodeError: 'gbk' codec can't decode byte 0x96 in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by Darksiderlyd** [PaddlePaddle/PaddleSpeech#3663]
**Describe the bug**
Traceback (most recent call last):
File "D:\lvyaodong\python3\lib\runpy.py", line 196, in run_module_as_main
exec(code, run_globals)
File "D:\aiworkspace\PaddleSpeech.venv\Scripts\paddlespeech.exe_main.py", line 7, in
sys.exit(execute())
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\paddlespeech\cli\entry.py", line 40, in execute
exec("from {} import {}".format(module, cls))
File "", line 1, in
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\paddlespeech\cli\tts_init.py", line 14, in
from .infer import TTSExecutor
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\paddlespeech\cli\tts\infer.py", line 33, in
from paddlespeech.t2s.exps.syn_utils import get_am_inference
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\paddlespeech\t2s\exps\syn_utils.py", line 36, in
from paddlespeech.t2s.frontend.canton_frontend import CantonFrontend
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\paddlespeech\t2s\frontend\canton_frontend.py", line 19, in
import ToJyutping
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\ToJyutping_init.py", line 3, in
from .ToJyutping import *
File "D:\aiworkspace\PaddleSpeech.venv\lib\site-packages\ToJyutping\ToJyutping.py", line 9, in
for line in f:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x96 in position 2: illegal multibyte sequence

**To Reproduce**
`
from paddlespeech.cli.tts.infer import TTSExecutor

TEXT = str('今天天气十分不错。', 'utf-8')

tts = TTSExecutor()
tts(encodings='utf-8', text=TEXT, output="output.wav")
`

**Expected behavior**

**Screenshots**
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/20541921/5af0bace-d0cc-481f-9c44-d6bf41e0db06)

**Environment (please complete the following information):**
 - OS: Windows10
 - GCC/G++ Version [e.g. 8.3]
 - Python Version 3.10
 - PaddlePaddle Version 2.6-gpu
 - Model Version 
 - GPU/DRIVER Informationo [e.g. Tesla V100-SXM2-32GB/440.64.00]
 - CUDA/CUDNN Version  11.7/8.4.1
 - MKL Version
- TensorRT Version

**Additional context**

set PYTHONUTF8=1 没有用

**Comment by Darksiderlyd** [comment]
paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav   直接跑也不行

**Comment by Darksiderlyd** [comment]
解决了 之前用conda 安装的0.21的ToJyutping，卸载掉然后重新 pip install ToJyutping 再次运行就OK了，打扰了
