### ISSUE TITLE
请帮忙分析下报错：IndexError: (OutOfRange) The starting index 0 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [0, 0). (at ..\paddle/fluid/pybind/slice_utils.h:214)

### ISSUE THREAD

**Issue by quantbruce** [PaddlePaddle/PaddleSpeech#3665]
## General Question

E:\Anaconda\installation\envs\Audio\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2024-01-18 13:51:22,092] [    INFO] - Already cached C:\Users\47053\.paddlenlp\models\bert-base-chinese\bert-base-chinese-vocab.txt
[2024-01-18 13:51:22,105] [    INFO] - tokenizer config file saved in C:\Users\47053\.paddlenlp\models\bert-base-chinese\tokenizer_config.json
[2024-01-18 13:51:22,105] [    INFO] - Special tokens file saved in C:\Users\47053\.paddlenlp\models\bert-base-chinese\special_tokens_map.json
E:\Anaconda\installation\envs\Audio\lib\site-packages\paddle\nn\layer\layers.py:2084: UserWarning: Skip loading for encoder.embed.1.alpha. encoder.embed.1.alpha receives a shape [1], but the expected shape is [].
  warnings.warn(f"Skip loading for {key}. " + str(err))
E:\Anaconda\installation\envs\Audio\lib\site-packages\paddle\nn\layer\layers.py:2084: UserWarning: Skip loading for decoder.embed.0.alpha. decoder.embed.0.alpha receives a shape [1], but the expected shape is [].
  warnings.warn(f"Skip loading for {key}. " + str(err))
Building prefix dict from the default dictionary ...
[2024-01-18 13:51:31,117] [   DEBUG] __init__.py:113 - Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\47053\AppData\Local\Temp\jieba.cache
[2024-01-18 13:51:31,822] [   DEBUG] __init__.py:146 - Dumping model to file cache C:\Users\47053\AppData\Local\Temp\jieba.cache
Loading model cost 0.757 seconds.
[2024-01-18 13:51:31,875] [   DEBUG] __init__.py:164 - Loading model cost 0.757 seconds.
Prefix dict has been built successfully.
[2024-01-18 13:51:31,875] [   DEBUG] __init__.py:166 - Prefix dict has been built successfully.
Traceback (most recent call last):
  File "D:\Develop\Python\Audio\PaddleSpeech\demo.py", line 6, in <module>
    tts(text="今天天气十分不错。", output="output.wav")
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\cli\utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\cli\tts\infer.py", line 710, in __call__
    self.infer(text=text, lang=lang, am=am, spk_id=spk_id)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddle\base\dygraph\base.py", line 352, in _decorate_function
    return func(*args, **kwargs)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\cli\tts\infer.py", line 496, in infer
    mel = self.am_inference(part_phone_ids)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\models\fastspeech2\fastspeech2.py", line 920, in forward
    normalized_mel, d_outs, p_outs, e_outs = self.acoustic_model.inference(
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\models\fastspeech2\fastspeech2.py", line 810, in inference
    _, outs, d_outs, p_outs, e_outs, _ = self._forward(
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\models\fastspeech2\fastspeech2.py", line 601, in _forward
    x_masks = self._source_mask(ilens)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\models\fastspeech2\fastspeech2.py", line 891, in _source_mask
    x_masks = make_non_pad_mask(ilens)
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\modules\nets_utils.py", line 258, in make_non_pad_mask
    return paddle.logical_not(make_pad_mask(lengths, xs, length_dim))
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\modules\nets_utils.py", line 146, in make_pad_mask
    bs = paddle.shape(lengths)[0]
  File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddle\base\dygraph\tensor_patch_methods.py", line 896, in __getitem__
    return self._getitem_dygraph(item)
IndexError: (OutOfRange) The starting index 0 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [0, 0). (at ..\paddle/fluid/pybind/slice_utils.h:214)

**Comment by zyk-miao** [comment]
我也遇到了 这个

**Comment by zyk-miao** [comment]
楼主解决了吗

**Comment by zxcd** [comment]
你是修改了什么吗？
报错显示
```
File "E:\Anaconda\installation\envs\Audio\lib\site-packages\paddlespeech\t2s\modules\nets_utils.py", line 146, in make_pad_mask
bs = paddle.shape(lengths)[0]
```
这里的bs越界了，你可以看看paddle.shape(lengths)输出什么。

**Comment by zyk-miao** [comment]
![图片](https://github.com/PaddlePaddle/PaddleSpeech/assets/45023244/b8ede3b1-8271-4c12-aeb6-3e86fa9539f3)

**Comment by zyk-miao** [comment]
我debug paddle.shape(lengths)是截图中的。我没有修改任何代码
就只是根据示例
  from paddlespeech.cli.tts.infer import TTSExecutor
    tts = TTSExecutor()
    tts(text="今天天气十分不错。", output="output.wav")

**Comment by lijianxin520** [comment]
我尝试了一下，应该是版本高的问题；我使用paddlepaddle==2.4.0是可以。

**Comment by zyk-miao** [comment]
pip仓库没有2.4.0了

**Comment by zyk-miao** [comment]
paddlepaddle==2.5.1 测试可以了

**Comment by lixiaoxiangzhi** [comment]
我也遇到了，降低版本到2.6以下就可以了，语法的改变，运行2.6以下版本会有提示改变内容。

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。

**Comment by quantbruce** [comment]
好的，谢谢大家解答。
我再去试试

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。

**Comment by lixiaoxiangzhi** [comment]
您的来信已收到，祝您每天有个好心情。
