### ISSUE TITLE
[TTS] FileNotFoundError: [Errno 2] No such file or directory: 'dump/test/raw/metadata.jsonl'

### ISSUE THREAD

**Issue by Zzmes** [PaddlePaddle/PaddleSpeech#3752]
(PaddleSpeech) root@45ee9542141a:/zyyo/code/PaddleSpeech/examples/ljspeech/tts0# ./run.sh 
Generate durations.txt from MFA results ...
Extract features ...
100%|████████████████████████████████████████████████████████████████████████████████| 4434/4434 [00:30<00:00, 145.98it/s]
Done
Get features' stats ...
100%|███████████████████████████████████████████████████████████████████████████████| 4434/4434 [00:01<00:00, 2252.59it/s]
Normalize ...
100%|███████████████████████████████████████████████████████████████████████████████| 4434/4434 [00:02<00:00, 1916.70it/s]
Traceback (most recent call last):
  File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 124, in <module>
    main()
  File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 62, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/root/miniconda3/envs/PaddleSpeech/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 643, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/dev/raw/metadata.jsonl'
Traceback (most recent call last):
  File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 124, in <module>
    main()
  File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 62, in main
    with jsonlines.open(args.metadata, 'r') as reader:
  File "/root/miniconda3/envs/PaddleSpeech/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 643, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'dump/test/raw/metadata.jsonl'

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，你可以尝试通过修改 PaddleSpeech 源码的方式自己解决，或请求开源社区其他开发者的协助。飞桨开源社区交流频道：[飞桨AI Studio星河社区-人工智能学习与实训社区](https://aistudio.baidu.com/community/channel/306)

**Comment by wytyl13** [comment]
> (PaddleSpeech) root@45ee9542141a:/zyyo/code/PaddleSpeech/examples/ljspeech/tts0# ./run.sh Generate durations.txt from MFA results ... Extract features ... 100%|████████████████████████████████████████████████████████████████████████████████| 4434/4434 [00:30<00:00, 145.98it/s] Done Get features' stats ... 100%|███████████████████████████████████████████████████████████████████████████████| 4434/4434 [00:01<00:00, 2252.59it/s] Normalize ... 100%|███████████████████████████████████████████████████████████████████████████████| 4434/4434 [00:02<00:00, 1916.70it/s] Traceback (most recent call last): File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 124, in main() File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 62, in main with jsonlines.open(args.metadata, 'r') as reader: File "/root/miniconda3/envs/PaddleSpeech/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 643, in open fp = builtins.open(file, mode=mode + "t", encoding=encoding) FileNotFoundError: [Errno 2] No such file or directory: 'dump/dev/raw/metadata.jsonl' Traceback (most recent call last): File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 124, in main() File "/zyyo/code/PaddleSpeech/paddlespeech/t2s/exps/tacotron2/normalize.py", line 62, in main with jsonlines.open(args.metadata, 'r') as reader: File "/root/miniconda3/envs/PaddleSpeech/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 643, in open fp = builtins.open(file, mode=mode + "t", encoding=encoding) FileNotFoundError: [Errno 2] No such file or directory: 'dump/test/raw/metadata.jsonl'

我换了份数据进行训练，然后重新训练之前报错的数据，这个问题就解决了，应该是训练出错导致的缓存问题
我删除了训练缓存文件，无效
我想应该删除~/Documents/MFA
