### ISSUE TITLE
paddlespeech asr --lang zh --input zh.wav 报错: InvalidArgument

### ISSUE THREAD

**Issue by mjx1999** [PaddlePaddle/PaddleSpeech#3753]
- OS: [Ubuntu 22.4]
 - GCC 11.4.0
 - Python Version 3.10
 - PaddlePaddle 2.61
 - GPU  Tesla P40
 - CUDA/CUDNN 12.0

 选源码下载编译安装
git clone https://github.com/PaddlePaddle/PaddleSpeech.git
cd PaddleSpeech
pip install pytest-runner
pip install .

运行  paddlespeech asr --lang zh --input zh.wav 会报如下的错误:

W0425 10:54:48.787741 584456 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.4, Runtime API Version: 12.0
W0425 10:54:48.788694 584456 gpu_resources.cc:164] device: 0, cuDNN Version: 9.1.
[2024-04-25 10:54:50,736] [   ERROR] - (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:73)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/cli/asr/infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/dygraph/base.py", line 352, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 818, in decode
    hyp = self.attention_rescoring(
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 543, in attention_rescoring
    hyps, encoder_out = self._ctc_prefix_beam_search(
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 424, in _ctc_prefix_beam_search
    encoder_out, encoder_mask = self._forward_encoder(
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 229, in _forward_encoder
    encoder_out, encoder_mask = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/modules/encoder.py", line 184, in forward
    chunk_masks = add_optional_chunk_mask(
  File "/usr/local/lib/python3.10/dist-packages/paddlespeech/s2t/modules/mask.py", line 202, in add_optional_chunk_mask
    chunk_masks = masks.logical_and(chunk_masks)  # (B, L, L)
  File "/usr/local/lib/python3.10/dist-packages/paddle/tensor/logic.py", line 143, in logical_and
    return _C_ops.logical_and(x, y)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:73)

**Comment by mjx1999** [comment]
原代码的默认模型有错:
![QQ图片20240426124125](https://github.com/PaddlePaddle/PaddleSpeech/assets/8605647/856eb993-e41f-4c86-9341-00aa6202506a)
![QQ图片20240426124132](https://github.com/PaddlePaddle/PaddleSpeech/assets/8605647/6ff5dddd-d984-4cc9-9b9b-a9ad7f07692d)
