### ISSUE TITLE
使用时，报错: IndexError: list index out of range

### ISSUE THREAD

**Issue by hgguyu** [PaddlePaddle/PaddleSpeech#3754]
环境
python 3.9
paddlepaddle 2.6.1
paddlespeech 1.4.1

安装期间，已经解决了
1、setuptools_scm 报错问题
2、numpy 版本过高问题 : module 'numpy' has no attribute 'complex'  

使用时，报了下面错误: 
paddlespeech   asr --lang zh --input zh.wav
[2024-04-25 13:39:18,021] [   ERROR] - list index out of range
Traceback (most recent call last):
  File "/root/tools/venv/lib/python3.9/site-packages/paddlespeech/cli/asr/infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "/root/tools/venv/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/tools/venv/lib/python3.9/site-packages/paddle/base/dygraph/base.py", line 352, in _decorate_function
    return func(*args, **kwargs)
  File "/root/tools/venv/lib/python3.9/site-packages/paddlespeech/s2t/models/u2/u2.py", line 818, in decode
    hyp = self.attention_rescoring(
  File "/root/tools/venv/lib/python3.9/site-packages/paddlespeech/s2t/models/u2/u2.py", line 532, in attention_rescoring
    assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，建议参考：https://github.com/PaddlePaddle/PaddleSpeech/issues/3577

**Comment by yaowt05** [comment]
你的paddlepaddle版本太高了，只支持paddlepaddle<2.5.0的版本，需要通过源码编译的方式安装paddlespeech才可以支持高版本paddlepaddle

**Comment by yousun4688** [comment]
楼主  问题解决了吗 ？   我这边使用的2.5 和speech dev版本 也是报同样的错误
