### ISSUE TITLE
自定义语料训练报错

### ISSUE THREAD

**Issue by wytyl13** [PaddlePaddle/PaddleSpeech#3763]
调用./run.sh报错如下
get mfa result
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 69, in align_corpus
TypeError: 'NoneType' object is not subscriptable
[10918] Failed to execute script align

**Comment by jianghuakun** [comment]
混合语音报错，请问怎么解决？
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/77032736/392dad6e-2e09-4338-a1db-f11892e148ba)
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/77032736/638065d4-143c-483a-8576-e68694f17d7a)

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，你可以尝试通过修改 PaddleSpeech 源码的方式自己解决，或请求开源社区其他开发者的协助。飞桨开源社区交流频道：[飞桨AI Studio星河社区-人工智能学习与实训社区](https://aistudio.baidu.com/community/channel/306)

**Comment by wytyl13** [comment]
> 调用./run.sh报错如下 get mfa result align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. Traceback (most recent call last): File "aligner/command_line/align.py", line 186, in File "aligner/command_line/align.py", line 142, in validate_args File "aligner/command_line/align.py", line 69, in align_corpus TypeError: 'NoneType' object is not subscriptable [10918] Failed to execute script align

删除MFA缓存文件，应该是~/Documents/MFA

**Comment by wytyl13** [comment]
> ，请问怎么

混合模型名字写错了，应该在训练脚本中改正过来

**Comment by wytyl13** [comment]
> 混合语音报错，请问怎么解决？ ![image](https://private-user-images.githubusercontent.com/77032736/329757304-392dad6e-2e09-4338-a1db-f11892e148ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjg3MTUsIm5iZiI6MTcxNjAyODQxNSwicGF0aCI6Ii83NzAzMjczNi8zMjk3NTczMDQtMzkyZGFkNmUtMmUwOS00MzM4LWExZGItZjExODkyZTE0OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYTk1ZTZkNTUwYThmZWExM2FiOThhMzBmYzBiMTI3NDEwNTE0ODg3YWVmNWJkZWFiNzVlM2RlYTU5MTgzOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKfcpAKk8qAoQmASDIYU5E7CBadn4YvkTID-FlDYj98) ![image](https://private-user-images.githubusercontent.com/77032736/329757329-638065d4-143c-483a-8576-e68694f17d7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjg3MTUsIm5iZiI6MTcxNjAyODQxNSwicGF0aCI6Ii83NzAzMjczNi8zMjk3NTczMjktNjM4MDY1ZDQtMTQzYy00ODNhLTg1NzYtZTY4Njk0ZjE3ZDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZjUxOWE2ZDY0YmQ4OGI0NGFjOTQ0NWQ2ZjAwOGUwY2RlZmMyNjllOTNlYTExYzkzMWUyM2QyNGJkNzg3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fk7k307J9G6wSstjfwKunKytqTRtDyC7io-mi7QEYTo)

你这个应该是使用tts推理的时候报错的，下载对应的权重文件fastspeech2_mix-mix
