### ISSUE TITLE
使用vits_csmsc_ckpt_1.4.0预训练模型时报错ValueError: (InvalidArgument) expand(): argument (position 2) must be list of int, but got Tensor at pos 0 

### ISSUE THREAD

**Issue by KevinFOS** [PaddlePaddle/PaddleSpeech#3769]
**环境:**
 - OS: Windows 11
 - GCC 10.3.0
 - Python Version 3.8.19
 - PaddlePaddle Version 2.6.1
 - GPU/DRIVER Information NVIDIA GeForce RTX3060 Laptop
 - CUDA/CUDNN Version 12.0

遵循 /examples/csmsc/vits/README.md 的介绍，使用以下命令：

`python ~/paddlespeech/t2s/exps/vits/synthesize_e2e.py --config=vits_csmsc_ckpt_1.4.0/default.yaml --ckpt=vits_csmsc_ckpt_1.4.0/snapshot_iter_150000.pdz --phones_dict=vits_csmsc_ckpt_1.4.0/phone_id_map.txt --output_dir=exp/default/test_e2e --text=~/paddlespeech/t2s/assets/sentences.txt --add-blank=true`

出现以下报错：

```
Traceback (most recent call last):
  File "C:/Users/45178/OneDrive/TTS_Project/PaddleSpeech/paddlespeech/t2s/exps/vits/synthesize_e2e.py", line 198, in <module>
    main()
  File "C:/Users/45178/OneDrive/TTS_Project/PaddleSpeech/paddlespeech/t2s/exps/vits/synthesize_e2e.py", line 194, in main
    evaluate(args)
  File "C:/Users/45178/OneDrive/TTS_Project/PaddleSpeech/paddlespeech/t2s/exps/vits/synthesize_e2e.py", line 111, in evaluate
    wav = vits_inference(part_phone_ids)
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddlespeech\t2s\models\vits\vits.py", line 542, in forward
    out = self.acoustic_model.inference(
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddlespeech\t2s\models\vits\vits.py", line 444, in inference
    wav, att_w, dur = self.generator.inference(
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddlespeech\t2s\models\vits\generator.py", line 482, in inference
    x, m_p, logs_p, x_mask = self.text_encoder(text, text_lengths)
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddlespeech\t2s\models\vits\text_encoder.py", line 157, in forward
    x_mask = make_non_pad_mask(x_lengths).unsqueeze(1)
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddlespeech\t2s\modules\nets_utils.py", line 296, in make_non_pad_mask
    return paddle.logical_not(make_pad_mask(lengths, xs, length_dim))
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddlespeech\t2s\modules\nets_utils.py", line 192, in make_pad_mask
    seq_range_expand = seq_range.unsqueeze(0).expand([bs, maxlen])
  File "C:\Users\45178\OneDrive\TTS_Project\PaddleSpeech\tools\venv\lib\site-packages\paddle\tensor\manipulation.py", line 3741, in expand
    return _C_ops.expand(x, shape)
ValueError: (InvalidArgument) expand(): argument (position 2) must be list of int, but got Tensor at pos 0 (at ..\paddle\fluid\pybind\op_function_common.cc:470)
```

**Comment by KevinFOS** [comment]
原因：Paddlepaddle版本过高，换用较低的2.5.1版本即可解决。
