### ISSUE TITLE
Unable to normalize segment

### ISSUE THREAD

**Issue by shoegazerstella** [PaddlePaddle/PaddleSpeech#399]
This error appears quite often during my training.
Any idea on how to solve it? maybe doing some preprocessing on the audio?

```
[WARNING 2019-12-18 17:38:59,189 reader.py:487] Your reader has raised an exception!
Exception in thread Thread-120:
Traceback (most recent call last):
  File "/home/stella/.conda/envs/paddle/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/stella/.conda/envs/paddle/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/stella/.conda/envs/paddle/lib/python2.7/site-packages/paddle/fluid/reader.py", line 488, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/stella/.conda/envs/paddle/lib/python2.7/site-packages/paddle/fluid/reader.py", line 468, in __thread_main__
    for tensors in self._tensor_reader():
  File "/mnt/Data/stella/paddle/DeepSpeech/data_utils/data.py", line 200, in batch_reader
    for instance in instance_reader():
  File "/mnt/Data/stella/paddle/DeepSpeech/data_utils/data.py", line 279, in reader
    instance["text"]),
  File "/mnt/Data/stella/paddle/DeepSpeech/data_utils/data.py", line 121, in process_utterance
    speech_segment, self._keep_transcription_text)
  File "/mnt/Data/stella/paddle/DeepSpeech/data_utils/featurizer/speech_featurizer.py", line 76, in featurize
    audio_feature = self._audio_featurizer.featurize(speech_segment)
  File "/mnt/Data/stella/paddle/DeepSpeech/data_utils/featurizer/audio_featurizer.py", line 86, in featurize
    audio_segment.normalize(target_db=self._target_dB)
  File "/mnt/Data/stella/paddle/DeepSpeech/data_utils/audio.py", line 345, in normalize
    (target_db, max_gain_db))
ValueError: Unable to normalize segment to -20.000000 dB because the the probable gain have exceeds max_gain_db (300.000000 dB)
```

Thanks!

**Comment by lfchener** [comment]
Did you finish the data preparation before training? And which dataset did you using？

**Comment by lfchener** [comment]
Did you finish the data preparation before training? And which dataset did you use？

**Comment by shoegazerstella** [comment]
Yes I computed the data preparation like this:

```
python tools/compute_mean_std.py \
--num_samples 2000 \
--specgram_type linear \
--manifest_path train_pp_eng.txt \
--output_path mean_std.npz
```

The error above does not stop the training but I noticed it skips some batches quite often.
I am using my own dataset.

**Comment by shoegazerstella** [comment]
I have some logs to show, basically when the error occurs the train of that epoch is stopped

```
----------Begin test...
--------Time: 109.195673 sec, epoch: 12, train loss: 29.476292, test loss: 53.123539
epoch: 12, batch: 0, train loss: 31.763771

epoch: 12, batch: 100, train loss: 71.694092

epoch: 12, batch: 200, train loss: 55.236881


----------Begin test...
--------Time: 142.631619 sec, epoch: 13, train loss: 52.898251, test loss: 53.524574
epoch: 13, batch: 0, train loss: 34.942764


----------Begin test...
--------Time: 54.822144 sec, epoch: 14, train loss: 34.942764, test loss: 52.582970
epoch: 14, batch: 0, train loss: 66.187073

epoch: 14, batch: 100, train loss: 49.939499

epoch: 14, batch: 200, train loss: 44.748089

epoch: 14, batch: 300, train loss: 56.365620

epoch: 14, batch: 400, train loss: 62.855026

epoch: 14, batch: 500, train loss: 54.263683

epoch: 14, batch: 600, train loss: 31.412270

epoch: 14, batch: 700, train loss: 54.352444


----------Begin test...
--------Time: 433.748984 sec, epoch: 15, train loss: 52.515465, test loss: 51.527508
epoch: 15, batch: 0, train loss: 38.828835


----------Begin test...
--------Time: 6.328256 sec, epoch: 16, train loss: 38.828835, test loss: 51.499104
epoch: 16, batch: 0, train loss: 79.683914

epoch: 16, batch: 100, train loss: 71.081345
```

Is there a way I can solve this? 
Thanks!

**Comment by lfchener** [comment]
It seems like the variance of your audio data is too large.
You can try to increase the default value of **max_gain_db** in  **normalize**：
![image](https://user-images.githubusercontent.com/6771821/71231545-639baf00-2329-11ea-9289-2471349f86b7.png)

which is defined in **data_utils/audio.py**
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/data_utils/audio.py#L323

**Comment by shoegazerstella** [comment]
I just doubled to 600 and had still that error but less often, I guess I need to find the best value? Is more than 600 too much?

**Comment by lfchener** [comment]
Maybe you should analyze your audio data to get the best value.
