### ISSUE TITLE
按照readme 一步一步执行的， infer 时报错。

### ISSUE THREAD

**Issue by xinzheshen** [PaddlePaddle/PaddleSpeech#404]
@lfchener 我看报错这行代码是您最近添加的，我是pip安装的环境， 并按照readme 一步步执行的，但执行到infer时报错，是readme过时了吗？谢谢。
Traceback (most recent call last):
  File "/home/shenxz/.IdeaIC2019.2/config/plugins/python-ce/helpers/pydev/pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/shenxz/code/DeepSpeech/infer.py", line 152, in <module>
    main()
  File "/home/shenxz/code/DeepSpeech/infer.py", line 148, in main
    infer()
  File "/home/shenxz/code/DeepSpeech/infer.py", line 94, in infer
    infer_data = next(batch_reader())
  File "/home/shenxz/code/DeepSpeech/data_utils/data.py", line 203, in batch_reader
    yield self._padding_batch(batch, padding_to, flatten)
  File "/home/shenxz/code/DeepSpeech/data_utils/data.py", line 333, in _padding_batch
    texts = np.expand_dims(np.array(texts).astype('int32'), axis=-1)
ValueError: invalid literal for int() with base 10: 'he hoped there would be stew for dinner turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick peppered flour fattened sauce'

**Comment by jchua127** [comment]
用上个版本的data.py

**Comment by WilliamEt** [comment]
确实这样，用上个版本的替换掉DeepSpeech/data_utils/data.py就好了
![image](https://user-images.githubusercontent.com/17410301/71542145-c3373180-299d-11ea-8065-9ec2ae4eeb62.png)

**Comment by xinzheshen** [comment]
我试了，确实是这样，多谢 @jchua127  @WilliamEt

**Comment by xinzheshen** [comment]
我pull了最新的代码，仍然报上面的错。
