### ISSUE TITLE
aishell  run_test.sh时UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-11: invalid decimal Unicode string

### ISSUE THREAD

**Issue by tianchaolangzi** [PaddlePaddle/PaddleSpeech#414]
-----------  Configuration Arguments -----------
alpha: 2.6
batch_size: 128
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: models/aishell/mean_std.npz
model_path: models/aishell
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
test_manifest: data/aishell/manifest.test
use_gpu: 1
use_gru: 1
vocab_path: models/aishell/vocab.txt
------------------------------------------------
2020-01-20 01:43:38,386-INFO: begin to initialize the external scorer for decoding
2020-01-20 01:43:38,501-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-01-20 01:43:38,501-INFO: end initializing scorer
2020-01-20 01:43:38,502-INFO: start evaluation ...
Traceback (most recent call last):
  File "test.py", line 149, in <module>
    main()
  File "test.py", line 145, in main
    evaluate()
  File "test.py", line 110, in evaluate
    for infer_data in batch_reader():
  File "/media/zzzzzzk/HDD4T/zk/DeepSpeech/data_utils/data.py", line 206, in batch_reader
    yield self._padding_batch(batch, padding_to, flatten)
  File "/media/zzzzzzk/HDD4T/zk/DeepSpeech/data_utils/data.py", line 336, in _padding_batch
    texts = np.expand_dims(np.array(texts).astype('int32'), axis=-1)
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-11: invalid decimal Unicode string
Failed in evaluation!

**Comment by lfchener** [comment]
已修复，感谢关注!

**Comment by tianchaolangzi** [comment]
多谢
