### ISSUE TITLE
运行Test.py时出现错误OSError: cannot load library 'libsndfile.so.1': libsndfile.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DoraemonMiku** [PaddlePaddle/PaddleSpeech#440]
系统是CentOS 7.3，按照readMe里面来一步步操作的，但是测试时候出现了这个异常(运行examples/tiny/里面的也会,下面运行的是test.py):
**configure: WARNING: *** One or more of the external libraries (ie libflac, libogg and
configure: WARNING: *** libvorbis) is either missing (possibly only the development
configure: WARNING: *** headers) or is of an unsupported version.
configure: WARNING: ***
configure: WARNING: *** Unfortunately, for ease of maintenance, the external libs
configure: WARNING: *** are an all or nothing affair.
configure: WARNING: Touching files in directory tests/.
Install all dependencies successfully.
[root@iz4uregsg8u6ngz DeepSpeech]# test.py
-bash: test.py: command not found
[root@iz4uregsg8u6ngz DeepSpeech]# python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from data_utils.data import DataGenerator
  File "/root/DeepSpeech/data_utils/data.py", line 15, in <module>
    from data_utils.augmentor.augmentation import AugmentationPipeline
  File "/root/DeepSpeech/data_utils/augmentor/augmentation.py", line 11, in <module>
    from data_utils.augmentor.noise_perturb import NoisePerturbAugmentor
  File "/root/DeepSpeech/data_utils/augmentor/noise_perturb.py", line 8, in <module>
    from data_utils.audio import AudioSegment
  File "/root/DeepSpeech/data_utils/audio.py", line 10, in <module>
    import soundfile
  File "/usr/lib/python2.7/site-packages/soundfile.py", line 267, in <module>
    _snd = _ffi.dlopen('sndfile')
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'libsndfile.so.1': libsndfile.so.1: cannot open shared object file: No such file or directory**
安装时候他给我一个警告是可能是因为这个原因？求解，小白一个。

**Comment by qili93** [comment]
libsndfile.so 安装目录是在“/usr/local/lib”下面，检查一下你的“LD_LIBRARY_PATH”是否包含这个目录，如果没有就`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`，再尝试运行一下。

**Comment by yeyupiaoling** [comment]
安装
```
apt install libsndfile1
```

**Comment by zhangxiudan** [comment]
File "/usr/local/lib/python2.7/site-packages/soundfile.py", line 267, in <module>
    _snd = _ffi.dlopen('sndfile')
  File "/usr/local/lib/python2.7/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python2.7/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python2.7/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'sndfile'
我也遇到同样的问题， / usr / local / lib 下没有libsndfile.so  

apt install libsndfile1  pip install libsndfile1 都没有安装成功，请问有没有其他办法？

**Comment by yeyupiaoling** [comment]
@zhangxiudan 你看看这：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech ，可能会解决这个问题。

**Comment by zhangxiudan** [comment]
apt-get update
apt install libsndfile1

**Comment by zhangxiudan** [comment]
@yeyupiaoling 谢谢

**Comment by EzrealoveQXY** [comment]
![633a5c732d603ab820cb35260340d54](https://user-images.githubusercontent.com/49974992/200282975-9d065451-e730-46df-ad48-64f1b9159a21.jpg)
docker-compose 启动，也报这个错
