### ISSUE TITLE
请问如何直接预测自己的录音，将录音转成文本

### ISSUE THREAD

**Issue by duan348733684** [PaddlePaddle/PaddleSpeech#452]
请问如何直接预测自己的录音，将录音转成文本？谢谢解答，有提供相应的脚本吗？

**Comment by xixiaoyao** [comment]
辛苦 @lfchener 看一下

**Comment by lfchener** [comment]
可以参考 README：
https://github.com/PaddlePaddle/DeepSpeech#trying-live-demo-with-your-own-voice

**Comment by duan348733684** [comment]
> 可以参考 README：
> https://github.com/PaddlePaddle/DeepSpeech#trying-live-demo-with-your-own-voice

您好。我在运行 python infer.py 时出现下面错误，帮我看下好吗，谢谢
Traceback (most recent call last):
  File "infer.py", line 152, in <module>
    main()
  File "infer.py", line 148, in main
    infer()
  File "infer.py", line 124, in infer
    feeding_dict=data_generator.feeding)
  File "/home/duanchao/DeepSpeech/model_utils/model.py", line 402, in infer_batch_probs
    feeder, log_probs, _ = self.create_network(is_infer=True)
  File "/home/duanchao/DeepSpeech/model_utils/model.py", line 145, in create_network
    share_rnn_weights=self._share_rnn_weights)
  File "/home/duanchao/DeepSpeech/model_utils/network.py", line 427, in deep_speech_v2_network
    share_rnn_weights=share_rnn_weights)
  File "/home/duanchao/DeepSpeech/model_utils/network.py", line 359, in rnn_group
    share_weights=share_rnn_weights)
  File "/home/duanchao/DeepSpeech/model_utils/network.py", line 196, in bidirectional_simple_rnn_bn_layer
    forward_rnn = fluid.layers.sequence_unpad(x=forward_rnn, length=length)
  File "/home/duanchao/.local/lib/python2.7/site-packages/paddle/fluid/layers/sequence_lod.py", line 1039, in sequence_unpad
    'fluid.layers.sequence_unpad')
  File "/home/duanchao/.local/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
    check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
  File "/home/duanchao/.local/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
    extra_message))
TypeError: The data type of 'length' in fluid.layers.sequence_unpad must be ['int64'], but received float32.

**Comment by duan348733684** [comment]
@lfchener

**Comment by zh794390558** [comment]
TypeError: The data type of 'length' in fluid.layers.sequence_unpad must be ['int64'], but received float32.
