### ISSUE TITLE
运行 python infer.py 时报C++的错?

### ISSUE THREAD

**Issue by duan348733684** [PaddlePaddle/PaddleSpeech#453]
Traceback (most recent call last):
  File "infer.py", line 154, in <module>
    main()
  File "infer.py", line 150, in main
    infer()
  File "infer.py", line 122, in infer
    vocab_list)
  File "/apps/users/dbc/workspace/DeepSpeech/model_utils/model.py", line 478, in init_ext_scorer
    language_model_path, vocab_list)
  File "/apps/users/dbc/workspace/DeepSpeech/decoders/swig_wrapper.py", line 23, in __init__
    swig_decoders.Scorer.__init__(self, alpha, beta, model_path, vocabulary)
  File "/apps/users/dbc/py3/lib/python3.7/site-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg/swig_decoders.py", line 1269, in __init__
    this = _swig_decoders.new_Scorer(alpha, beta, lm_path, vocabulary)
TypeError: in method 'new_Scorer', argument 4 of type 'std::vector< std::string,std::allocator< std::string > > const &'

请问下在 运行 python infer.py 时报这个错是什么意思啊？完全看不懂

**Comment by artinegi1607** [comment]
Is this issue resolved?

**Comment by yeyupiaoling** [comment]
@duan348733684 你这个是在Python3编译得到的环境吧？我的也出现这个问题，请问你解决了吗？
