### ISSUE TITLE
TypeError: The data type of 'length' in fluid.layers.sequence_unpad must be ['int64'], but received float32. 

### ISSUE THREAD

**Issue by duan348733684** [PaddlePaddle/PaddleSpeech#454]
运行 python infer.py 时，出现下面问题，请大佬们帮忙看下

Traceback (most recent call last):
  File "infer.py", line 152, in <module>
    main()
  File "infer.py", line 148, in main
    infer()
  File "infer.py", line 124, in infer
    feeding_dict=data_generator.feeding)
  File "/home/duanchao/DeepSpeech/model_utils/model.py", line 402, in infer_batch_probs
    feeder, log_probs, _ = self.create_network(is_infer=True)
  File "/home/duanchao/DeepSpeech/model_utils/model.py", line 145, in create_network
    share_rnn_weights=self._share_rnn_weights)
  File "/home/duanchao/DeepSpeech/model_utils/network.py", line 427, in deep_speech_v2_network
    share_rnn_weights=share_rnn_weights)
  File "/home/duanchao/DeepSpeech/model_utils/network.py", line 359, in rnn_group
    share_weights=share_rnn_weights)
  File "/home/duanchao/DeepSpeech/model_utils/network.py", line 196, in bidirectional_simple_rnn_bn_layer
    forward_rnn = fluid.layers.sequence_unpad(x=forward_rnn, length=length)
  File "/home/duanchao/.local/lib/python2.7/site-packages/paddle/fluid/layers/sequence_lod.py", line 1039, in sequence_unpad
    'fluid.layers.sequence_unpad')
  File "/home/duanchao/.local/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
    check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
  File "/home/duanchao/.local/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
    extra_message))
TypeError: The data type of 'length' in fluid.layers.sequence_unpad must be ['int64'], but received float32.

**Comment by duan348733684** [comment]
@xixiaoyao  @lfchener   两位大佬有时间能看下上面这个问题吗？谢谢。。我的python 是2.7.15，paddlepaddle 是1.8.1,   语言模型和语音模型 是在 README  里发布模型部分中下载的。

**Comment by lfchener** [comment]
> @xixiaoyao @lfchener 两位大佬有时间能看下上面这个问题吗？谢谢。。我的python 是2.7.15，paddlepaddle 是1.8.1, 语言模型和语音模型 是在 README 里发布模型部分中下载的。

这个是 paddle 1.8.1 的 bug，我们会尽快修复。
paddle 1.8.0 是没有问题的，你可以先使用 1.8.0 运行。

**Comment by shoegazerstella** [comment]
thanks @lfchener it works now with paddlepaddle==1.8.0.
Could you tell us when the new version will be bugs free? Thanks!
