### ISSUE TITLE
 The pretrained params do not exist. Failed in inference!

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSpeech#461]
Hi,

``
[INFO 2020-06-17 08:27:41,059 model.py:474] begin to initialize the external scorer for decoding
[INFO 2020-06-17 08:27:51,392 model.py:484] language model: is_character_based = 0, max_order = 5, dict_size = 400000
[INFO 2020-06-17 08:27:51,616 model.py:485] end initializing scorer
[INFO 2020-06-17 08:27:51,617 infer.py:121] start inference ...
W0617 08:27:52.673171   330 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 60, Driver API Version: 10.1, Runtime API Version: 9.0
W0617 08:27:52.678908   330 device_context.cc:243] device: 0, cuDNN Version: 7.5.
./checkpoints/tiny/step_final
Traceback (most recent call last):
  File "infer.py", line 152, in <module>
    main()
  File "infer.py", line 148, in main
    infer()
  File "infer.py", line 124, in infer
    feeding_dict=data_generator.feeding)
  File "/DeepSpeech/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/DeepSpeech/model_utils/model.py", line 155, in init_from_pretrained_model
    raise Warning("The pretrained params do not exist.")
Warning: The pretrained params do not exist.
Failed in inference!
``

What am I missing here?

**Comment by ParmpalSinghGill** [comment]
You need to download model from https://deepspeech.bj.bcebos.com/eng_models/librispeech_model_fluid.tar.gz and extract it and give the path to argument as a model_path

**Comment by smpkali** [comment]
[INFO 2022-03-23 08:38:31,479 eval.py:74] 开始评估 ...
Traceback (most recent call last):
  File "eval.py", line 117, in <module>
    main()
  File "eval.py", line 113, in main
    evaluate()
  File "eval.py", line 79, in evaluate
    probs_split = ds2_model.infer_batch_data(infer_data=infer_data)
  File "/home/rasa/DeepSpeech/model_utils/model.py", line 368, in infer_batch_data
    self.load_param(self.infer_program, self._resume_model)
  File "/home/rasa/DeepSpeech/model_utils/model.py", line 144, in load_param
    raise Warning("The pretrained params [%s] do not exist." % model_path)
Warning: The pretrained params [./models/param/50.pdparams] do not exist.
您好请问我这报错该怎么处理
