### ISSUE TITLE
Error to run inference and test scripts in chinese

### ISSUE THREAD

**Issue by andy311p** [PaddlePaddle/PaddleSpeech#487]
when i run scripts infer.sh or test.sh i get the following error:
Traceback (most recent call last):
  File "infer.py", line 152, in <module>
    main()
  File "infer.py", line 148, in main
    infer()
  File "infer.py", line 124, in infer
    feeding_dict=data_generator.feeding)
  File "/DeepSpeech/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 877, in load_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 820, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((4299L,)), while the loaded parameter (namely [ layer_5_fc_bias ]) has a shape of  ((4334,)).
Failed in inference!

**Comment by C4712** [comment]
i meet the same peoblem, How did you solve this problem

**Comment by Zolewit** [comment]
"vocab_path" should use “models/aishell/vocab.txt”, not "data/..."
because vocab.txt in "models" has 4299 lines but in "data" has 4333 lines.
