### ISSUE TITLE
load 官方的aishell_model_fluid时报错

### ISSUE THREAD

**Issue by Mryangkaitong** [PaddlePaddle/PaddleSpeech#491]
`python ./deploy/demo_server.py --model_path='/root/DeepSpeech/deploy/aishell_model_fluid'  --host_ip='localhost'  --host_port=8086 --use_gpu=False --mean_std_path='/root/DeepSpeech/deploy/aishell_model_fluid/mean_std.npz'  --vocab_path='/root/DeepSpeech/deploy/aishell_model_fluid/vocab.txt' --lang_model_path='/root/DeepSpeech/deploy/zh_giga.no_cna_cmn.prune01244.klm' --rnn_layer_size=1024 --share_rnn_weights=False  --specgram_type='linear' --warmup_manifest='/root/DeepSpeech/data/tiny/manifest.test-clean' --num_conv_layers=2 --num_rnn_layers=3`
时报错如下：
2020-09-06 21:39:12,323-INFO: begin to initialize the external scorer for decoding
2020-09-06 21:39:49,813-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-09-06 21:39:49,813-INFO: end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'./dataset/librispeech/test-clean/LibriSpeech/test-clean/7176/92135/7176-92135-0025.flac')
Traceback (most recent call last):
  File "./deploy/demo_server.py", line 238, in <module>
    main()
  File "./deploy/demo_server.py", line 234, in main
    start_server()
  File "./deploy/demo_server.py", line 219, in start_server
    num_test_cases=3)
  File "./deploy/demo_server.py", line 136, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "./deploy/demo_server.py", line 195, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/root/DeepSpeech/deploy/../model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/root/DeepSpeech/deploy/../model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/root/anaconda3/envs/python27/lib/python2.7/site-packages/paddle/fluid/io.py", line 876, in load_params
    filename=filename)
  File "/root/anaconda3/envs/python27/lib/python2.7/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/python27/lib/python2.7/site-packages/paddle/fluid/io.py", line 819, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((1024L, 1024L)), while the loaded parameter (namely [ layer_3_forward_rnn_weight ]) has a shape of  ((1024, 3072)).
请问这个是我哪里设置错误了吗？谢谢

**Comment by lrsSpace** [comment]
我把 --use_gru=True 设置为True就行了
