### ISSUE TITLE
PaddlePaddle 1.8.0 installation fails

### ISSUE THREAD

**Issue by AshutoshDongare** [PaddlePaddle/PaddleSpeech#493]
Downloading https://mirror.baidu.com/pypi/packages/a1/d6/8422797e35f8814b1d9842530566a949d9b5850a466321a6c1d5a99055ee/opencv-python-4.3.0.38.tar.gz (88.0 MB)
     |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 88.0 MB 22 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Admin\anaconda3\envs\speech\python.exe' 'C:\Users\Admin\anaconda3\envs\speech\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\admin\appdata\local\temp\tmpmsjh7o'
       cwd: c:\users\admin\appdata\local\temp\pip-install-ep_8ia\opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "C:\Users\Admin\anaconda3\envs\speech\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\Admin\anaconda3\envs\speech\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Admin\anaconda3\envs\speech\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "c:\users\admin\appdata\local\temp\pip-build-env-6a9hmw\overlay\Lib\site-packages\setuptools\build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "c:\users\admin\appdata\local\temp\pip-build-env-6a9hmw\overlay\Lib\site-packages\setuptools\build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "c:\users\admin\appdata\local\temp\pip-build-env-6a9hmw\overlay\Lib\site-packages\setuptools\build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "c:\users\admin\appdata\local\temp\pip-build-env-6a9hmw\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "C:\Users\Admin\anaconda3\envs\speech\lib\re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Admin\anaconda3\envs\speech\python.exe' 'C:\Users\Admin\anaconda3\envs\speech\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\admin\appdata\local\temp\tmpmsjh7o' Check the logs for full command output.

**Comment by LeonKennedy** [comment]
i have the same error

**Comment by LeonKennedy** [comment]
open-python 4.3 is not compatible for python 2.7, so you need run this before:
_pip install opencv-python==4.2.0.32_
