### ISSUE TITLE
 pip install paddlepaddle-gpu==1.8.0.post107 -i https://mirrors.aliyun.com/pypi/simple  下载报错

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleSpeech#505]
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting paddlepaddle-gpu==1.8.0.post107
  Using cached https://mirrors.aliyun.com/pypi/packages/77/54/e55c1484f0cc7af8a69a38e9e4722b4754be2130810984450761895a02c2/paddlepaddle_gpu-1.8.0.post107-cp27-cp27mu-manylinux1_x86_64.whl (405.7 MB)
Collecting graphviz
  Using cached https://mirrors.aliyun.com/pypi/packages/86/86/89ba50ba65928001d3161f23bfa03945ed18ea13a1d1d44a772ff1fa4e7a/graphviz-0.16-py2.py3-none-any.whl (19 kB)
Collecting opencv-python
  Using cached https://mirrors.aliyun.com/pypi/packages/a1/d6/8422797e35f8814b1d9842530566a949d9b5850a466321a6c1d5a99055ee/opencv-python-4.3.0.38.tar.gz (88.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/Anaconda3/envs/py2/bin/python /opt/Anaconda3/envs/py2/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp07EPYa
       cwd: /tmp/pip-install-U8NATZ/opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/opt/Anaconda3/envs/py2/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/Anaconda3/envs/py2/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/Anaconda3/envs/py2/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-Md_yKd/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-Md_yKd/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-Md_yKd/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-Md_yKd/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "/opt/Anaconda3/envs/py2/lib/python2.7/re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/Anaconda3/envs/py2/bin/python /opt/Anaconda3/envs/py2/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp07EPYa Check the logs for full command output.

**Comment by weiaoliu** [comment]
请问这是什么原因
