### ISSUE TITLE
AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleSpeech#506]
Traceback (most recent call last):
  File "infer.py", line 182, in <module>
    show(audiopath)
  File "infer.py", line 176, in show
    result = infer()
  File "infer.py", line 151, in infer
    feeding_dict=data_generator.feeding)
  File "/home/port/model_utils/model.py", line 402, in infer_batch_probs
    feeder, log_probs, _ = self.create_network(is_infer=True)
  File "/home/port/model_utils/model.py", line 120, in create_network
    lod_level=0)
  File "<decorator-gen-25>", line 2, in data
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 231, in __impl__
    ), "In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and '%s()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode." % func.__name__
AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.

**Comment by DemoMoon** [comment]
model.py 新增

import paddle
paddle.enable_static()

就可以执行了。
