### ISSUE TITLE
加载预训练模型报错

### ISSUE THREAD

**Issue by xiaoyu4122** [PaddlePaddle/PaddleSpeech#510]

**Comment by xiaoyu4122** [comment]
augment_conf_path: conf/augmentation.config
batch_size: 64
dev_manifest: /data/aistation/XiangyuZhu/dataset/magic_data_sample/manifest.dev
init_from_pretrained_model: /data/aistation/XiangyuZhu/DeepSpeech/checkpoints/baidu
is_local: 1
learning_rate: 0.0005
max_duration: 27.0
mean_std_path: /data/aistation/XiangyuZhu/DeepSpeech/data/baidu/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_epoch: 100
num_iter_print: 100
num_rnn_layers: 3
num_samples: 120000
output_model_dir: ./checkpoints/magic_sample_ckpt
rnn_layer_size: 2048
save_epoch: 1
share_rnn_weights: 0
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 1
train_manifest: /data/aistation/XiangyuZhu/dataset/magic_data_sample/manifest.train
use_gpu: 1
use_gru: 1
use_sortagrad: 1
vocab_path: /data/aistation/XiangyuZhu/DeepSpeech/data/baidu/vocab.txt
------------------------------------------------
W0112 17:46:29.731545 308801 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
W0112 17:46:29.737216 308801 device_context.cc:260] device: 0, cuDNN Version: 7.6.
finish initing model from pretrained params from /data/aistation/XiangyuZhu/DeepSpeech/checkpoints/baidu
W0112 17:46:52.255365 308801 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 38. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 38.
[WARNING 2021-01-12 17:46:52,517 reader.py:1144] Your reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/data.py", line 200, in batch_reader
    for instance in instance_reader():
  File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/data.py", line 279, in reader
    instance["text"]),
  File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/data.py", line 121, in process_utterance
    speech_segment, self._keep_transcription_text)
  File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/featurizer/speech_featurizer.py", line 79, in featurize
    text_ids = self._text_featurizer.featurize(speech_segment.transcript)
  File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/featurizer/text_featurizer.py", line 36, in featurize
    return [self._vocab_dict[token] for token in tokens]
KeyError: u'\u4e00'

/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main()
  File "train.py", line 138, in main
    train()
  File "train.py", line 133, in train
    test_off=args.test_off)
  File "/data/aistation/XiangyuZhu/DeepSpeech/model_utils/model.py", line 336, in train
    return_numpy=False)
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/data/aistation/XiangyuZhu/paddle-deepspeech/lib/python2.7/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/data/aistation/XiangyuZhu/DeepSpeech/model_utils/model.py", line 112, in create_network
    use_double_buffer=True)
  File "/data/aistation/XiangyuZhu/DeepSpeech/model_utils/model.py", line 281, in train
    train_reader, log_probs, ctc_loss = self.create_network()
  File "train.py", line 133, in train
    test_off=args.test_off)
  File "train.py", line 138, in main
    train()
  File "train.py", line 142, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
Failed in training!
**报错内容**

**Comment by zh794390558** [comment]
please check this :
```
File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/data.py", line 121, in process_utterance
speech_segment, self._keep_transcription_text)
File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/featurizer/speech_featurizer.py", line 79, in featurize
text_ids = self._text_featurizer.featurize(speech_segment.transcript)
File "/data/aistation/XiangyuZhu/DeepSpeech/data_utils/featurizer/text_featurizer.py", line 36, in featurize
return [self._vocab_dict[token] for token in tokens]
KeyError: u'\u4e00'
```
