### ISSUE TITLE
使用官方BaiduCN1.2k Model和Mandarin LM Small搭建语音识别报错

### ISSUE THREAD

**Issue by ccbptm** [PaddlePaddle/PaddleSpeech#513]
修改test.py并运行提示：
```
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;-----------  Configuration Arguments -----------
alpha: 2.5
batch_size: 32
beam_size: 500
beta: 0.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: CER
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: models/baidu_ch1.2k/mean_std.npz
model_path: /home/mocai/Graduation/DeepSpeech/models/aishell
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: False
specgram_type: linear
test_manifest: /home/mocai/Graduation/DeepSpeech/data/aishell/manifest.test
use_gpu: True
use_gru: True
vocab_path: models/baidu_ch1.2k/vocab.txt
------------------------------------------------
[INFO 2021-01-13 19:20:17,509 model.py:474] begin to initialize the external scorer for decoding
[INFO 2021-01-13 19:20:17,587 model.py:484] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2021-01-13 19:20:17,587 model.py:485] end initializing scorer
[INFO 2021-01-13 19:20:17,587 test.py:115] start evaluation ...
W0113 19:20:17.922132 20528 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0113 19:20:17.924199 20528 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "test.py", line 155, in <module>
    main()
  File "test.py", line 151, in main
    evaluate()
  File "test.py", line 119, in evaluate
    feeding_dict=data_generator.feeding)
  File "/home/mocai/Graduation/DeepSpeech/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/home/mocai/Graduation/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/io.py", line 877, in load_params
    filename=filename)
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/io.py", line 820, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((6144L,)), while the loaded parameter (namely [ layer_2_forward_batch_norm_moving_mean ]) has a shape of  ((3072,)).

```

然后我的TensorRT也安装好了并且导入到LD_LIBARARY_PATH内了

**Comment by ccbptm** [comment]
```
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;-----------  Configuration Arguments -----------
alpha: 2.5
batch_size: 32
beam_size: 500
beta: 0.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: CER
lang_model_path: /home/mocai/Graduation/DeepSpeech/models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: /home/mocai/Graduation/DeepSpeech/models/baidu_ch1.2k/mean_std.npz
model_path: /home/mocai/Graduation/DeepSpeech/models/baidu_ch1.2k
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: False
specgram_type: linear
test_manifest: /home/mocai/Graduation/DeepSpeech/data/aishell/manifest.test
use_gpu: True
use_gru: True
vocab_path: /home/mocai/Graduation/DeepSpeech/models/baidu_ch1.2k/vocab.txt
------------------------------------------------
[INFO 2021-01-13 19:33:06,033 model.py:474] begin to initialize the external scorer for decoding
[INFO 2021-01-13 19:33:06,112 model.py:484] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2021-01-13 19:33:06,112 model.py:485] end initializing scorer
[INFO 2021-01-13 19:33:06,112 test.py:115] start evaluation ...
W0113 19:33:06.465489 21373 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0113 19:33:06.467573 21373 device_context.cc:260] device: 0, cuDNN Version: 7.6.
finish initing model from pretrained params from /home/mocai/Graduation/DeepSpeech/models/baidu_ch1.2k
Error rate [CER] (32/?) = 1.000000
finish initing model from pretrained params from /home/mocai/Graduation/DeepSpeech/models/baidu_ch1.2k
^CTraceback (most recent call last):
  File "test.py", line 155, in <module>
    main()
  File "test.py", line 151, in main
    evaluate()
  File "test.py", line 119, in evaluate
    feeding_dict=data_generator.feeding)
  File "/home/mocai/Graduation/DeepSpeech/model_utils/model.py", line 423, in infer_batch_probs
    return_numpy=False)
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1224, in _run_program
    fetch_var_name=fetch_var_name)
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 609, in _add_feed_fetch_ops
    attrs={'col': i})
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2679, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1829, in __init__
    if in_dygraph_mode():
  File "/home/mocai/.local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 200, in in_dygraph_mode
    return _dygraph_tracer_ is not None
KeyboardInterrupt

```

**Comment by zh794390558** [comment]
模型和配置不匹配。
