### ISSUE TITLE
Run infer.py时报错

### ISSUE THREAD

**Issue by TyroneHe-0926** [PaddlePaddle/PaddleSpeech#540]
以前example什么的跑的都是好的，然后想用自己的数据试试就下了几个flac文件，然后把那些文件的manifest做出来之后用infer.py跑就报这个错： 
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: wer
infer_manifest: /home/ubuntu/DeepSpeech/data/aishell/testmani2
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: /home/ubuntu/DeepSpeech/models/aishell/mean_std.npz
model_path: checkpoints/aishell/step_final
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 1024
share_rnn_weights: False
specgram_type: linear
use_gpu: True
use_gru: True
vocab_path: /home/ubuntu/DeepSpeech/models/aishell/vocab.txt
------------------------------------------------
Traceback (most recent call last):
  File "infer.py", line 146, in <module>
    main()
  File "infer.py", line 142, in main
    infer()
  File "infer.py", line 88, in infer
    infer_data = next(batch_reader())
  File "/home/ubuntu/DeepSpeech/data_utils/data.py", line 197, in batch_reader
    for instance in instance_reader():
  File "/home/ubuntu/DeepSpeech/data_utils/data.py", line 276, in reader
    instance["text"])
  File "/home/ubuntu/DeepSpeech/data_utils/data.py", line 118, in process_utterance
    speech_segment, self._keep_transcription_text)
  File "/home/ubuntu/DeepSpeech/data_utils/featurizer/speech_featurizer.py", line 73, in featurize
    audio_feature = self._audio_featurizer.featurize(speech_segment)
  File "/home/ubuntu/DeepSpeech/data_utils/featurizer/audio_featurizer.py", line 77, in featurize
    audio_segment.resample(self._target_sample_rate)
  File "/home/ubuntu/DeepSpeech/data_utils/audio.py", line 397, in resample
    self.samples, self.sample_rate, target_sample_rate, filter=filter)
  File "/usr/local/lib/python3.6/dist-packages/resampy/core.py", line 92, in resample
    'Only floating-point types are supported.'.format(x.dtype))
TypeError: Unable to resample signals of dtype=float32. Only floating-point types are supported.
用的是python3.6.9和paddlepaddle-gpu1.8.5

**Comment by zh794390558** [comment]
resample 升级到 0.2.2 试下。

**Comment by TyroneHe-0926** [comment]
哈哈升级好之后就好了，不过看了下那个resampy的core.py里就是把之前版本raise这个报错的error给删掉了-＿-， 之前我也是把那个raise error哪里直接comment out就好了但是忘记更新了
多谢啦！
