### ISSUE TITLE
InvalidArgumentError: Cannot parse tensor desc

### ISSUE THREAD

**Issue by weiaoliu** [PaddlePaddle/PaddleSpeech#554]
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: data_type
/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "infer.py", line 120, in <module>
    show(audiopath)
  File "infer.py", line 114, in show
    result = infer()
  File "infer.py", line 91, in infer
    feeding_dict=data_generator.feeding)
  File "/home/weiao/port/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/home/weiao/port/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/io.py", line 877, in load_params
    filename=filename)
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/io.py", line 805, in load_vars
    executor.run(load_prog)
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::TensorFromStream(std::istream&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&)
3   paddle::framework::DeserializeFromStream(std::istream&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&)
4   paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, paddle::platform::Place const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const
5   paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
8   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
9   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
10  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
11  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
12  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/io.py", line 803, in load_vars
    'model_from_memory': vars_from_memory
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/home/weiao/anaconda3/envs/deep/lib/python2.7/site-packages/paddle/fluid/io.py", line 877, in load_params
    filename=filename)
  File "/home/weiao/port/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/home/weiao/port/model_utils/model.py", line 411, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "infer.py", line 91, in infer
    feeding_dict=data_generator.feeding)
  File "infer.py", line 114, in show
    result = infer()
  File "infer.py", line 120, in <module>
    show(audiopath)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] at (/paddle/paddle/fluid/framework/tensor_util.cu:527)
  [operator < load_combine > error]

**Comment by DemoMoon** [comment]
最后 解决了吗？
