### ISSUE TITLE
引入噪声数据增强后 报错

### ISSUE THREAD

**Issue by wuchaowei2012** [PaddlePaddle/PaddleSpeech#559]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/DeepSpeech/DeepSpeech/deepspeech/frontend/augmentor/noise_perturb.py", line 71, in transform_audio
    audio_segment.add_noise(noise_segment, snr_dB, allow_downsampling=True, rng=self._rng)
  File "/DeepSpeech/DeepSpeech/deepspeech/frontend/audio.py", line 597, in add_noise
    if noise.sample_rate != self.sample_rate:
AttributeError: 'NoneType' object has no attribute 'sample_rate'

但是 实际检查的时候，发现噪声数据 存在，且长度正确。

**Comment by zh794390558** [comment]
check 下noise和self是否有sample rate 属性。

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
