### ISSUE TITLE
Failed in starting demo server!

### ISSUE THREAD

**Issue by xqmmy** [PaddlePaddle/PaddleSpeech#689]
Traceback (most recent call last):
  File "/home/DeepSpeech/examples/aishell/s0/../../..//deepspeech/exps/deepspeech2/bin/deploy/server.py", line 128, in <module>
    main(config, args)
  File "/home/DeepSpeech/examples/aishell/s0/../../..//deepspeech/exps/deepspeech2/bin/deploy/server.py", line 94, in main
    start_server(config, args)
  File "/home/DeepSpeech/examples/aishell/s0/../../..//deepspeech/exps/deepspeech2/bin/deploy/server.py", line 40, in start_server
    dataset = ManifestDataset.from_config(config)
  File "/home/DeepSpeech/deepspeech/io/dataset.py", line 57, in from_config
    assert config.data.manifest
AssertionError
Failed in starting demo server!

**Comment by zh794390558** [comment]
麻烦pull下develop最新代码。
