### ISSUE TITLE
aishell训练完的模型，测试效果，启动客户端报错，启动命令 bash ./local/client.sh ，按下空格键 ，报错如下

### ISSUE THREAD

**Issue by wonder2025** [PaddlePaddle/PaddleSpeech#727]
ys:1: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
 Start Recording ...                                                                              Traceback (most recent call last):
  File "/home/DeepSpeech/examples/aishell/s0/../../..//deepspeech/exps/deepspeech2/bin/deploy/client.py", line 65, in callback
    socket_send(args.host_ip, args.host_port, ''.join(data_list))
TypeError: sequence item 0: expected str instance, bytes found
Traceback (most recent call last):
  File "/home/DeepSpeech/examples/aishell/s0/../../..//deepspeech/exps/deepspeech2/bin/deploy/client.py", line 95, in <module>
    main()
  File "/home/DeepSpeech/examples/aishell/s0/../../..//deepspeech/exps/deepspeech2/bin/deploy/client.py", line 85, in main
    if keyboard.record('esc'):
  File "/home/miniconda3/lib/python3.9/site-packages/keyboard/__init__.py", line 1042, in record
    wait(until, suppress=suppress, trigger_on_release=trigger_on_release)
  File "/home/miniconda3/lib/python3.9/site-packages/keyboard/__init__.py", line 882, in wait
    lock.wait()
  File "/home/miniconda3/lib/python3.9/site-packages/keyboard/__init__.py", line 117, in wait
    if _UninterruptibleEvent.wait(self, 0.5):
  File "/home/miniconda3/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/miniconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
TypeError
Failed in starting demo client!

**Comment by zh794390558** [comment]
使用 https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deepspeech/exps/deepspeech2/bin/deploy/send.py 测试吧
