### ISSUE TITLE
dataloader多线程读取数据报错：无'_shutdown'属性

### ISSUE THREAD

**Issue by zdyupup** [PaddlePaddle/PaddleSpeech#762]
[ERROR 2021/08/18 08:55:40 trainer.py:182] Can't pickle <class 'deepspeech.io.dataset.local_data'>: attribute lookup local_data on deepspeech.io.dataset failed
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f752502b290>
Traceback (most recent call last):
  File "/DeepSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 763, in __del__
    self._try_shutdown_all()
  File "/DeepSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 577, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

num_workers=0可以正常训练，但速度太慢了，然后设置不为0时就会报上述错误，请问怎么解决该问题？

**Comment by zh794390558** [comment]
这个建议升级paddle到2.1.2版本，目前这个版本io部分修复了几个Bug。

**Comment by zdyupup** [comment]
好的，谢谢
