### ISSUE TITLE
在运行example/tiny/s0/local/test.sh时报错

### ISSUE THREAD

**Issue by 26903651** [PaddlePaddle/PaddleSpeech#893]
使用的docker环境，镜像为registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda10.2-cudnn7，解决了各种问题后，终于环境编译通过，现在运行tiny/run.sh进行测试，在运行到test.sh时会发生错误，找不到解决方法，请求帮助。以下为报错信息

2021-10-14 08:27:28.545 | INFO     | deepspeech.exps.deepspeech2.model:test:358 - Test Total Examples: 10
2021-10-14 08:27:28,605 - auto_log.autolog - INFO - Init logger done!
2021-10-14 08:27:28.841 | INFO     | deepspeech.modules.ctc:_init_ext_scorer:170 - begin to initialize the external scorer for decoding
2021-10-14 08:27:28.842 | INFO     | deepspeech.training.timer:__exit__:44 - Test/Decode Done: 0:00:01.069955
Traceback (most recent call last):
  File "/DeepSpeech/deepspeech/exps/deepspeech2/bin/test.py", line 54, in <module>
    main(config, args)
  File "/DeepSpeech/deepspeech/exps/deepspeech2/bin/test.py", line 28, in main
    main_sp(config, args)
  File "/DeepSpeech/deepspeech/exps/deepspeech2/bin/test.py", line 24, in main_sp
    exp.run_test()
  File "/DeepSpeech/deepspeech/training/trainer.py", line 335, in run_test
    self.test()
  File "/DeepSpeech/deepspeech/utils/mp_tools.py", line 27, in wrapper
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
    result = func(*args, **kwargs)
  File "/DeepSpeech/tools/venv/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/DeepSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/DeepSpeech/deepspeech/exps/deepspeech2/model.py", line 371, in test
    texts_len, fout)
  File "/DeepSpeech/deepspeech/exps/deepspeech2/model.py", line 306, in compute_metrics
    vocab_list, cfg)
  File "/DeepSpeech/deepspeech/exps/deepspeech2/model.py", line 343, in compute_result_transcripts
    num_processes=cfg.num_proc_bsearch)
  File "/DeepSpeech/tools/venv/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/DeepSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/DeepSpeech/deepspeech/models/ds2/deepspeech2.py", line 194, in decode
    decoding_method=decoding_method)
  File "/DeepSpeech/deepspeech/modules/ctc.py", line 237, in init_decode
    vocab_list)
  File "/DeepSpeech/deepspeech/modules/ctc.py", line 172, in _init_ext_scorer
    self._ext_scorer = Scorer(beam_alpha, beam_beta,
NameError: name 'Scorer' is not defined
/DeepSpeech/tools/venv/lib/python3.7/site-packages/scipy/fftpack/__init__.py:103: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/DeepSpeech/tools/venv/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/DeepSpeech/tools/venv/lib/python3.7/site-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg/swig_decoders.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2021-10-14 08:27:29.818 | INFO     | deepspeech.modules.ctc:<module>:30 - ctcdecoder not installed!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/synchronize.py", line 111, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Failed in evaluation!

**Comment by zh794390558** [comment]
File "/DeepSpeech/deepspeech/modules/ctc.py", line 172, in _init_ext_scorer
self._ext_scorer = Scorer(beam_alpha, beam_beta,
NameError: name 'Scorer' is not defined

应该是ctcdecoder没有安装，运行deepspech/setup.sh 后，确认ctcdeocder已安装

**Comment by 26903651** [comment]
请问如何确认，能否手动安装，整个setup.sh安装看起来是正常的

**Comment by 26903651** [comment]
> File "/DeepSpeech/deepspeech/modules/ctc.py", line 172, in _init_ext_scorer self._ext_scorer = Scorer(beam_alpha, beam_beta, NameError: name 'Scorer' is not defined
> 
> 应该是ctcdecoder没有安装，运行deepspech/setup.sh 后，确认ctcdeocder已安装

我尝试往根目录的requirements.txt中加入了ctcdecode, 然后setup.sh，还是不行，报错是一样的，请问如何能确保安装ctcdecoder?

**Comment by 26903651** [comment]
而且我用pip list, 里面是可以看到swig-decoders，版本1.1

**Comment by zh794390558** [comment]
#901 修复了此问题。
