### ISSUE TITLE
请问你们这个支持在3090上运行吗

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleSpeech#991]
请问你们这个支持在3090上运行吗？我的系统是centos，显卡为3090，cuda为11.1，python为3.8

我按照readme的指令运行后报错。
指令为 FLAGS_allocator_strategy=naive_best_fit FLAGS_fraction_of_gpu_memory_to_use=0.01 python3 ${BIN_DIR}/synthesize_e2e.py   --fastspeech2-config=fastspeech2_nosil_baker_ckpt_0.4/default.yaml   --fastspeech2-checkpoint=fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz   --fastspeech2-stat=fastspeech2_nosil_baker_ckpt_0.4/speech_stats.npy   --pwg-config=pwg_baker_ckpt_0.4/pwg_default.yaml   --pwg-checkpoint=pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz   --pwg-stat=pwg_baker_ckpt_0.4/pwg_stats.npy   --text=${BIN_DIR}/../sentences.txt   --output-dir=exp/default/test_e2e   --inference-dir=exp/default/inference   --phones-dict=fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
应该和readme上的一致

报错信息：
Traceback (most recent call last):
  File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/synthesize_e2e.py", line 185, in <module>
    main()
  File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/synthesize_e2e.py", line 181, in main
    evaluate(args, fastspeech2_config, pwg_config)
  File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/synthesize_e2e.py", line 51, in evaluate
    model = FastSpeech2(
  File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 166, in __init__
    encoder_input_layer = nn.Embedding(
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1386, in __init__
    self.weight = self.create_parameter(
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 373, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3163, in append_op
    _dygraph_tracer().trace_op(type,
  File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
SystemError: (Fatal) Operator uniform_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

paddle-gpu安装是没有问题的，运行fluid.install_check.run_check()显示成功

请问上面的报错是什么原因呢？

**Comment by yt605155624** [comment]
这个应该是 paddle 版本的问题，好像 paddle 不支持 cuda 11.1，建议去 paddle 提交 issue 
https://github.com/PaddlePaddle/Paddle/issues/35008
核心报错是这句哈 cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device.

**Comment by ZZHHogan** [comment]
好的谢谢，不过paddle 应该是支持的，因为我之前用11.1、11.2都能运行paddleocr。那我去paddle下提issue

**Comment by yt605155624** [comment]
看你的 paddle 的版本是 2.0.0 ，我们的 parallel wave gan 只能在最新的 develop  或者这两天即将发布的 paddle 2.2.0 上跑起来训练哈（用到了最新支持的 stft 算子），说不定你可以先装个 paddle develop 试试，我在 paddle 官网安装教程上没有看到 cuda 11.1 这个选项卡

**Comment by xxllp** [comment]
我的本地都11.4了 这个咋弄

**Comment by yt605155624** [comment]
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 可以根据官网下载安装 cuda cudnn paddle 匹配的版本，cuda 11.4 对于 paddle 来说太高了，建议降低版本

**Comment by BoragoCode** [comment]
同问，这个 问题咋解决呢
